/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * I Watch Football API
 * The API Docs for I Watch Football
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import { clientInstance } from '../client-instance';
/**
 * @summary Create Address
 */
export const createAddress = (createAddressDTO) => {
    return clientInstance({ url: `/address`, method: 'POST',
        headers: { 'Content-Type': 'application/json', },
        data: createAddressDTO
    });
};
export const getCreateAddressMutationOptions = (options) => {
    const { mutation: mutationOptions } = options !== null && options !== void 0 ? options : {};
    const mutationFn = (props) => {
        const { data } = props !== null && props !== void 0 ? props : {};
        return createAddress(data);
    };
    return Object.assign({ mutationFn }, mutationOptions);
};
/**
* @summary Create Address
*/
export const useCreateAddress = (options) => {
    const mutationOptions = getCreateAddressMutationOptions(options);
    return useMutation(mutationOptions);
};
/**
* @summary Get all Addresss
*/
export const getAllAddress = (signal) => {
    return clientInstance({ url: `/address`, method: 'GET', signal
    });
};
export const getGetAllAddressQueryKey = () => {
    return [`/address`];
};
export const getGetAllAddressQueryOptions = (options) => {
    var _a;
    const { query: queryOptions } = options !== null && options !== void 0 ? options : {};
    const queryKey = (_a = queryOptions === null || queryOptions === void 0 ? void 0 : queryOptions.queryKey) !== null && _a !== void 0 ? _a : getGetAllAddressQueryKey();
    const queryFn = ({ signal }) => getAllAddress(signal);
    return Object.assign({ queryKey, queryFn }, queryOptions);
};
/**
 * @summary Get all Addresss
 */
export const useGetAllAddress = (options) => {
    const queryOptions = getGetAllAddressQueryOptions(options);
    const query = useQuery(queryOptions);
    query.queryKey = queryOptions.queryKey;
    return query;
};
/**
 * @summary Get all Addresss
 */
export const getQueryAddress = (params, signal) => {
    return clientInstance({ url: `/address/query`, method: 'GET',
        params, signal
    });
};
export const getGetQueryAddressQueryKey = (params) => {
    return [`/address/query`, ...(params ? [params] : [])];
};
export const getGetQueryAddressQueryOptions = (params, options) => {
    var _a;
    const { query: queryOptions } = options !== null && options !== void 0 ? options : {};
    const queryKey = (_a = queryOptions === null || queryOptions === void 0 ? void 0 : queryOptions.queryKey) !== null && _a !== void 0 ? _a : getGetQueryAddressQueryKey(params);
    const queryFn = ({ signal }) => getQueryAddress(params, signal);
    return Object.assign({ queryKey, queryFn }, queryOptions);
};
/**
 * @summary Get all Addresss
 */
export const useGetQueryAddress = (params, options) => {
    const queryOptions = getGetQueryAddressQueryOptions(params, options);
    const query = useQuery(queryOptions);
    query.queryKey = queryOptions.queryKey;
    return query;
};
/**
 * @summary Get count of Addresss
 */
export const getCountAddress = (params, signal) => {
    return clientInstance({ url: `/address/count`, method: 'GET',
        params, signal
    });
};
export const getGetCountAddressQueryKey = (params) => {
    return [`/address/count`, ...(params ? [params] : [])];
};
export const getGetCountAddressQueryOptions = (params, options) => {
    var _a;
    const { query: queryOptions } = options !== null && options !== void 0 ? options : {};
    const queryKey = (_a = queryOptions === null || queryOptions === void 0 ? void 0 : queryOptions.queryKey) !== null && _a !== void 0 ? _a : getGetCountAddressQueryKey(params);
    const queryFn = ({ signal }) => getCountAddress(params, signal);
    return Object.assign({ queryKey, queryFn }, queryOptions);
};
/**
 * @summary Get count of Addresss
 */
export const useGetCountAddress = (params, options) => {
    const queryOptions = getGetCountAddressQueryOptions(params, options);
    const query = useQuery(queryOptions);
    query.queryKey = queryOptions.queryKey;
    return query;
};
/**
 * @summary Get one Address
 */
export const getOneAddress = (id, signal) => {
    return clientInstance({ url: `/address/${id}`, method: 'GET', signal
    });
};
export const getGetOneAddressQueryKey = (id) => {
    return [`/address/${id}`];
};
export const getGetOneAddressQueryOptions = (id, options) => {
    var _a;
    const { query: queryOptions } = options !== null && options !== void 0 ? options : {};
    const queryKey = (_a = queryOptions === null || queryOptions === void 0 ? void 0 : queryOptions.queryKey) !== null && _a !== void 0 ? _a : getGetOneAddressQueryKey(id);
    const queryFn = ({ signal }) => getOneAddress(id, signal);
    return Object.assign({ queryKey, queryFn, enabled: !!(id) }, queryOptions);
};
/**
 * @summary Get one Address
 */
export const useGetOneAddress = (id, options) => {
    const queryOptions = getGetOneAddressQueryOptions(id, options);
    const query = useQuery(queryOptions);
    query.queryKey = queryOptions.queryKey;
    return query;
};
/**
 * @summary Update one Address
 */
export const updateOneAddress = (id, address) => {
    return clientInstance({ url: `/address/${id}`, method: 'PATCH',
        headers: { 'Content-Type': 'application/json', },
        data: address
    });
};
export const getUpdateOneAddressMutationOptions = (options) => {
    const { mutation: mutationOptions } = options !== null && options !== void 0 ? options : {};
    const mutationFn = (props) => {
        const { id, data } = props !== null && props !== void 0 ? props : {};
        return updateOneAddress(id, data);
    };
    return Object.assign({ mutationFn }, mutationOptions);
};
/**
* @summary Update one Address
*/
export const useUpdateOneAddress = (options) => {
    const mutationOptions = getUpdateOneAddressMutationOptions(options);
    return useMutation(mutationOptions);
};
/**
* @summary Delete one Address
*/
export const deleteOneAddress = (id) => {
    return clientInstance({ url: `/address/${id}`, method: 'DELETE'
    });
};
export const getDeleteOneAddressMutationOptions = (options) => {
    const { mutation: mutationOptions } = options !== null && options !== void 0 ? options : {};
    const mutationFn = (props) => {
        const { id } = props !== null && props !== void 0 ? props : {};
        return deleteOneAddress(id);
    };
    return Object.assign({ mutationFn }, mutationOptions);
};
/**
* @summary Delete one Address
*/
export const useDeleteOneAddress = (options) => {
    const mutationOptions = getDeleteOneAddressMutationOptions(options);
    return useMutation(mutationOptions);
};
/**
* @summary Upload a file for Address
*/
export const uploadAddress = () => {
    return clientInstance({ url: `/address/upload`, method: 'POST'
    });
};
export const getUploadAddressMutationOptions = (options) => {
    const { mutation: mutationOptions } = options !== null && options !== void 0 ? options : {};
    const mutationFn = () => {
        return uploadAddress();
    };
    return Object.assign({ mutationFn }, mutationOptions);
};
/**
* @summary Upload a file for Address
*/
export const useUploadAddress = (options) => {
    const mutationOptions = getUploadAddressMutationOptions(options);
    return useMutation(mutationOptions);
};
/**
* @summary Download file related to Address
*/
export const downloadAddress = (filename, signal) => {
    return clientInstance({ url: `/address/download/${filename}`, method: 'GET', signal
    });
};
export const getDownloadAddressQueryKey = (filename) => {
    return [`/address/download/${filename}`];
};
export const getDownloadAddressQueryOptions = (filename, options) => {
    var _a;
    const { query: queryOptions } = options !== null && options !== void 0 ? options : {};
    const queryKey = (_a = queryOptions === null || queryOptions === void 0 ? void 0 : queryOptions.queryKey) !== null && _a !== void 0 ? _a : getDownloadAddressQueryKey(filename);
    const queryFn = ({ signal }) => downloadAddress(filename, signal);
    return Object.assign({ queryKey, queryFn, enabled: !!(filename) }, queryOptions);
};
/**
 * @summary Download file related to Address
 */
export const useDownloadAddress = (filename, options) => {
    const queryOptions = getDownloadAddressQueryOptions(filename, options);
    const query = useQuery(queryOptions);
    query.queryKey = queryOptions.queryKey;
    return query;
};
//# sourceMappingURL=address.js.map