/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * I Watch Football API
 * The API Docs for I Watch Football
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query'
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query'
import type {
  DataSyncRunDto
} from './iWatchFootballAPI.schemas'
import { clientInstance } from '../client-instance';




/**
 * Runs StatsBomb (optional) then API-Sports steps under a shared maxApiRequests budget. When Redis is configured, defaults to async (BullMQ) to avoid HTTP timeouts; poll GET /admin/data-sync/jobs/:id. Use resumeJobId to continue checkpoints after partial runs or crashes.
 * @summary One-click bulk sync (StatsBomb + budgeted API-Sports)
 */
export const dataSyncControllerRun = (
    dataSyncRunDto: DataSyncRunDto,
 ) => {
      
      
      return clientInstance<void>(
      {url: `/admin/data-sync/run`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: dataSyncRunDto
    },
      );
    }
  


export const getDataSyncControllerRunMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof dataSyncControllerRun>>, TError,{data: DataSyncRunDto}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof dataSyncControllerRun>>, TError,{data: DataSyncRunDto}, TContext> => {
const {mutation: mutationOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof dataSyncControllerRun>>, {data: DataSyncRunDto}> = (props) => {
          const {data} = props ?? {};

          return  dataSyncControllerRun(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DataSyncControllerRunMutationResult = NonNullable<Awaited<ReturnType<typeof dataSyncControllerRun>>>
    export type DataSyncControllerRunMutationBody = DataSyncRunDto
    export type DataSyncControllerRunMutationError = unknown

    /**
 * @summary One-click bulk sync (StatsBomb + budgeted API-Sports)
 */
export const useDataSyncControllerRun = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof dataSyncControllerRun>>, TError,{data: DataSyncRunDto}, TContext>, }
): UseMutationResult<
        Awaited<ReturnType<typeof dataSyncControllerRun>>,
        TError,
        {data: DataSyncRunDto},
        TContext
      > => {

      const mutationOptions = getDataSyncControllerRunMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * @summary Get sync job, steps, and cursors
 */
export const dataSyncControllerGetJob = (
    id: number,
 signal?: AbortSignal
) => {
      
      
      return clientInstance<void>(
      {url: `/admin/data-sync/jobs/${id}`, method: 'GET', signal
    },
      );
    }
  

export const getDataSyncControllerGetJobQueryKey = (id: number,) => {
    return [`/admin/data-sync/jobs/${id}`] as const;
    }

    
export const getDataSyncControllerGetJobQueryOptions = <TData = Awaited<ReturnType<typeof dataSyncControllerGetJob>>, TError = unknown>(id: number, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof dataSyncControllerGetJob>>, TError, TData>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getDataSyncControllerGetJobQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof dataSyncControllerGetJob>>> = ({ signal }) => dataSyncControllerGetJob(id, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof dataSyncControllerGetJob>>, TError, TData> & { queryKey: QueryKey }
}

export type DataSyncControllerGetJobQueryResult = NonNullable<Awaited<ReturnType<typeof dataSyncControllerGetJob>>>
export type DataSyncControllerGetJobQueryError = unknown

/**
 * @summary Get sync job, steps, and cursors
 */
export const useDataSyncControllerGetJob = <TData = Awaited<ReturnType<typeof dataSyncControllerGetJob>>, TError = unknown>(
 id: number, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof dataSyncControllerGetJob>>, TError, TData>, }

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getDataSyncControllerGetJobQueryOptions(id,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



