/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * I Watch Football API
 * The API Docs for I Watch Football
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import { clientInstance } from '../client-instance';
/**
 * Either pass `country` + `season` (fetches live) or paste `response` from discover. Upserts competitions/seasons. By default, also runs up to `maxStandingsRequests` GET /standings calls (one per league) to upsert teams, competitionStanding, and teamCompetitionSeason — skipping cups and leagues without standings coverage to limit API usage.
 * @summary Import competitions + seasons from API-Sports /leagues
 */
export const apiSportsControllerImportLeagues = (apiSportsImportLeaguesDto) => {
    return clientInstance({ url: `/api-sports/sync/import/leagues`, method: 'POST',
        headers: { 'Content-Type': 'application/json', },
        data: apiSportsImportLeaguesDto
    });
};
export const getApiSportsControllerImportLeaguesMutationOptions = (options) => {
    const { mutation: mutationOptions } = options !== null && options !== void 0 ? options : {};
    const mutationFn = (props) => {
        const { data } = props !== null && props !== void 0 ? props : {};
        return apiSportsControllerImportLeagues(data);
    };
    return Object.assign({ mutationFn }, mutationOptions);
};
/**
* @summary Import competitions + seasons from API-Sports /leagues
*/
export const useApiSportsControllerImportLeagues = (options) => {
    const mutationOptions = getApiSportsControllerImportLeaguesMutationOptions(options);
    return useMutation(mutationOptions);
};
/**
* Requires API key (API_SPORTS_KEY or FOOTBALLAPISPORTS_API_KEY). Maps teams by metadata.providers.apisports.externalId.
* @summary Sync league standings from API-Sports
*/
export const apiSportsControllerSyncStandings = (apiSportsSyncStandingsDto) => {
    return clientInstance({ url: `/api-sports/sync/standings`, method: 'POST',
        headers: { 'Content-Type': 'application/json', },
        data: apiSportsSyncStandingsDto
    });
};
export const getApiSportsControllerSyncStandingsMutationOptions = (options) => {
    const { mutation: mutationOptions } = options !== null && options !== void 0 ? options : {};
    const mutationFn = (props) => {
        const { data } = props !== null && props !== void 0 ? props : {};
        return apiSportsControllerSyncStandings(data);
    };
    return Object.assign({ mutationFn }, mutationOptions);
};
/**
* @summary Sync league standings from API-Sports
*/
export const useApiSportsControllerSyncStandings = (options) => {
    const mutationOptions = getApiSportsControllerSyncStandingsMutationOptions(options);
    return useMutation(mutationOptions);
};
/**
* Only processes players with metadata.providers.apisports.externalId (or metadata.apisportsPlayerId).
* @summary Enrich player DOB, nationality, height from API-Sports
*/
export const apiSportsControllerEnrichPlayers = (apiSportsEnrichPlayersDto) => {
    return clientInstance({ url: `/api-sports/enrich/players`, method: 'POST',
        headers: { 'Content-Type': 'application/json', },
        data: apiSportsEnrichPlayersDto
    });
};
export const getApiSportsControllerEnrichPlayersMutationOptions = (options) => {
    const { mutation: mutationOptions } = options !== null && options !== void 0 ? options : {};
    const mutationFn = (props) => {
        const { data } = props !== null && props !== void 0 ? props : {};
        return apiSportsControllerEnrichPlayers(data);
    };
    return Object.assign({ mutationFn }, mutationOptions);
};
/**
* @summary Enrich player DOB, nationality, height from API-Sports
*/
export const useApiSportsControllerEnrichPlayers = (options) => {
    const mutationOptions = getApiSportsControllerEnrichPlayersMutationOptions(options);
    return useMutation(mutationOptions);
};
/**
* Upserts `fixture` rows by `metadata.providers.apisports.externalId`, or merges into an existing same-competition fixture when kickoff differs by ≤6h and teams match (and both sides agree on score when finalized). Requires competition + season (yearStart/yearEnd) and teams already linked for that league. **`syncStandingsAfter`: true** adds one **`/standings`** call; **`recomputeStandingsFromFixturesAfter`: true** rebuilds ladder from scored fixtures (+0 requests). **`syncPrimaryVenuesAfter`: true** runs paged **`GET /teams`** and links each club **`venue`** to **`teamStadium`** as primary home (not match venue). Fixture upserts use **`fixtureUpsertConcurrency`**. With `from`/`to`, API-Football returns all fixtures in one call and rejects `page`; `allPages`/`maxPages` here are ignored.
* @summary Import fixtures into DB (API-Football /fixtures)
*/
export const apiSportsControllerImportFixtures = (apiSportsImportFixturesDto) => {
    return clientInstance({ url: `/api-sports/sync/import/fixtures`, method: 'POST',
        headers: { 'Content-Type': 'application/json', },
        data: apiSportsImportFixturesDto
    });
};
export const getApiSportsControllerImportFixturesMutationOptions = (options) => {
    const { mutation: mutationOptions } = options !== null && options !== void 0 ? options : {};
    const mutationFn = (props) => {
        const { data } = props !== null && props !== void 0 ? props : {};
        return apiSportsControllerImportFixtures(data);
    };
    return Object.assign({ mutationFn }, mutationOptions);
};
/**
* @summary Import fixtures into DB (API-Football /fixtures)
*/
export const useApiSportsControllerImportFixtures = (options) => {
    const mutationOptions = getApiSportsControllerImportFixturesMutationOptions(options);
    return useMutation(mutationOptions);
};
/**
* One **`GET /teams?league=&season=`** (no `page` — API-Football rejects `page` with this filter and returns all teams in one response). For each row, resolves the local team by `metadata.providers.apisports.externalId`, upserts `stadium` from the club **`venue`**, and upserts **`teamStadium`** with `metadata.relationship: primary_home` and `source: api-sports-teams`.
* @summary Link primary stadiums from API-Football GET /teams
*/
export const apiSportsControllerImportTeamPrimaryVenues = (apiSportsSyncPrimaryVenuesDto) => {
    return clientInstance({ url: `/api-sports/sync/import/team-primary-venues`, method: 'POST',
        headers: { 'Content-Type': 'application/json', },
        data: apiSportsSyncPrimaryVenuesDto
    });
};
export const getApiSportsControllerImportTeamPrimaryVenuesMutationOptions = (options) => {
    const { mutation: mutationOptions } = options !== null && options !== void 0 ? options : {};
    const mutationFn = (props) => {
        const { data } = props !== null && props !== void 0 ? props : {};
        return apiSportsControllerImportTeamPrimaryVenues(data);
    };
    return Object.assign({ mutationFn }, mutationOptions);
};
/**
* @summary Link primary stadiums from API-Football GET /teams
*/
export const useApiSportsControllerImportTeamPrimaryVenues = (options) => {
    const mutationOptions = getApiSportsControllerImportTeamPrimaryVenuesMutationOptions(options);
    return useMutation(mutationOptions);
};
/**
* Creates players when missing, deduping by API-Sports id first, then strict name+DOB match. Caps pages/requests to protect daily quota.
* @summary Import missing players from API-Sports /players (league+season)
*/
export const apiSportsControllerImportPlayers = (apiSportsImportPlayersDto) => {
    return clientInstance({ url: `/api-sports/sync/import/players`, method: 'POST',
        headers: { 'Content-Type': 'application/json', },
        data: apiSportsImportPlayersDto
    });
};
export const getApiSportsControllerImportPlayersMutationOptions = (options) => {
    const { mutation: mutationOptions } = options !== null && options !== void 0 ? options : {};
    const mutationFn = (props) => {
        const { data } = props !== null && props !== void 0 ? props : {};
        return apiSportsControllerImportPlayers(data);
    };
    return Object.assign({ mutationFn }, mutationOptions);
};
/**
* @summary Import missing players from API-Sports /players (league+season)
*/
export const useApiSportsControllerImportPlayers = (options) => {
    const mutationOptions = getApiSportsControllerImportPlayersMutationOptions(options);
    return useMutation(mutationOptions);
};
/**
* Resolves players and teams via metadata.providers.apisports.externalId. Skips rows that cannot be mapped.
* @summary Import transfers for an API-Sports team
*/
export const apiSportsControllerSyncTransfers = (apiSportsSyncTransfersDto) => {
    return clientInstance({ url: `/api-sports/sync/transfers`, method: 'POST',
        headers: { 'Content-Type': 'application/json', },
        data: apiSportsSyncTransfersDto
    });
};
export const getApiSportsControllerSyncTransfersMutationOptions = (options) => {
    const { mutation: mutationOptions } = options !== null && options !== void 0 ? options : {};
    const mutationFn = (props) => {
        const { data } = props !== null && props !== void 0 ? props : {};
        return apiSportsControllerSyncTransfers(data);
    };
    return Object.assign({ mutationFn }, mutationOptions);
};
/**
* @summary Import transfers for an API-Sports team
*/
export const useApiSportsControllerSyncTransfers = (options) => {
    const mutationOptions = getApiSportsControllerSyncTransfersMutationOptions(options);
    return useMutation(mutationOptions);
};
/**
* Proxies GET /leagues. See API-Football leagues docs for full filter list.
* @summary List/search leagues from API-Sports
*/
export const apiSportsControllerDiscoverLeagues = (params, signal) => {
    return clientInstance({ url: `/api-sports/discover/leagues`, method: 'GET',
        params, signal
    });
};
export const getApiSportsControllerDiscoverLeaguesQueryKey = (params) => {
    return [`/api-sports/discover/leagues`, ...(params ? [params] : [])];
};
export const getApiSportsControllerDiscoverLeaguesQueryOptions = (params, options) => {
    var _a;
    const { query: queryOptions } = options !== null && options !== void 0 ? options : {};
    const queryKey = (_a = queryOptions === null || queryOptions === void 0 ? void 0 : queryOptions.queryKey) !== null && _a !== void 0 ? _a : getApiSportsControllerDiscoverLeaguesQueryKey(params);
    const queryFn = ({ signal }) => apiSportsControllerDiscoverLeagues(params, signal);
    return Object.assign({ queryKey, queryFn }, queryOptions);
};
/**
 * @summary List/search leagues from API-Sports
 */
export const useApiSportsControllerDiscoverLeagues = (params, options) => {
    const queryOptions = getApiSportsControllerDiscoverLeaguesQueryOptions(params, options);
    const query = useQuery(queryOptions);
    query.queryKey = queryOptions.queryKey;
    return query;
};
/**
 * Proxies GET /leagues?id={id}. Use `response[0].seasons` for valid `season` years for standings.
 * @summary One league + seasons coverage
 */
export const apiSportsControllerDiscoverLeagueById = (id, signal) => {
    return clientInstance({ url: `/api-sports/discover/league/${id}`, method: 'GET', signal
    });
};
export const getApiSportsControllerDiscoverLeagueByIdQueryKey = (id) => {
    return [`/api-sports/discover/league/${id}`];
};
export const getApiSportsControllerDiscoverLeagueByIdQueryOptions = (id, options) => {
    var _a;
    const { query: queryOptions } = options !== null && options !== void 0 ? options : {};
    const queryKey = (_a = queryOptions === null || queryOptions === void 0 ? void 0 : queryOptions.queryKey) !== null && _a !== void 0 ? _a : getApiSportsControllerDiscoverLeagueByIdQueryKey(id);
    const queryFn = ({ signal }) => apiSportsControllerDiscoverLeagueById(id, signal);
    return Object.assign({ queryKey, queryFn, enabled: !!(id) }, queryOptions);
};
/**
 * @summary One league + seasons coverage
 */
export const useApiSportsControllerDiscoverLeagueById = (id, options) => {
    const queryOptions = getApiSportsControllerDiscoverLeagueByIdQueryOptions(id, options);
    const query = useQuery(queryOptions);
    query.queryKey = queryOptions.queryKey;
    return query;
};
/**
 * Proxies **GET /fixtures** — see [API-Football documentation v3](https://www.api-football.com/documentation-v3). **Efficient:** `date=YYYY-MM-DD` (+ optional `timezone` for “today”); narrow with `league`+`season`; batch with `ids=id1-id2`; use **GET /api-sports/discover/fixtures/live** for all live matches in one call. **allPages=true** merges pagination server-side (multiple upstream requests, capped by `maxPages`).
 * @summary Fixtures from API-Sports (API-Football v3)
 */
export const apiSportsControllerDiscoverFixtures = (params, signal) => {
    return clientInstance({ url: `/api-sports/discover/fixtures`, method: 'GET',
        params, signal
    });
};
export const getApiSportsControllerDiscoverFixturesQueryKey = (params) => {
    return [`/api-sports/discover/fixtures`, ...(params ? [params] : [])];
};
export const getApiSportsControllerDiscoverFixturesQueryOptions = (params, options) => {
    var _a;
    const { query: queryOptions } = options !== null && options !== void 0 ? options : {};
    const queryKey = (_a = queryOptions === null || queryOptions === void 0 ? void 0 : queryOptions.queryKey) !== null && _a !== void 0 ? _a : getApiSportsControllerDiscoverFixturesQueryKey(params);
    const queryFn = ({ signal }) => apiSportsControllerDiscoverFixtures(params, signal);
    return Object.assign({ queryKey, queryFn }, queryOptions);
};
/**
 * @summary Fixtures from API-Sports (API-Football v3)
 */
export const useApiSportsControllerDiscoverFixtures = (params, options) => {
    const queryOptions = getApiSportsControllerDiscoverFixturesQueryOptions(params, options);
    const query = useQuery(queryOptions);
    query.queryKey = queryOptions.queryKey;
    return query;
};
/**
 * Proxies **GET /fixtures?live=all** — preferred over polling `/fixtures/events` per fixture. See [API-Football v3](https://www.api-football.com/documentation-v3).
 * @summary Live fixtures + events (one API call)
 */
export const apiSportsControllerDiscoverLiveFixtures = (signal) => {
    return clientInstance({ url: `/api-sports/discover/fixtures/live`, method: 'GET', signal
    });
};
export const getApiSportsControllerDiscoverLiveFixturesQueryKey = () => {
    return [`/api-sports/discover/fixtures/live`];
};
export const getApiSportsControllerDiscoverLiveFixturesQueryOptions = (options) => {
    var _a;
    const { query: queryOptions } = options !== null && options !== void 0 ? options : {};
    const queryKey = (_a = queryOptions === null || queryOptions === void 0 ? void 0 : queryOptions.queryKey) !== null && _a !== void 0 ? _a : getApiSportsControllerDiscoverLiveFixturesQueryKey();
    const queryFn = ({ signal }) => apiSportsControllerDiscoverLiveFixtures(signal);
    return Object.assign({ queryKey, queryFn }, queryOptions);
};
/**
 * @summary Live fixtures + events (one API call)
 */
export const useApiSportsControllerDiscoverLiveFixtures = (options) => {
    const queryOptions = getApiSportsControllerDiscoverLiveFixturesQueryOptions(options);
    const query = useQuery(queryOptions);
    query.queryKey = queryOptions.queryKey;
    return query;
};
/**
 * Proxies **GET /teams** — each entry includes **`team`** and **`venue`** (registered home ground). See [API-Football documentation v3](https://www.api-football.com/documentation-v3). Typical: `league` + `season`, or `id` / `team` for one club.
 * @summary Teams (+ club venue) from API-Sports
 */
export const apiSportsControllerDiscoverTeams = (params, signal) => {
    return clientInstance({ url: `/api-sports/discover/teams`, method: 'GET',
        params, signal
    });
};
export const getApiSportsControllerDiscoverTeamsQueryKey = (params) => {
    return [`/api-sports/discover/teams`, ...(params ? [params] : [])];
};
export const getApiSportsControllerDiscoverTeamsQueryOptions = (params, options) => {
    var _a;
    const { query: queryOptions } = options !== null && options !== void 0 ? options : {};
    const queryKey = (_a = queryOptions === null || queryOptions === void 0 ? void 0 : queryOptions.queryKey) !== null && _a !== void 0 ? _a : getApiSportsControllerDiscoverTeamsQueryKey(params);
    const queryFn = ({ signal }) => apiSportsControllerDiscoverTeams(params, signal);
    return Object.assign({ queryKey, queryFn }, queryOptions);
};
/**
 * @summary Teams (+ club venue) from API-Sports
 */
export const useApiSportsControllerDiscoverTeams = (params, options) => {
    const queryOptions = getApiSportsControllerDiscoverTeamsQueryOptions(params, options);
    const query = useQuery(queryOptions);
    query.queryKey = queryOptions.queryKey;
    return query;
};
/**
 * Proxies GET /countries. Optional: `search`, `code`.
 * @summary Countries from API-Sports
 */
export const apiSportsControllerDiscoverCountries = (params, signal) => {
    return clientInstance({ url: `/api-sports/discover/countries`, method: 'GET',
        params, signal
    });
};
export const getApiSportsControllerDiscoverCountriesQueryKey = (params) => {
    return [`/api-sports/discover/countries`, ...(params ? [params] : [])];
};
export const getApiSportsControllerDiscoverCountriesQueryOptions = (params, options) => {
    var _a;
    const { query: queryOptions } = options !== null && options !== void 0 ? options : {};
    const queryKey = (_a = queryOptions === null || queryOptions === void 0 ? void 0 : queryOptions.queryKey) !== null && _a !== void 0 ? _a : getApiSportsControllerDiscoverCountriesQueryKey(params);
    const queryFn = ({ signal }) => apiSportsControllerDiscoverCountries(params, signal);
    return Object.assign({ queryKey, queryFn }, queryOptions);
};
/**
 * @summary Countries from API-Sports
 */
export const useApiSportsControllerDiscoverCountries = (params, options) => {
    const queryOptions = getApiSportsControllerDiscoverCountriesQueryOptions(params, options);
    const query = useQuery(queryOptions);
    query.queryKey = queryOptions.queryKey;
    return query;
};
//# sourceMappingURL=api-sports.js.map