/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * I Watch Football API
 * The API Docs for I Watch Football
 * OpenAPI spec version: 1.0
 */
import { useMutation } from '@tanstack/react-query';
import { clientInstance } from '../client-instance';
/**
 * @summary Login user
 */
export const login = (loginBody) => {
    return clientInstance({ url: `/auth/login`, method: 'POST',
        headers: { 'Content-Type': 'application/json', },
        data: loginBody
    });
};
export const getLoginMutationOptions = (options) => {
    const { mutation: mutationOptions } = options !== null && options !== void 0 ? options : {};
    const mutationFn = (props) => {
        const { data } = props !== null && props !== void 0 ? props : {};
        return login(data);
    };
    return Object.assign({ mutationFn }, mutationOptions);
};
/**
* @summary Login user
*/
export const useLogin = (options) => {
    const mutationOptions = getLoginMutationOptions(options);
    return useMutation(mutationOptions);
};
/**
* @summary Register new user
*/
export const register = (registerBody) => {
    return clientInstance({ url: `/auth/register`, method: 'POST',
        headers: { 'Content-Type': 'application/json', },
        data: registerBody
    });
};
export const getRegisterMutationOptions = (options) => {
    const { mutation: mutationOptions } = options !== null && options !== void 0 ? options : {};
    const mutationFn = (props) => {
        const { data } = props !== null && props !== void 0 ? props : {};
        return register(data);
    };
    return Object.assign({ mutationFn }, mutationOptions);
};
/**
* @summary Register new user
*/
export const useRegister = (options) => {
    const mutationOptions = getRegisterMutationOptions(options);
    return useMutation(mutationOptions);
};
//# sourceMappingURL=auth.js.map