/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * I Watch Football API
 * The API Docs for I Watch Football
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import { clientInstance } from '../client-instance';
/**
 * @summary Create Card
 */
export const createCard = (createCardDTO) => {
    return clientInstance({ url: `/card`, method: 'POST',
        headers: { 'Content-Type': 'application/json', },
        data: createCardDTO
    });
};
export const getCreateCardMutationOptions = (options) => {
    const { mutation: mutationOptions } = options !== null && options !== void 0 ? options : {};
    const mutationFn = (props) => {
        const { data } = props !== null && props !== void 0 ? props : {};
        return createCard(data);
    };
    return Object.assign({ mutationFn }, mutationOptions);
};
/**
* @summary Create Card
*/
export const useCreateCard = (options) => {
    const mutationOptions = getCreateCardMutationOptions(options);
    return useMutation(mutationOptions);
};
/**
* @summary Get all Cards
*/
export const getAllCard = (signal) => {
    return clientInstance({ url: `/card`, method: 'GET', signal
    });
};
export const getGetAllCardQueryKey = () => {
    return [`/card`];
};
export const getGetAllCardQueryOptions = (options) => {
    var _a;
    const { query: queryOptions } = options !== null && options !== void 0 ? options : {};
    const queryKey = (_a = queryOptions === null || queryOptions === void 0 ? void 0 : queryOptions.queryKey) !== null && _a !== void 0 ? _a : getGetAllCardQueryKey();
    const queryFn = ({ signal }) => getAllCard(signal);
    return Object.assign({ queryKey, queryFn }, queryOptions);
};
/**
 * @summary Get all Cards
 */
export const useGetAllCard = (options) => {
    const queryOptions = getGetAllCardQueryOptions(options);
    const query = useQuery(queryOptions);
    query.queryKey = queryOptions.queryKey;
    return query;
};
/**
 * @summary Get all Cards
 */
export const getQueryCard = (params, signal) => {
    return clientInstance({ url: `/card/query`, method: 'GET',
        params, signal
    });
};
export const getGetQueryCardQueryKey = (params) => {
    return [`/card/query`, ...(params ? [params] : [])];
};
export const getGetQueryCardQueryOptions = (params, options) => {
    var _a;
    const { query: queryOptions } = options !== null && options !== void 0 ? options : {};
    const queryKey = (_a = queryOptions === null || queryOptions === void 0 ? void 0 : queryOptions.queryKey) !== null && _a !== void 0 ? _a : getGetQueryCardQueryKey(params);
    const queryFn = ({ signal }) => getQueryCard(params, signal);
    return Object.assign({ queryKey, queryFn }, queryOptions);
};
/**
 * @summary Get all Cards
 */
export const useGetQueryCard = (params, options) => {
    const queryOptions = getGetQueryCardQueryOptions(params, options);
    const query = useQuery(queryOptions);
    query.queryKey = queryOptions.queryKey;
    return query;
};
/**
 * @summary Get count of Cards
 */
export const getCountCard = (params, signal) => {
    return clientInstance({ url: `/card/count`, method: 'GET',
        params, signal
    });
};
export const getGetCountCardQueryKey = (params) => {
    return [`/card/count`, ...(params ? [params] : [])];
};
export const getGetCountCardQueryOptions = (params, options) => {
    var _a;
    const { query: queryOptions } = options !== null && options !== void 0 ? options : {};
    const queryKey = (_a = queryOptions === null || queryOptions === void 0 ? void 0 : queryOptions.queryKey) !== null && _a !== void 0 ? _a : getGetCountCardQueryKey(params);
    const queryFn = ({ signal }) => getCountCard(params, signal);
    return Object.assign({ queryKey, queryFn }, queryOptions);
};
/**
 * @summary Get count of Cards
 */
export const useGetCountCard = (params, options) => {
    const queryOptions = getGetCountCardQueryOptions(params, options);
    const query = useQuery(queryOptions);
    query.queryKey = queryOptions.queryKey;
    return query;
};
/**
 * @summary Get one Card
 */
export const getOneCard = (id, signal) => {
    return clientInstance({ url: `/card/${id}`, method: 'GET', signal
    });
};
export const getGetOneCardQueryKey = (id) => {
    return [`/card/${id}`];
};
export const getGetOneCardQueryOptions = (id, options) => {
    var _a;
    const { query: queryOptions } = options !== null && options !== void 0 ? options : {};
    const queryKey = (_a = queryOptions === null || queryOptions === void 0 ? void 0 : queryOptions.queryKey) !== null && _a !== void 0 ? _a : getGetOneCardQueryKey(id);
    const queryFn = ({ signal }) => getOneCard(id, signal);
    return Object.assign({ queryKey, queryFn, enabled: !!(id) }, queryOptions);
};
/**
 * @summary Get one Card
 */
export const useGetOneCard = (id, options) => {
    const queryOptions = getGetOneCardQueryOptions(id, options);
    const query = useQuery(queryOptions);
    query.queryKey = queryOptions.queryKey;
    return query;
};
/**
 * @summary Update one Card
 */
export const updateOneCard = (id, card) => {
    return clientInstance({ url: `/card/${id}`, method: 'PATCH',
        headers: { 'Content-Type': 'application/json', },
        data: card
    });
};
export const getUpdateOneCardMutationOptions = (options) => {
    const { mutation: mutationOptions } = options !== null && options !== void 0 ? options : {};
    const mutationFn = (props) => {
        const { id, data } = props !== null && props !== void 0 ? props : {};
        return updateOneCard(id, data);
    };
    return Object.assign({ mutationFn }, mutationOptions);
};
/**
* @summary Update one Card
*/
export const useUpdateOneCard = (options) => {
    const mutationOptions = getUpdateOneCardMutationOptions(options);
    return useMutation(mutationOptions);
};
/**
* @summary Delete one Card
*/
export const deleteOneCard = (id) => {
    return clientInstance({ url: `/card/${id}`, method: 'DELETE'
    });
};
export const getDeleteOneCardMutationOptions = (options) => {
    const { mutation: mutationOptions } = options !== null && options !== void 0 ? options : {};
    const mutationFn = (props) => {
        const { id } = props !== null && props !== void 0 ? props : {};
        return deleteOneCard(id);
    };
    return Object.assign({ mutationFn }, mutationOptions);
};
/**
* @summary Delete one Card
*/
export const useDeleteOneCard = (options) => {
    const mutationOptions = getDeleteOneCardMutationOptions(options);
    return useMutation(mutationOptions);
};
/**
* @summary Upload a file for Card
*/
export const uploadCard = () => {
    return clientInstance({ url: `/card/upload`, method: 'POST'
    });
};
export const getUploadCardMutationOptions = (options) => {
    const { mutation: mutationOptions } = options !== null && options !== void 0 ? options : {};
    const mutationFn = () => {
        return uploadCard();
    };
    return Object.assign({ mutationFn }, mutationOptions);
};
/**
* @summary Upload a file for Card
*/
export const useUploadCard = (options) => {
    const mutationOptions = getUploadCardMutationOptions(options);
    return useMutation(mutationOptions);
};
/**
* @summary Download file related to Card
*/
export const downloadCard = (filename, signal) => {
    return clientInstance({ url: `/card/download/${filename}`, method: 'GET', signal
    });
};
export const getDownloadCardQueryKey = (filename) => {
    return [`/card/download/${filename}`];
};
export const getDownloadCardQueryOptions = (filename, options) => {
    var _a;
    const { query: queryOptions } = options !== null && options !== void 0 ? options : {};
    const queryKey = (_a = queryOptions === null || queryOptions === void 0 ? void 0 : queryOptions.queryKey) !== null && _a !== void 0 ? _a : getDownloadCardQueryKey(filename);
    const queryFn = ({ signal }) => downloadCard(filename, signal);
    return Object.assign({ queryKey, queryFn, enabled: !!(filename) }, queryOptions);
};
/**
 * @summary Download file related to Card
 */
export const useDownloadCard = (filename, options) => {
    const queryOptions = getDownloadCardQueryOptions(filename, options);
    const query = useQuery(queryOptions);
    query.queryKey = queryOptions.queryKey;
    return query;
};
//# sourceMappingURL=card.js.map