/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * I Watch Football API
 * The API Docs for I Watch Football
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query'
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query'
import type {
  Card,
  CreateCardDTO,
  GetCountCardParams,
  GetQueryCardParams
} from './iWatchFootballAPI.schemas'
import { clientInstance } from '../client-instance';




/**
 * @summary Create Card
 */
export const createCard = (
    createCardDTO: CreateCardDTO,
 ) => {
      
      
      return clientInstance<Card>(
      {url: `/card`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createCardDTO
    },
      );
    }
  


export const getCreateCardMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createCard>>, TError,{data: CreateCardDTO}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof createCard>>, TError,{data: CreateCardDTO}, TContext> => {
const {mutation: mutationOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createCard>>, {data: CreateCardDTO}> = (props) => {
          const {data} = props ?? {};

          return  createCard(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateCardMutationResult = NonNullable<Awaited<ReturnType<typeof createCard>>>
    export type CreateCardMutationBody = CreateCardDTO
    export type CreateCardMutationError = void

    /**
 * @summary Create Card
 */
export const useCreateCard = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createCard>>, TError,{data: CreateCardDTO}, TContext>, }
): UseMutationResult<
        Awaited<ReturnType<typeof createCard>>,
        TError,
        {data: CreateCardDTO},
        TContext
      > => {

      const mutationOptions = getCreateCardMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * @summary Get all Cards
 */
export const getAllCard = (
    
 signal?: AbortSignal
) => {
      
      
      return clientInstance<Card[]>(
      {url: `/card`, method: 'GET', signal
    },
      );
    }
  

export const getGetAllCardQueryKey = () => {
    return [`/card`] as const;
    }

    
export const getGetAllCardQueryOptions = <TData = Awaited<ReturnType<typeof getAllCard>>, TError = void>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getAllCard>>, TError, TData>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAllCardQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAllCard>>> = ({ signal }) => getAllCard(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAllCard>>, TError, TData> & { queryKey: QueryKey }
}

export type GetAllCardQueryResult = NonNullable<Awaited<ReturnType<typeof getAllCard>>>
export type GetAllCardQueryError = void

/**
 * @summary Get all Cards
 */
export const useGetAllCard = <TData = Awaited<ReturnType<typeof getAllCard>>, TError = void>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getAllCard>>, TError, TData>, }

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getGetAllCardQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Get all Cards
 */
export const getQueryCard = (
    params?: GetQueryCardParams,
 signal?: AbortSignal
) => {
      
      
      return clientInstance<Card[]>(
      {url: `/card/query`, method: 'GET',
        params, signal
    },
      );
    }
  

export const getGetQueryCardQueryKey = (params?: GetQueryCardParams,) => {
    return [`/card/query`, ...(params ? [params]: [])] as const;
    }

    
export const getGetQueryCardQueryOptions = <TData = Awaited<ReturnType<typeof getQueryCard>>, TError = void>(params?: GetQueryCardParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getQueryCard>>, TError, TData>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetQueryCardQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getQueryCard>>> = ({ signal }) => getQueryCard(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getQueryCard>>, TError, TData> & { queryKey: QueryKey }
}

export type GetQueryCardQueryResult = NonNullable<Awaited<ReturnType<typeof getQueryCard>>>
export type GetQueryCardQueryError = void

/**
 * @summary Get all Cards
 */
export const useGetQueryCard = <TData = Awaited<ReturnType<typeof getQueryCard>>, TError = void>(
 params?: GetQueryCardParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getQueryCard>>, TError, TData>, }

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getGetQueryCardQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Get count of Cards
 */
export const getCountCard = (
    params?: GetCountCardParams,
 signal?: AbortSignal
) => {
      
      
      return clientInstance<number>(
      {url: `/card/count`, method: 'GET',
        params, signal
    },
      );
    }
  

export const getGetCountCardQueryKey = (params?: GetCountCardParams,) => {
    return [`/card/count`, ...(params ? [params]: [])] as const;
    }

    
export const getGetCountCardQueryOptions = <TData = Awaited<ReturnType<typeof getCountCard>>, TError = void>(params?: GetCountCardParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getCountCard>>, TError, TData>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetCountCardQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getCountCard>>> = ({ signal }) => getCountCard(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getCountCard>>, TError, TData> & { queryKey: QueryKey }
}

export type GetCountCardQueryResult = NonNullable<Awaited<ReturnType<typeof getCountCard>>>
export type GetCountCardQueryError = void

/**
 * @summary Get count of Cards
 */
export const useGetCountCard = <TData = Awaited<ReturnType<typeof getCountCard>>, TError = void>(
 params?: GetCountCardParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getCountCard>>, TError, TData>, }

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getGetCountCardQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Get one Card
 */
export const getOneCard = (
    id: number,
 signal?: AbortSignal
) => {
      
      
      return clientInstance<Card>(
      {url: `/card/${id}`, method: 'GET', signal
    },
      );
    }
  

export const getGetOneCardQueryKey = (id: number,) => {
    return [`/card/${id}`] as const;
    }

    
export const getGetOneCardQueryOptions = <TData = Awaited<ReturnType<typeof getOneCard>>, TError = void>(id: number, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getOneCard>>, TError, TData>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetOneCardQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getOneCard>>> = ({ signal }) => getOneCard(id, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getOneCard>>, TError, TData> & { queryKey: QueryKey }
}

export type GetOneCardQueryResult = NonNullable<Awaited<ReturnType<typeof getOneCard>>>
export type GetOneCardQueryError = void

/**
 * @summary Get one Card
 */
export const useGetOneCard = <TData = Awaited<ReturnType<typeof getOneCard>>, TError = void>(
 id: number, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getOneCard>>, TError, TData>, }

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getGetOneCardQueryOptions(id,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Update one Card
 */
export const updateOneCard = (
    id: number,
    card: Card,
 ) => {
      
      
      return clientInstance<void>(
      {url: `/card/${id}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: card
    },
      );
    }
  


export const getUpdateOneCardMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateOneCard>>, TError,{id: number;data: Card}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof updateOneCard>>, TError,{id: number;data: Card}, TContext> => {
const {mutation: mutationOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateOneCard>>, {id: number;data: Card}> = (props) => {
          const {id,data} = props ?? {};

          return  updateOneCard(id,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateOneCardMutationResult = NonNullable<Awaited<ReturnType<typeof updateOneCard>>>
    export type UpdateOneCardMutationBody = Card
    export type UpdateOneCardMutationError = void

    /**
 * @summary Update one Card
 */
export const useUpdateOneCard = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateOneCard>>, TError,{id: number;data: Card}, TContext>, }
): UseMutationResult<
        Awaited<ReturnType<typeof updateOneCard>>,
        TError,
        {id: number;data: Card},
        TContext
      > => {

      const mutationOptions = getUpdateOneCardMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * @summary Delete one Card
 */
export const deleteOneCard = (
    id: number,
 ) => {
      
      
      return clientInstance<void>(
      {url: `/card/${id}`, method: 'DELETE'
    },
      );
    }
  


export const getDeleteOneCardMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteOneCard>>, TError,{id: number}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof deleteOneCard>>, TError,{id: number}, TContext> => {
const {mutation: mutationOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteOneCard>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  deleteOneCard(id,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteOneCardMutationResult = NonNullable<Awaited<ReturnType<typeof deleteOneCard>>>
    
    export type DeleteOneCardMutationError = void

    /**
 * @summary Delete one Card
 */
export const useDeleteOneCard = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteOneCard>>, TError,{id: number}, TContext>, }
): UseMutationResult<
        Awaited<ReturnType<typeof deleteOneCard>>,
        TError,
        {id: number},
        TContext
      > => {

      const mutationOptions = getDeleteOneCardMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * @summary Upload a file for Card
 */
export const uploadCard = (
    
 ) => {
      
      
      return clientInstance<void>(
      {url: `/card/upload`, method: 'POST'
    },
      );
    }
  


export const getUploadCardMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof uploadCard>>, TError,void, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof uploadCard>>, TError,void, TContext> => {
const {mutation: mutationOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof uploadCard>>, void> = () => {
          

          return  uploadCard()
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UploadCardMutationResult = NonNullable<Awaited<ReturnType<typeof uploadCard>>>
    
    export type UploadCardMutationError = void

    /**
 * @summary Upload a file for Card
 */
export const useUploadCard = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof uploadCard>>, TError,void, TContext>, }
): UseMutationResult<
        Awaited<ReturnType<typeof uploadCard>>,
        TError,
        void,
        TContext
      > => {

      const mutationOptions = getUploadCardMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * @summary Download file related to Card
 */
export const downloadCard = (
    filename: string,
 signal?: AbortSignal
) => {
      
      
      return clientInstance<void>(
      {url: `/card/download/${filename}`, method: 'GET', signal
    },
      );
    }
  

export const getDownloadCardQueryKey = (filename: string,) => {
    return [`/card/download/${filename}`] as const;
    }

    
export const getDownloadCardQueryOptions = <TData = Awaited<ReturnType<typeof downloadCard>>, TError = void>(filename: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof downloadCard>>, TError, TData>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getDownloadCardQueryKey(filename);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof downloadCard>>> = ({ signal }) => downloadCard(filename, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(filename), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof downloadCard>>, TError, TData> & { queryKey: QueryKey }
}

export type DownloadCardQueryResult = NonNullable<Awaited<ReturnType<typeof downloadCard>>>
export type DownloadCardQueryError = void

/**
 * @summary Download file related to Card
 */
export const useDownloadCard = <TData = Awaited<ReturnType<typeof downloadCard>>, TError = void>(
 filename: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof downloadCard>>, TError, TData>, }

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getDownloadCardQueryOptions(filename,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



