/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * I Watch Football API
 * The API Docs for I Watch Football
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query'
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query'
import type {
  CommsPreference,
  CommsPreferenceDTO,
  GetCountCommsPreferenceParams,
  GetQueryCommsPreferenceParams
} from './iWatchFootballAPI.schemas'
import { clientInstance } from '../client-instance';




/**
 * @summary Create CommsPreference
 */
export const createCommsPreference = (
    commsPreferenceDTO: CommsPreferenceDTO,
 ) => {
      
      
      return clientInstance<CommsPreference>(
      {url: `/commsPreference`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: commsPreferenceDTO
    },
      );
    }
  


export const getCreateCommsPreferenceMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createCommsPreference>>, TError,{data: CommsPreferenceDTO}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof createCommsPreference>>, TError,{data: CommsPreferenceDTO}, TContext> => {
const {mutation: mutationOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createCommsPreference>>, {data: CommsPreferenceDTO}> = (props) => {
          const {data} = props ?? {};

          return  createCommsPreference(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateCommsPreferenceMutationResult = NonNullable<Awaited<ReturnType<typeof createCommsPreference>>>
    export type CreateCommsPreferenceMutationBody = CommsPreferenceDTO
    export type CreateCommsPreferenceMutationError = void

    /**
 * @summary Create CommsPreference
 */
export const useCreateCommsPreference = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createCommsPreference>>, TError,{data: CommsPreferenceDTO}, TContext>, }
): UseMutationResult<
        Awaited<ReturnType<typeof createCommsPreference>>,
        TError,
        {data: CommsPreferenceDTO},
        TContext
      > => {

      const mutationOptions = getCreateCommsPreferenceMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * @summary Get all CommsPreferences
 */
export const getAllCommsPreference = (
    
 signal?: AbortSignal
) => {
      
      
      return clientInstance<CommsPreference[]>(
      {url: `/commsPreference`, method: 'GET', signal
    },
      );
    }
  

export const getGetAllCommsPreferenceQueryKey = () => {
    return [`/commsPreference`] as const;
    }

    
export const getGetAllCommsPreferenceQueryOptions = <TData = Awaited<ReturnType<typeof getAllCommsPreference>>, TError = void>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getAllCommsPreference>>, TError, TData>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAllCommsPreferenceQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAllCommsPreference>>> = ({ signal }) => getAllCommsPreference(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAllCommsPreference>>, TError, TData> & { queryKey: QueryKey }
}

export type GetAllCommsPreferenceQueryResult = NonNullable<Awaited<ReturnType<typeof getAllCommsPreference>>>
export type GetAllCommsPreferenceQueryError = void

/**
 * @summary Get all CommsPreferences
 */
export const useGetAllCommsPreference = <TData = Awaited<ReturnType<typeof getAllCommsPreference>>, TError = void>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getAllCommsPreference>>, TError, TData>, }

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getGetAllCommsPreferenceQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Get all CommsPreferences
 */
export const getQueryCommsPreference = (
    params?: GetQueryCommsPreferenceParams,
 signal?: AbortSignal
) => {
      
      
      return clientInstance<CommsPreference[]>(
      {url: `/commsPreference/query`, method: 'GET',
        params, signal
    },
      );
    }
  

export const getGetQueryCommsPreferenceQueryKey = (params?: GetQueryCommsPreferenceParams,) => {
    return [`/commsPreference/query`, ...(params ? [params]: [])] as const;
    }

    
export const getGetQueryCommsPreferenceQueryOptions = <TData = Awaited<ReturnType<typeof getQueryCommsPreference>>, TError = void>(params?: GetQueryCommsPreferenceParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getQueryCommsPreference>>, TError, TData>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetQueryCommsPreferenceQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getQueryCommsPreference>>> = ({ signal }) => getQueryCommsPreference(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getQueryCommsPreference>>, TError, TData> & { queryKey: QueryKey }
}

export type GetQueryCommsPreferenceQueryResult = NonNullable<Awaited<ReturnType<typeof getQueryCommsPreference>>>
export type GetQueryCommsPreferenceQueryError = void

/**
 * @summary Get all CommsPreferences
 */
export const useGetQueryCommsPreference = <TData = Awaited<ReturnType<typeof getQueryCommsPreference>>, TError = void>(
 params?: GetQueryCommsPreferenceParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getQueryCommsPreference>>, TError, TData>, }

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getGetQueryCommsPreferenceQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Get count of CommsPreferences
 */
export const getCountCommsPreference = (
    params?: GetCountCommsPreferenceParams,
 signal?: AbortSignal
) => {
      
      
      return clientInstance<number>(
      {url: `/commsPreference/count`, method: 'GET',
        params, signal
    },
      );
    }
  

export const getGetCountCommsPreferenceQueryKey = (params?: GetCountCommsPreferenceParams,) => {
    return [`/commsPreference/count`, ...(params ? [params]: [])] as const;
    }

    
export const getGetCountCommsPreferenceQueryOptions = <TData = Awaited<ReturnType<typeof getCountCommsPreference>>, TError = void>(params?: GetCountCommsPreferenceParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getCountCommsPreference>>, TError, TData>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetCountCommsPreferenceQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getCountCommsPreference>>> = ({ signal }) => getCountCommsPreference(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getCountCommsPreference>>, TError, TData> & { queryKey: QueryKey }
}

export type GetCountCommsPreferenceQueryResult = NonNullable<Awaited<ReturnType<typeof getCountCommsPreference>>>
export type GetCountCommsPreferenceQueryError = void

/**
 * @summary Get count of CommsPreferences
 */
export const useGetCountCommsPreference = <TData = Awaited<ReturnType<typeof getCountCommsPreference>>, TError = void>(
 params?: GetCountCommsPreferenceParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getCountCommsPreference>>, TError, TData>, }

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getGetCountCommsPreferenceQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Get one CommsPreference
 */
export const getOneCommsPreference = (
    id: number,
 signal?: AbortSignal
) => {
      
      
      return clientInstance<CommsPreference>(
      {url: `/commsPreference/${id}`, method: 'GET', signal
    },
      );
    }
  

export const getGetOneCommsPreferenceQueryKey = (id: number,) => {
    return [`/commsPreference/${id}`] as const;
    }

    
export const getGetOneCommsPreferenceQueryOptions = <TData = Awaited<ReturnType<typeof getOneCommsPreference>>, TError = void>(id: number, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getOneCommsPreference>>, TError, TData>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetOneCommsPreferenceQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getOneCommsPreference>>> = ({ signal }) => getOneCommsPreference(id, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getOneCommsPreference>>, TError, TData> & { queryKey: QueryKey }
}

export type GetOneCommsPreferenceQueryResult = NonNullable<Awaited<ReturnType<typeof getOneCommsPreference>>>
export type GetOneCommsPreferenceQueryError = void

/**
 * @summary Get one CommsPreference
 */
export const useGetOneCommsPreference = <TData = Awaited<ReturnType<typeof getOneCommsPreference>>, TError = void>(
 id: number, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getOneCommsPreference>>, TError, TData>, }

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getGetOneCommsPreferenceQueryOptions(id,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Update one CommsPreference
 */
export const updateOneCommsPreference = (
    id: number,
    commsPreference: CommsPreference,
 ) => {
      
      
      return clientInstance<void>(
      {url: `/commsPreference/${id}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: commsPreference
    },
      );
    }
  


export const getUpdateOneCommsPreferenceMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateOneCommsPreference>>, TError,{id: number;data: CommsPreference}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof updateOneCommsPreference>>, TError,{id: number;data: CommsPreference}, TContext> => {
const {mutation: mutationOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateOneCommsPreference>>, {id: number;data: CommsPreference}> = (props) => {
          const {id,data} = props ?? {};

          return  updateOneCommsPreference(id,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateOneCommsPreferenceMutationResult = NonNullable<Awaited<ReturnType<typeof updateOneCommsPreference>>>
    export type UpdateOneCommsPreferenceMutationBody = CommsPreference
    export type UpdateOneCommsPreferenceMutationError = void

    /**
 * @summary Update one CommsPreference
 */
export const useUpdateOneCommsPreference = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateOneCommsPreference>>, TError,{id: number;data: CommsPreference}, TContext>, }
): UseMutationResult<
        Awaited<ReturnType<typeof updateOneCommsPreference>>,
        TError,
        {id: number;data: CommsPreference},
        TContext
      > => {

      const mutationOptions = getUpdateOneCommsPreferenceMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * @summary Delete one CommsPreference
 */
export const deleteOneCommsPreference = (
    id: number,
 ) => {
      
      
      return clientInstance<void>(
      {url: `/commsPreference/${id}`, method: 'DELETE'
    },
      );
    }
  


export const getDeleteOneCommsPreferenceMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteOneCommsPreference>>, TError,{id: number}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof deleteOneCommsPreference>>, TError,{id: number}, TContext> => {
const {mutation: mutationOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteOneCommsPreference>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  deleteOneCommsPreference(id,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteOneCommsPreferenceMutationResult = NonNullable<Awaited<ReturnType<typeof deleteOneCommsPreference>>>
    
    export type DeleteOneCommsPreferenceMutationError = void

    /**
 * @summary Delete one CommsPreference
 */
export const useDeleteOneCommsPreference = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteOneCommsPreference>>, TError,{id: number}, TContext>, }
): UseMutationResult<
        Awaited<ReturnType<typeof deleteOneCommsPreference>>,
        TError,
        {id: number},
        TContext
      > => {

      const mutationOptions = getDeleteOneCommsPreferenceMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * @summary Upload a file for CommsPreference
 */
export const uploadCommsPreference = (
    
 ) => {
      
      
      return clientInstance<void>(
      {url: `/commsPreference/upload`, method: 'POST'
    },
      );
    }
  


export const getUploadCommsPreferenceMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof uploadCommsPreference>>, TError,void, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof uploadCommsPreference>>, TError,void, TContext> => {
const {mutation: mutationOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof uploadCommsPreference>>, void> = () => {
          

          return  uploadCommsPreference()
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UploadCommsPreferenceMutationResult = NonNullable<Awaited<ReturnType<typeof uploadCommsPreference>>>
    
    export type UploadCommsPreferenceMutationError = void

    /**
 * @summary Upload a file for CommsPreference
 */
export const useUploadCommsPreference = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof uploadCommsPreference>>, TError,void, TContext>, }
): UseMutationResult<
        Awaited<ReturnType<typeof uploadCommsPreference>>,
        TError,
        void,
        TContext
      > => {

      const mutationOptions = getUploadCommsPreferenceMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * @summary Download file related to CommsPreference
 */
export const downloadCommsPreference = (
    filename: string,
 signal?: AbortSignal
) => {
      
      
      return clientInstance<void>(
      {url: `/commsPreference/download/${filename}`, method: 'GET', signal
    },
      );
    }
  

export const getDownloadCommsPreferenceQueryKey = (filename: string,) => {
    return [`/commsPreference/download/${filename}`] as const;
    }

    
export const getDownloadCommsPreferenceQueryOptions = <TData = Awaited<ReturnType<typeof downloadCommsPreference>>, TError = void>(filename: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof downloadCommsPreference>>, TError, TData>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getDownloadCommsPreferenceQueryKey(filename);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof downloadCommsPreference>>> = ({ signal }) => downloadCommsPreference(filename, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(filename), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof downloadCommsPreference>>, TError, TData> & { queryKey: QueryKey }
}

export type DownloadCommsPreferenceQueryResult = NonNullable<Awaited<ReturnType<typeof downloadCommsPreference>>>
export type DownloadCommsPreferenceQueryError = void

/**
 * @summary Download file related to CommsPreference
 */
export const useDownloadCommsPreference = <TData = Awaited<ReturnType<typeof downloadCommsPreference>>, TError = void>(
 filename: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof downloadCommsPreference>>, TError, TData>, }

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getDownloadCommsPreferenceQueryOptions(filename,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



