/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * I Watch Football API
 * The API Docs for I Watch Football
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import { clientInstance } from '../client-instance';
/**
 * @summary Create Competition
 */
export const createCompetition = (createCompetitionDTO) => {
    return clientInstance({ url: `/competition`, method: 'POST',
        headers: { 'Content-Type': 'application/json', },
        data: createCompetitionDTO
    });
};
export const getCreateCompetitionMutationOptions = (options) => {
    const { mutation: mutationOptions } = options !== null && options !== void 0 ? options : {};
    const mutationFn = (props) => {
        const { data } = props !== null && props !== void 0 ? props : {};
        return createCompetition(data);
    };
    return Object.assign({ mutationFn }, mutationOptions);
};
/**
* @summary Create Competition
*/
export const useCreateCompetition = (options) => {
    const mutationOptions = getCreateCompetitionMutationOptions(options);
    return useMutation(mutationOptions);
};
/**
* @summary Get all Competitions
*/
export const getAllCompetition = (signal) => {
    return clientInstance({ url: `/competition`, method: 'GET', signal
    });
};
export const getGetAllCompetitionQueryKey = () => {
    return [`/competition`];
};
export const getGetAllCompetitionQueryOptions = (options) => {
    var _a;
    const { query: queryOptions } = options !== null && options !== void 0 ? options : {};
    const queryKey = (_a = queryOptions === null || queryOptions === void 0 ? void 0 : queryOptions.queryKey) !== null && _a !== void 0 ? _a : getGetAllCompetitionQueryKey();
    const queryFn = ({ signal }) => getAllCompetition(signal);
    return Object.assign({ queryKey, queryFn }, queryOptions);
};
/**
 * @summary Get all Competitions
 */
export const useGetAllCompetition = (options) => {
    const queryOptions = getGetAllCompetitionQueryOptions(options);
    const query = useQuery(queryOptions);
    query.queryKey = queryOptions.queryKey;
    return query;
};
/**
 * @summary Get all Competitions
 */
export const getQueryCompetition = (params, signal) => {
    return clientInstance({ url: `/competition/query`, method: 'GET',
        params, signal
    });
};
export const getGetQueryCompetitionQueryKey = (params) => {
    return [`/competition/query`, ...(params ? [params] : [])];
};
export const getGetQueryCompetitionQueryOptions = (params, options) => {
    var _a;
    const { query: queryOptions } = options !== null && options !== void 0 ? options : {};
    const queryKey = (_a = queryOptions === null || queryOptions === void 0 ? void 0 : queryOptions.queryKey) !== null && _a !== void 0 ? _a : getGetQueryCompetitionQueryKey(params);
    const queryFn = ({ signal }) => getQueryCompetition(params, signal);
    return Object.assign({ queryKey, queryFn }, queryOptions);
};
/**
 * @summary Get all Competitions
 */
export const useGetQueryCompetition = (params, options) => {
    const queryOptions = getGetQueryCompetitionQueryOptions(params, options);
    const query = useQuery(queryOptions);
    query.queryKey = queryOptions.queryKey;
    return query;
};
/**
 * @summary Get count of Competitions
 */
export const getCountCompetition = (params, signal) => {
    return clientInstance({ url: `/competition/count`, method: 'GET',
        params, signal
    });
};
export const getGetCountCompetitionQueryKey = (params) => {
    return [`/competition/count`, ...(params ? [params] : [])];
};
export const getGetCountCompetitionQueryOptions = (params, options) => {
    var _a;
    const { query: queryOptions } = options !== null && options !== void 0 ? options : {};
    const queryKey = (_a = queryOptions === null || queryOptions === void 0 ? void 0 : queryOptions.queryKey) !== null && _a !== void 0 ? _a : getGetCountCompetitionQueryKey(params);
    const queryFn = ({ signal }) => getCountCompetition(params, signal);
    return Object.assign({ queryKey, queryFn }, queryOptions);
};
/**
 * @summary Get count of Competitions
 */
export const useGetCountCompetition = (params, options) => {
    const queryOptions = getGetCountCompetitionQueryOptions(params, options);
    const query = useQuery(queryOptions);
    query.queryKey = queryOptions.queryKey;
    return query;
};
/**
 * @summary Get one Competition
 */
export const getOneCompetition = (id, signal) => {
    return clientInstance({ url: `/competition/${id}`, method: 'GET', signal
    });
};
export const getGetOneCompetitionQueryKey = (id) => {
    return [`/competition/${id}`];
};
export const getGetOneCompetitionQueryOptions = (id, options) => {
    var _a;
    const { query: queryOptions } = options !== null && options !== void 0 ? options : {};
    const queryKey = (_a = queryOptions === null || queryOptions === void 0 ? void 0 : queryOptions.queryKey) !== null && _a !== void 0 ? _a : getGetOneCompetitionQueryKey(id);
    const queryFn = ({ signal }) => getOneCompetition(id, signal);
    return Object.assign({ queryKey, queryFn, enabled: !!(id) }, queryOptions);
};
/**
 * @summary Get one Competition
 */
export const useGetOneCompetition = (id, options) => {
    const queryOptions = getGetOneCompetitionQueryOptions(id, options);
    const query = useQuery(queryOptions);
    query.queryKey = queryOptions.queryKey;
    return query;
};
/**
 * @summary Update one Competition
 */
export const updateOneCompetition = (id, competition) => {
    return clientInstance({ url: `/competition/${id}`, method: 'PATCH',
        headers: { 'Content-Type': 'application/json', },
        data: competition
    });
};
export const getUpdateOneCompetitionMutationOptions = (options) => {
    const { mutation: mutationOptions } = options !== null && options !== void 0 ? options : {};
    const mutationFn = (props) => {
        const { id, data } = props !== null && props !== void 0 ? props : {};
        return updateOneCompetition(id, data);
    };
    return Object.assign({ mutationFn }, mutationOptions);
};
/**
* @summary Update one Competition
*/
export const useUpdateOneCompetition = (options) => {
    const mutationOptions = getUpdateOneCompetitionMutationOptions(options);
    return useMutation(mutationOptions);
};
/**
* @summary Delete one Competition
*/
export const deleteOneCompetition = (id) => {
    return clientInstance({ url: `/competition/${id}`, method: 'DELETE'
    });
};
export const getDeleteOneCompetitionMutationOptions = (options) => {
    const { mutation: mutationOptions } = options !== null && options !== void 0 ? options : {};
    const mutationFn = (props) => {
        const { id } = props !== null && props !== void 0 ? props : {};
        return deleteOneCompetition(id);
    };
    return Object.assign({ mutationFn }, mutationOptions);
};
/**
* @summary Delete one Competition
*/
export const useDeleteOneCompetition = (options) => {
    const mutationOptions = getDeleteOneCompetitionMutationOptions(options);
    return useMutation(mutationOptions);
};
/**
* @summary Upload a file for Competition
*/
export const uploadCompetition = () => {
    return clientInstance({ url: `/competition/upload`, method: 'POST'
    });
};
export const getUploadCompetitionMutationOptions = (options) => {
    const { mutation: mutationOptions } = options !== null && options !== void 0 ? options : {};
    const mutationFn = () => {
        return uploadCompetition();
    };
    return Object.assign({ mutationFn }, mutationOptions);
};
/**
* @summary Upload a file for Competition
*/
export const useUploadCompetition = (options) => {
    const mutationOptions = getUploadCompetitionMutationOptions(options);
    return useMutation(mutationOptions);
};
/**
* @summary Download file related to Competition
*/
export const downloadCompetition = (filename, signal) => {
    return clientInstance({ url: `/competition/download/${filename}`, method: 'GET', signal
    });
};
export const getDownloadCompetitionQueryKey = (filename) => {
    return [`/competition/download/${filename}`];
};
export const getDownloadCompetitionQueryOptions = (filename, options) => {
    var _a;
    const { query: queryOptions } = options !== null && options !== void 0 ? options : {};
    const queryKey = (_a = queryOptions === null || queryOptions === void 0 ? void 0 : queryOptions.queryKey) !== null && _a !== void 0 ? _a : getDownloadCompetitionQueryKey(filename);
    const queryFn = ({ signal }) => downloadCompetition(filename, signal);
    return Object.assign({ queryKey, queryFn, enabled: !!(filename) }, queryOptions);
};
/**
 * @summary Download file related to Competition
 */
export const useDownloadCompetition = (filename, options) => {
    const queryOptions = getDownloadCompetitionQueryOptions(filename, options);
    const query = useQuery(queryOptions);
    query.queryKey = queryOptions.queryKey;
    return query;
};
//# sourceMappingURL=competition.js.map