/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * I Watch Football API
 * The API Docs for I Watch Football
 * OpenAPI spec version: 1.0
 */
import {
  useMutation
} from '@tanstack/react-query'
import type {
  MutationFunction,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query'
import { clientInstance } from '../client-instance';




/**
 * @summary Seed teams data
 */
export const seedTeams = (
    
 ) => {
      
      
      return clientInstance<void>(
      {url: `/dataSeeding/teams`, method: 'POST'
    },
      );
    }
  


export const getSeedTeamsMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof seedTeams>>, TError,void, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof seedTeams>>, TError,void, TContext> => {
const {mutation: mutationOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof seedTeams>>, void> = () => {
          

          return  seedTeams()
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type SeedTeamsMutationResult = NonNullable<Awaited<ReturnType<typeof seedTeams>>>
    
    export type SeedTeamsMutationError = unknown

    /**
 * @summary Seed teams data
 */
export const useSeedTeams = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof seedTeams>>, TError,void, TContext>, }
): UseMutationResult<
        Awaited<ReturnType<typeof seedTeams>>,
        TError,
        void,
        TContext
      > => {

      const mutationOptions = getSeedTeamsMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * @summary Seed leagues data
 */
export const seedLeagues = (
    
 ) => {
      
      
      return clientInstance<void>(
      {url: `/dataSeeding/leagues`, method: 'POST'
    },
      );
    }
  


export const getSeedLeaguesMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof seedLeagues>>, TError,void, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof seedLeagues>>, TError,void, TContext> => {
const {mutation: mutationOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof seedLeagues>>, void> = () => {
          

          return  seedLeagues()
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type SeedLeaguesMutationResult = NonNullable<Awaited<ReturnType<typeof seedLeagues>>>
    
    export type SeedLeaguesMutationError = unknown

    /**
 * @summary Seed leagues data
 */
export const useSeedLeagues = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof seedLeagues>>, TError,void, TContext>, }
): UseMutationResult<
        Awaited<ReturnType<typeof seedLeagues>>,
        TError,
        void,
        TContext
      > => {

      const mutationOptions = getSeedLeaguesMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * @summary Seed fixtures data
 */
export const seedFixtures = (
    
 ) => {
      
      
      return clientInstance<void>(
      {url: `/dataSeeding/fixtures`, method: 'POST'
    },
      );
    }
  


export const getSeedFixturesMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof seedFixtures>>, TError,void, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof seedFixtures>>, TError,void, TContext> => {
const {mutation: mutationOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof seedFixtures>>, void> = () => {
          

          return  seedFixtures()
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type SeedFixturesMutationResult = NonNullable<Awaited<ReturnType<typeof seedFixtures>>>
    
    export type SeedFixturesMutationError = unknown

    /**
 * @summary Seed fixtures data
 */
export const useSeedFixtures = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof seedFixtures>>, TError,void, TContext>, }
): UseMutationResult<
        Awaited<ReturnType<typeof seedFixtures>>,
        TError,
        void,
        TContext
      > => {

      const mutationOptions = getSeedFixturesMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * @summary Seed standings data
 */
export const seedStandings = (
    
 ) => {
      
      
      return clientInstance<void>(
      {url: `/dataSeeding/standings`, method: 'POST'
    },
      );
    }
  


export const getSeedStandingsMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof seedStandings>>, TError,void, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof seedStandings>>, TError,void, TContext> => {
const {mutation: mutationOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof seedStandings>>, void> = () => {
          

          return  seedStandings()
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type SeedStandingsMutationResult = NonNullable<Awaited<ReturnType<typeof seedStandings>>>
    
    export type SeedStandingsMutationError = unknown

    /**
 * @summary Seed standings data
 */
export const useSeedStandings = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof seedStandings>>, TError,void, TContext>, }
): UseMutationResult<
        Awaited<ReturnType<typeof seedStandings>>,
        TError,
        void,
        TContext
      > => {

      const mutationOptions = getSeedStandingsMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * @summary Seed players data
 */
export const seedPlayers = (
    
 ) => {
      
      
      return clientInstance<void>(
      {url: `/dataSeeding/players`, method: 'POST'
    },
      );
    }
  


export const getSeedPlayersMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof seedPlayers>>, TError,void, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof seedPlayers>>, TError,void, TContext> => {
const {mutation: mutationOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof seedPlayers>>, void> = () => {
          

          return  seedPlayers()
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type SeedPlayersMutationResult = NonNullable<Awaited<ReturnType<typeof seedPlayers>>>
    
    export type SeedPlayersMutationError = unknown

    /**
 * @summary Seed players data
 */
export const useSeedPlayers = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof seedPlayers>>, TError,void, TContext>, }
): UseMutationResult<
        Awaited<ReturnType<typeof seedPlayers>>,
        TError,
        void,
        TContext
      > => {

      const mutationOptions = getSeedPlayersMutationOptions(options);

      return useMutation(mutationOptions);
    }
    