/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * I Watch Football API
 * The API Docs for I Watch Football
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query'
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query'
import type {
  DiscountCodeControllerCreateBody,
  DiscountCodeControllerValidateParams
} from './iWatchFootballAPI.schemas'
import { clientInstance } from '../client-instance';




/**
 * @summary Validate a discount code for current user & order total
 */
export const discountCodeControllerValidate = (
    code: string,
    params: DiscountCodeControllerValidateParams,
 signal?: AbortSignal
) => {
      
      
      return clientInstance<void>(
      {url: `/discount-code/validate/${code}`, method: 'GET',
        params, signal
    },
      );
    }
  

export const getDiscountCodeControllerValidateQueryKey = (code: string,
    params: DiscountCodeControllerValidateParams,) => {
    return [`/discount-code/validate/${code}`, ...(params ? [params]: [])] as const;
    }

    
export const getDiscountCodeControllerValidateQueryOptions = <TData = Awaited<ReturnType<typeof discountCodeControllerValidate>>, TError = void>(code: string,
    params: DiscountCodeControllerValidateParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof discountCodeControllerValidate>>, TError, TData>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getDiscountCodeControllerValidateQueryKey(code,params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof discountCodeControllerValidate>>> = ({ signal }) => discountCodeControllerValidate(code,params, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(code), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof discountCodeControllerValidate>>, TError, TData> & { queryKey: QueryKey }
}

export type DiscountCodeControllerValidateQueryResult = NonNullable<Awaited<ReturnType<typeof discountCodeControllerValidate>>>
export type DiscountCodeControllerValidateQueryError = void

/**
 * @summary Validate a discount code for current user & order total
 */
export const useDiscountCodeControllerValidate = <TData = Awaited<ReturnType<typeof discountCodeControllerValidate>>, TError = void>(
 code: string,
    params: DiscountCodeControllerValidateParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof discountCodeControllerValidate>>, TError, TData>, }

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getDiscountCodeControllerValidateQueryOptions(code,params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Admin: list all discount codes
 */
export const discountCodeControllerFindAll = (
    
 signal?: AbortSignal
) => {
      
      
      return clientInstance<void>(
      {url: `/discount-code`, method: 'GET', signal
    },
      );
    }
  

export const getDiscountCodeControllerFindAllQueryKey = () => {
    return [`/discount-code`] as const;
    }

    
export const getDiscountCodeControllerFindAllQueryOptions = <TData = Awaited<ReturnType<typeof discountCodeControllerFindAll>>, TError = void>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof discountCodeControllerFindAll>>, TError, TData>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getDiscountCodeControllerFindAllQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof discountCodeControllerFindAll>>> = ({ signal }) => discountCodeControllerFindAll(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof discountCodeControllerFindAll>>, TError, TData> & { queryKey: QueryKey }
}

export type DiscountCodeControllerFindAllQueryResult = NonNullable<Awaited<ReturnType<typeof discountCodeControllerFindAll>>>
export type DiscountCodeControllerFindAllQueryError = void

/**
 * @summary Admin: list all discount codes
 */
export const useDiscountCodeControllerFindAll = <TData = Awaited<ReturnType<typeof discountCodeControllerFindAll>>, TError = void>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof discountCodeControllerFindAll>>, TError, TData>, }

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getDiscountCodeControllerFindAllQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Admin: create a discount code
 */
export const discountCodeControllerCreate = (
    discountCodeControllerCreateBody: DiscountCodeControllerCreateBody,
 ) => {
      
      
      return clientInstance<void>(
      {url: `/discount-code`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: discountCodeControllerCreateBody
    },
      );
    }
  


export const getDiscountCodeControllerCreateMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof discountCodeControllerCreate>>, TError,{data: DiscountCodeControllerCreateBody}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof discountCodeControllerCreate>>, TError,{data: DiscountCodeControllerCreateBody}, TContext> => {
const {mutation: mutationOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof discountCodeControllerCreate>>, {data: DiscountCodeControllerCreateBody}> = (props) => {
          const {data} = props ?? {};

          return  discountCodeControllerCreate(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DiscountCodeControllerCreateMutationResult = NonNullable<Awaited<ReturnType<typeof discountCodeControllerCreate>>>
    export type DiscountCodeControllerCreateMutationBody = DiscountCodeControllerCreateBody
    export type DiscountCodeControllerCreateMutationError = void

    /**
 * @summary Admin: create a discount code
 */
export const useDiscountCodeControllerCreate = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof discountCodeControllerCreate>>, TError,{data: DiscountCodeControllerCreateBody}, TContext>, }
): UseMutationResult<
        Awaited<ReturnType<typeof discountCodeControllerCreate>>,
        TError,
        {data: DiscountCodeControllerCreateBody},
        TContext
      > => {

      const mutationOptions = getDiscountCodeControllerCreateMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * @summary Admin: toggle a discount code active/inactive
 */
export const discountCodeControllerToggle = (
    id: number,
 ) => {
      
      
      return clientInstance<void>(
      {url: `/discount-code/${id}/toggle`, method: 'PATCH'
    },
      );
    }
  


export const getDiscountCodeControllerToggleMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof discountCodeControllerToggle>>, TError,{id: number}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof discountCodeControllerToggle>>, TError,{id: number}, TContext> => {
const {mutation: mutationOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof discountCodeControllerToggle>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  discountCodeControllerToggle(id,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DiscountCodeControllerToggleMutationResult = NonNullable<Awaited<ReturnType<typeof discountCodeControllerToggle>>>
    
    export type DiscountCodeControllerToggleMutationError = void

    /**
 * @summary Admin: toggle a discount code active/inactive
 */
export const useDiscountCodeControllerToggle = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof discountCodeControllerToggle>>, TError,{id: number}, TContext>, }
): UseMutationResult<
        Awaited<ReturnType<typeof discountCodeControllerToggle>>,
        TError,
        {id: number},
        TContext
      > => {

      const mutationOptions = getDiscountCodeControllerToggleMutationOptions(options);

      return useMutation(mutationOptions);
    }
    