/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * I Watch Football API
 * The API Docs for I Watch Football
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import { clientInstance } from '../client-instance';
/**
 * @summary Create Fixture
 */
export const createFixture = (createFixtureDTO) => {
    return clientInstance({ url: `/fixture`, method: 'POST',
        headers: { 'Content-Type': 'application/json', },
        data: createFixtureDTO
    });
};
export const getCreateFixtureMutationOptions = (options) => {
    const { mutation: mutationOptions } = options !== null && options !== void 0 ? options : {};
    const mutationFn = (props) => {
        const { data } = props !== null && props !== void 0 ? props : {};
        return createFixture(data);
    };
    return Object.assign({ mutationFn }, mutationOptions);
};
/**
* @summary Create Fixture
*/
export const useCreateFixture = (options) => {
    const mutationOptions = getCreateFixtureMutationOptions(options);
    return useMutation(mutationOptions);
};
/**
* @summary Get all Fixtures
*/
export const getAllFixture = (signal) => {
    return clientInstance({ url: `/fixture`, method: 'GET', signal
    });
};
export const getGetAllFixtureQueryKey = () => {
    return [`/fixture`];
};
export const getGetAllFixtureQueryOptions = (options) => {
    var _a;
    const { query: queryOptions } = options !== null && options !== void 0 ? options : {};
    const queryKey = (_a = queryOptions === null || queryOptions === void 0 ? void 0 : queryOptions.queryKey) !== null && _a !== void 0 ? _a : getGetAllFixtureQueryKey();
    const queryFn = ({ signal }) => getAllFixture(signal);
    return Object.assign({ queryKey, queryFn }, queryOptions);
};
/**
 * @summary Get all Fixtures
 */
export const useGetAllFixture = (options) => {
    const queryOptions = getGetAllFixtureQueryOptions(options);
    const query = useQuery(queryOptions);
    query.queryKey = queryOptions.queryKey;
    return query;
};
/**
 * @summary Get all Fixtures
 */
export const getQueryFixture = (params, signal) => {
    return clientInstance({ url: `/fixture/query`, method: 'GET',
        params, signal
    });
};
export const getGetQueryFixtureQueryKey = (params) => {
    return [`/fixture/query`, ...(params ? [params] : [])];
};
export const getGetQueryFixtureQueryOptions = (params, options) => {
    var _a;
    const { query: queryOptions } = options !== null && options !== void 0 ? options : {};
    const queryKey = (_a = queryOptions === null || queryOptions === void 0 ? void 0 : queryOptions.queryKey) !== null && _a !== void 0 ? _a : getGetQueryFixtureQueryKey(params);
    const queryFn = ({ signal }) => getQueryFixture(params, signal);
    return Object.assign({ queryKey, queryFn }, queryOptions);
};
/**
 * @summary Get all Fixtures
 */
export const useGetQueryFixture = (params, options) => {
    const queryOptions = getGetQueryFixtureQueryOptions(params, options);
    const query = useQuery(queryOptions);
    query.queryKey = queryOptions.queryKey;
    return query;
};
/**
 * @summary Get count of Fixtures
 */
export const getCountFixture = (params, signal) => {
    return clientInstance({ url: `/fixture/count`, method: 'GET',
        params, signal
    });
};
export const getGetCountFixtureQueryKey = (params) => {
    return [`/fixture/count`, ...(params ? [params] : [])];
};
export const getGetCountFixtureQueryOptions = (params, options) => {
    var _a;
    const { query: queryOptions } = options !== null && options !== void 0 ? options : {};
    const queryKey = (_a = queryOptions === null || queryOptions === void 0 ? void 0 : queryOptions.queryKey) !== null && _a !== void 0 ? _a : getGetCountFixtureQueryKey(params);
    const queryFn = ({ signal }) => getCountFixture(params, signal);
    return Object.assign({ queryKey, queryFn }, queryOptions);
};
/**
 * @summary Get count of Fixtures
 */
export const useGetCountFixture = (params, options) => {
    const queryOptions = getGetCountFixtureQueryOptions(params, options);
    const query = useQuery(queryOptions);
    query.queryKey = queryOptions.queryKey;
    return query;
};
/**
 * @summary Get one Fixture
 */
export const getOneFixture = (id, signal) => {
    return clientInstance({ url: `/fixture/${id}`, method: 'GET', signal
    });
};
export const getGetOneFixtureQueryKey = (id) => {
    return [`/fixture/${id}`];
};
export const getGetOneFixtureQueryOptions = (id, options) => {
    var _a;
    const { query: queryOptions } = options !== null && options !== void 0 ? options : {};
    const queryKey = (_a = queryOptions === null || queryOptions === void 0 ? void 0 : queryOptions.queryKey) !== null && _a !== void 0 ? _a : getGetOneFixtureQueryKey(id);
    const queryFn = ({ signal }) => getOneFixture(id, signal);
    return Object.assign({ queryKey, queryFn, enabled: !!(id) }, queryOptions);
};
/**
 * @summary Get one Fixture
 */
export const useGetOneFixture = (id, options) => {
    const queryOptions = getGetOneFixtureQueryOptions(id, options);
    const query = useQuery(queryOptions);
    query.queryKey = queryOptions.queryKey;
    return query;
};
/**
 * @summary Update one Fixture
 */
export const updateOneFixture = (id, fixture) => {
    return clientInstance({ url: `/fixture/${id}`, method: 'PATCH',
        headers: { 'Content-Type': 'application/json', },
        data: fixture
    });
};
export const getUpdateOneFixtureMutationOptions = (options) => {
    const { mutation: mutationOptions } = options !== null && options !== void 0 ? options : {};
    const mutationFn = (props) => {
        const { id, data } = props !== null && props !== void 0 ? props : {};
        return updateOneFixture(id, data);
    };
    return Object.assign({ mutationFn }, mutationOptions);
};
/**
* @summary Update one Fixture
*/
export const useUpdateOneFixture = (options) => {
    const mutationOptions = getUpdateOneFixtureMutationOptions(options);
    return useMutation(mutationOptions);
};
/**
* @summary Delete one Fixture
*/
export const deleteOneFixture = (id) => {
    return clientInstance({ url: `/fixture/${id}`, method: 'DELETE'
    });
};
export const getDeleteOneFixtureMutationOptions = (options) => {
    const { mutation: mutationOptions } = options !== null && options !== void 0 ? options : {};
    const mutationFn = (props) => {
        const { id } = props !== null && props !== void 0 ? props : {};
        return deleteOneFixture(id);
    };
    return Object.assign({ mutationFn }, mutationOptions);
};
/**
* @summary Delete one Fixture
*/
export const useDeleteOneFixture = (options) => {
    const mutationOptions = getDeleteOneFixtureMutationOptions(options);
    return useMutation(mutationOptions);
};
/**
* @summary Upload a file for Fixture
*/
export const uploadFixture = () => {
    return clientInstance({ url: `/fixture/upload`, method: 'POST'
    });
};
export const getUploadFixtureMutationOptions = (options) => {
    const { mutation: mutationOptions } = options !== null && options !== void 0 ? options : {};
    const mutationFn = () => {
        return uploadFixture();
    };
    return Object.assign({ mutationFn }, mutationOptions);
};
/**
* @summary Upload a file for Fixture
*/
export const useUploadFixture = (options) => {
    const mutationOptions = getUploadFixtureMutationOptions(options);
    return useMutation(mutationOptions);
};
/**
* @summary Download file related to Fixture
*/
export const downloadFixture = (filename, signal) => {
    return clientInstance({ url: `/fixture/download/${filename}`, method: 'GET', signal
    });
};
export const getDownloadFixtureQueryKey = (filename) => {
    return [`/fixture/download/${filename}`];
};
export const getDownloadFixtureQueryOptions = (filename, options) => {
    var _a;
    const { query: queryOptions } = options !== null && options !== void 0 ? options : {};
    const queryKey = (_a = queryOptions === null || queryOptions === void 0 ? void 0 : queryOptions.queryKey) !== null && _a !== void 0 ? _a : getDownloadFixtureQueryKey(filename);
    const queryFn = ({ signal }) => downloadFixture(filename, signal);
    return Object.assign({ queryKey, queryFn, enabled: !!(filename) }, queryOptions);
};
/**
 * @summary Download file related to Fixture
 */
export const useDownloadFixture = (filename, options) => {
    const queryOptions = getDownloadFixtureQueryOptions(filename, options);
    const query = useQuery(queryOptions);
    query.queryKey = queryOptions.queryKey;
    return query;
};
/**
 * @summary Goals, cards and substitutions for a fixture (public)
 */
export const fixtureTimelineControllerGetFixtureEvents = (fixtureId, signal) => {
    return clientInstance({ url: `/fixture/${fixtureId}/events`, method: 'GET', signal
    });
};
export const getFixtureTimelineControllerGetFixtureEventsQueryKey = (fixtureId) => {
    return [`/fixture/${fixtureId}/events`];
};
export const getFixtureTimelineControllerGetFixtureEventsQueryOptions = (fixtureId, options) => {
    var _a;
    const { query: queryOptions } = options !== null && options !== void 0 ? options : {};
    const queryKey = (_a = queryOptions === null || queryOptions === void 0 ? void 0 : queryOptions.queryKey) !== null && _a !== void 0 ? _a : getFixtureTimelineControllerGetFixtureEventsQueryKey(fixtureId);
    const queryFn = ({ signal }) => fixtureTimelineControllerGetFixtureEvents(fixtureId, signal);
    return Object.assign({ queryKey, queryFn, enabled: !!(fixtureId) }, queryOptions);
};
/**
 * @summary Goals, cards and substitutions for a fixture (public)
 */
export const useFixtureTimelineControllerGetFixtureEvents = (fixtureId, options) => {
    const queryOptions = getFixtureTimelineControllerGetFixtureEventsQueryOptions(fixtureId, options);
    const query = useQuery(queryOptions);
    query.queryKey = queryOptions.queryKey;
    return query;
};
//# sourceMappingURL=fixture.js.map