/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * I Watch Football API
 * The API Docs for I Watch Football
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query'
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query'
import type {
  CreateFixtureRefereeDTO,
  FixtureReferee,
  GetCountFixtureRefereeParams,
  GetQueryFixtureRefereeParams
} from './iWatchFootballAPI.schemas'
import { clientInstance } from '../client-instance';




/**
 * @summary Create FixtureReferee
 */
export const createFixtureReferee = (
    createFixtureRefereeDTO: CreateFixtureRefereeDTO,
 ) => {
      
      
      return clientInstance<FixtureReferee>(
      {url: `/fixtureReferee`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createFixtureRefereeDTO
    },
      );
    }
  


export const getCreateFixtureRefereeMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createFixtureReferee>>, TError,{data: CreateFixtureRefereeDTO}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof createFixtureReferee>>, TError,{data: CreateFixtureRefereeDTO}, TContext> => {
const {mutation: mutationOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createFixtureReferee>>, {data: CreateFixtureRefereeDTO}> = (props) => {
          const {data} = props ?? {};

          return  createFixtureReferee(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateFixtureRefereeMutationResult = NonNullable<Awaited<ReturnType<typeof createFixtureReferee>>>
    export type CreateFixtureRefereeMutationBody = CreateFixtureRefereeDTO
    export type CreateFixtureRefereeMutationError = void

    /**
 * @summary Create FixtureReferee
 */
export const useCreateFixtureReferee = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createFixtureReferee>>, TError,{data: CreateFixtureRefereeDTO}, TContext>, }
): UseMutationResult<
        Awaited<ReturnType<typeof createFixtureReferee>>,
        TError,
        {data: CreateFixtureRefereeDTO},
        TContext
      > => {

      const mutationOptions = getCreateFixtureRefereeMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * @summary Get all FixtureReferees
 */
export const getAllFixtureReferee = (
    
 signal?: AbortSignal
) => {
      
      
      return clientInstance<FixtureReferee[]>(
      {url: `/fixtureReferee`, method: 'GET', signal
    },
      );
    }
  

export const getGetAllFixtureRefereeQueryKey = () => {
    return [`/fixtureReferee`] as const;
    }

    
export const getGetAllFixtureRefereeQueryOptions = <TData = Awaited<ReturnType<typeof getAllFixtureReferee>>, TError = void>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getAllFixtureReferee>>, TError, TData>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAllFixtureRefereeQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAllFixtureReferee>>> = ({ signal }) => getAllFixtureReferee(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAllFixtureReferee>>, TError, TData> & { queryKey: QueryKey }
}

export type GetAllFixtureRefereeQueryResult = NonNullable<Awaited<ReturnType<typeof getAllFixtureReferee>>>
export type GetAllFixtureRefereeQueryError = void

/**
 * @summary Get all FixtureReferees
 */
export const useGetAllFixtureReferee = <TData = Awaited<ReturnType<typeof getAllFixtureReferee>>, TError = void>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getAllFixtureReferee>>, TError, TData>, }

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getGetAllFixtureRefereeQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Get all FixtureReferees
 */
export const getQueryFixtureReferee = (
    params?: GetQueryFixtureRefereeParams,
 signal?: AbortSignal
) => {
      
      
      return clientInstance<FixtureReferee[]>(
      {url: `/fixtureReferee/query`, method: 'GET',
        params, signal
    },
      );
    }
  

export const getGetQueryFixtureRefereeQueryKey = (params?: GetQueryFixtureRefereeParams,) => {
    return [`/fixtureReferee/query`, ...(params ? [params]: [])] as const;
    }

    
export const getGetQueryFixtureRefereeQueryOptions = <TData = Awaited<ReturnType<typeof getQueryFixtureReferee>>, TError = void>(params?: GetQueryFixtureRefereeParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getQueryFixtureReferee>>, TError, TData>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetQueryFixtureRefereeQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getQueryFixtureReferee>>> = ({ signal }) => getQueryFixtureReferee(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getQueryFixtureReferee>>, TError, TData> & { queryKey: QueryKey }
}

export type GetQueryFixtureRefereeQueryResult = NonNullable<Awaited<ReturnType<typeof getQueryFixtureReferee>>>
export type GetQueryFixtureRefereeQueryError = void

/**
 * @summary Get all FixtureReferees
 */
export const useGetQueryFixtureReferee = <TData = Awaited<ReturnType<typeof getQueryFixtureReferee>>, TError = void>(
 params?: GetQueryFixtureRefereeParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getQueryFixtureReferee>>, TError, TData>, }

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getGetQueryFixtureRefereeQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Get count of FixtureReferees
 */
export const getCountFixtureReferee = (
    params?: GetCountFixtureRefereeParams,
 signal?: AbortSignal
) => {
      
      
      return clientInstance<number>(
      {url: `/fixtureReferee/count`, method: 'GET',
        params, signal
    },
      );
    }
  

export const getGetCountFixtureRefereeQueryKey = (params?: GetCountFixtureRefereeParams,) => {
    return [`/fixtureReferee/count`, ...(params ? [params]: [])] as const;
    }

    
export const getGetCountFixtureRefereeQueryOptions = <TData = Awaited<ReturnType<typeof getCountFixtureReferee>>, TError = void>(params?: GetCountFixtureRefereeParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getCountFixtureReferee>>, TError, TData>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetCountFixtureRefereeQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getCountFixtureReferee>>> = ({ signal }) => getCountFixtureReferee(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getCountFixtureReferee>>, TError, TData> & { queryKey: QueryKey }
}

export type GetCountFixtureRefereeQueryResult = NonNullable<Awaited<ReturnType<typeof getCountFixtureReferee>>>
export type GetCountFixtureRefereeQueryError = void

/**
 * @summary Get count of FixtureReferees
 */
export const useGetCountFixtureReferee = <TData = Awaited<ReturnType<typeof getCountFixtureReferee>>, TError = void>(
 params?: GetCountFixtureRefereeParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getCountFixtureReferee>>, TError, TData>, }

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getGetCountFixtureRefereeQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Get one FixtureReferee
 */
export const getOneFixtureReferee = (
    id: number,
 signal?: AbortSignal
) => {
      
      
      return clientInstance<FixtureReferee>(
      {url: `/fixtureReferee/${id}`, method: 'GET', signal
    },
      );
    }
  

export const getGetOneFixtureRefereeQueryKey = (id: number,) => {
    return [`/fixtureReferee/${id}`] as const;
    }

    
export const getGetOneFixtureRefereeQueryOptions = <TData = Awaited<ReturnType<typeof getOneFixtureReferee>>, TError = void>(id: number, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getOneFixtureReferee>>, TError, TData>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetOneFixtureRefereeQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getOneFixtureReferee>>> = ({ signal }) => getOneFixtureReferee(id, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getOneFixtureReferee>>, TError, TData> & { queryKey: QueryKey }
}

export type GetOneFixtureRefereeQueryResult = NonNullable<Awaited<ReturnType<typeof getOneFixtureReferee>>>
export type GetOneFixtureRefereeQueryError = void

/**
 * @summary Get one FixtureReferee
 */
export const useGetOneFixtureReferee = <TData = Awaited<ReturnType<typeof getOneFixtureReferee>>, TError = void>(
 id: number, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getOneFixtureReferee>>, TError, TData>, }

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getGetOneFixtureRefereeQueryOptions(id,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Update one FixtureReferee
 */
export const updateOneFixtureReferee = (
    id: number,
    fixtureReferee: FixtureReferee,
 ) => {
      
      
      return clientInstance<void>(
      {url: `/fixtureReferee/${id}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: fixtureReferee
    },
      );
    }
  


export const getUpdateOneFixtureRefereeMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateOneFixtureReferee>>, TError,{id: number;data: FixtureReferee}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof updateOneFixtureReferee>>, TError,{id: number;data: FixtureReferee}, TContext> => {
const {mutation: mutationOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateOneFixtureReferee>>, {id: number;data: FixtureReferee}> = (props) => {
          const {id,data} = props ?? {};

          return  updateOneFixtureReferee(id,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateOneFixtureRefereeMutationResult = NonNullable<Awaited<ReturnType<typeof updateOneFixtureReferee>>>
    export type UpdateOneFixtureRefereeMutationBody = FixtureReferee
    export type UpdateOneFixtureRefereeMutationError = void

    /**
 * @summary Update one FixtureReferee
 */
export const useUpdateOneFixtureReferee = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateOneFixtureReferee>>, TError,{id: number;data: FixtureReferee}, TContext>, }
): UseMutationResult<
        Awaited<ReturnType<typeof updateOneFixtureReferee>>,
        TError,
        {id: number;data: FixtureReferee},
        TContext
      > => {

      const mutationOptions = getUpdateOneFixtureRefereeMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * @summary Delete one FixtureReferee
 */
export const deleteOneFixtureReferee = (
    id: number,
 ) => {
      
      
      return clientInstance<void>(
      {url: `/fixtureReferee/${id}`, method: 'DELETE'
    },
      );
    }
  


export const getDeleteOneFixtureRefereeMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteOneFixtureReferee>>, TError,{id: number}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof deleteOneFixtureReferee>>, TError,{id: number}, TContext> => {
const {mutation: mutationOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteOneFixtureReferee>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  deleteOneFixtureReferee(id,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteOneFixtureRefereeMutationResult = NonNullable<Awaited<ReturnType<typeof deleteOneFixtureReferee>>>
    
    export type DeleteOneFixtureRefereeMutationError = void

    /**
 * @summary Delete one FixtureReferee
 */
export const useDeleteOneFixtureReferee = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteOneFixtureReferee>>, TError,{id: number}, TContext>, }
): UseMutationResult<
        Awaited<ReturnType<typeof deleteOneFixtureReferee>>,
        TError,
        {id: number},
        TContext
      > => {

      const mutationOptions = getDeleteOneFixtureRefereeMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * @summary Upload a file for FixtureReferee
 */
export const uploadFixtureReferee = (
    
 ) => {
      
      
      return clientInstance<void>(
      {url: `/fixtureReferee/upload`, method: 'POST'
    },
      );
    }
  


export const getUploadFixtureRefereeMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof uploadFixtureReferee>>, TError,void, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof uploadFixtureReferee>>, TError,void, TContext> => {
const {mutation: mutationOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof uploadFixtureReferee>>, void> = () => {
          

          return  uploadFixtureReferee()
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UploadFixtureRefereeMutationResult = NonNullable<Awaited<ReturnType<typeof uploadFixtureReferee>>>
    
    export type UploadFixtureRefereeMutationError = void

    /**
 * @summary Upload a file for FixtureReferee
 */
export const useUploadFixtureReferee = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof uploadFixtureReferee>>, TError,void, TContext>, }
): UseMutationResult<
        Awaited<ReturnType<typeof uploadFixtureReferee>>,
        TError,
        void,
        TContext
      > => {

      const mutationOptions = getUploadFixtureRefereeMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * @summary Download file related to FixtureReferee
 */
export const downloadFixtureReferee = (
    filename: string,
 signal?: AbortSignal
) => {
      
      
      return clientInstance<void>(
      {url: `/fixtureReferee/download/${filename}`, method: 'GET', signal
    },
      );
    }
  

export const getDownloadFixtureRefereeQueryKey = (filename: string,) => {
    return [`/fixtureReferee/download/${filename}`] as const;
    }

    
export const getDownloadFixtureRefereeQueryOptions = <TData = Awaited<ReturnType<typeof downloadFixtureReferee>>, TError = void>(filename: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof downloadFixtureReferee>>, TError, TData>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getDownloadFixtureRefereeQueryKey(filename);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof downloadFixtureReferee>>> = ({ signal }) => downloadFixtureReferee(filename, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(filename), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof downloadFixtureReferee>>, TError, TData> & { queryKey: QueryKey }
}

export type DownloadFixtureRefereeQueryResult = NonNullable<Awaited<ReturnType<typeof downloadFixtureReferee>>>
export type DownloadFixtureRefereeQueryError = void

/**
 * @summary Download file related to FixtureReferee
 */
export const useDownloadFixtureReferee = <TData = Awaited<ReturnType<typeof downloadFixtureReferee>>, TError = void>(
 filename: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof downloadFixtureReferee>>, TError, TData>, }

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getDownloadFixtureRefereeQueryOptions(filename,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



