/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * I Watch Football API
 * The API Docs for I Watch Football
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query'
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query'
import type {
  CreateGoalDTO,
  GetCountGoalParams,
  GetQueryGoalParams,
  Goal
} from './iWatchFootballAPI.schemas'
import { clientInstance } from '../client-instance';




/**
 * @summary Create Goal
 */
export const createGoal = (
    createGoalDTO: CreateGoalDTO,
 ) => {
      
      
      return clientInstance<Goal>(
      {url: `/goal`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createGoalDTO
    },
      );
    }
  


export const getCreateGoalMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createGoal>>, TError,{data: CreateGoalDTO}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof createGoal>>, TError,{data: CreateGoalDTO}, TContext> => {
const {mutation: mutationOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createGoal>>, {data: CreateGoalDTO}> = (props) => {
          const {data} = props ?? {};

          return  createGoal(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateGoalMutationResult = NonNullable<Awaited<ReturnType<typeof createGoal>>>
    export type CreateGoalMutationBody = CreateGoalDTO
    export type CreateGoalMutationError = void

    /**
 * @summary Create Goal
 */
export const useCreateGoal = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createGoal>>, TError,{data: CreateGoalDTO}, TContext>, }
): UseMutationResult<
        Awaited<ReturnType<typeof createGoal>>,
        TError,
        {data: CreateGoalDTO},
        TContext
      > => {

      const mutationOptions = getCreateGoalMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * @summary Get all Goals
 */
export const getAllGoal = (
    
 signal?: AbortSignal
) => {
      
      
      return clientInstance<Goal[]>(
      {url: `/goal`, method: 'GET', signal
    },
      );
    }
  

export const getGetAllGoalQueryKey = () => {
    return [`/goal`] as const;
    }

    
export const getGetAllGoalQueryOptions = <TData = Awaited<ReturnType<typeof getAllGoal>>, TError = void>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getAllGoal>>, TError, TData>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAllGoalQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAllGoal>>> = ({ signal }) => getAllGoal(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAllGoal>>, TError, TData> & { queryKey: QueryKey }
}

export type GetAllGoalQueryResult = NonNullable<Awaited<ReturnType<typeof getAllGoal>>>
export type GetAllGoalQueryError = void

/**
 * @summary Get all Goals
 */
export const useGetAllGoal = <TData = Awaited<ReturnType<typeof getAllGoal>>, TError = void>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getAllGoal>>, TError, TData>, }

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getGetAllGoalQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Get all Goals
 */
export const getQueryGoal = (
    params?: GetQueryGoalParams,
 signal?: AbortSignal
) => {
      
      
      return clientInstance<Goal[]>(
      {url: `/goal/query`, method: 'GET',
        params, signal
    },
      );
    }
  

export const getGetQueryGoalQueryKey = (params?: GetQueryGoalParams,) => {
    return [`/goal/query`, ...(params ? [params]: [])] as const;
    }

    
export const getGetQueryGoalQueryOptions = <TData = Awaited<ReturnType<typeof getQueryGoal>>, TError = void>(params?: GetQueryGoalParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getQueryGoal>>, TError, TData>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetQueryGoalQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getQueryGoal>>> = ({ signal }) => getQueryGoal(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getQueryGoal>>, TError, TData> & { queryKey: QueryKey }
}

export type GetQueryGoalQueryResult = NonNullable<Awaited<ReturnType<typeof getQueryGoal>>>
export type GetQueryGoalQueryError = void

/**
 * @summary Get all Goals
 */
export const useGetQueryGoal = <TData = Awaited<ReturnType<typeof getQueryGoal>>, TError = void>(
 params?: GetQueryGoalParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getQueryGoal>>, TError, TData>, }

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getGetQueryGoalQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Get count of Goals
 */
export const getCountGoal = (
    params?: GetCountGoalParams,
 signal?: AbortSignal
) => {
      
      
      return clientInstance<number>(
      {url: `/goal/count`, method: 'GET',
        params, signal
    },
      );
    }
  

export const getGetCountGoalQueryKey = (params?: GetCountGoalParams,) => {
    return [`/goal/count`, ...(params ? [params]: [])] as const;
    }

    
export const getGetCountGoalQueryOptions = <TData = Awaited<ReturnType<typeof getCountGoal>>, TError = void>(params?: GetCountGoalParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getCountGoal>>, TError, TData>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetCountGoalQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getCountGoal>>> = ({ signal }) => getCountGoal(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getCountGoal>>, TError, TData> & { queryKey: QueryKey }
}

export type GetCountGoalQueryResult = NonNullable<Awaited<ReturnType<typeof getCountGoal>>>
export type GetCountGoalQueryError = void

/**
 * @summary Get count of Goals
 */
export const useGetCountGoal = <TData = Awaited<ReturnType<typeof getCountGoal>>, TError = void>(
 params?: GetCountGoalParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getCountGoal>>, TError, TData>, }

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getGetCountGoalQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Get one Goal
 */
export const getOneGoal = (
    id: number,
 signal?: AbortSignal
) => {
      
      
      return clientInstance<Goal>(
      {url: `/goal/${id}`, method: 'GET', signal
    },
      );
    }
  

export const getGetOneGoalQueryKey = (id: number,) => {
    return [`/goal/${id}`] as const;
    }

    
export const getGetOneGoalQueryOptions = <TData = Awaited<ReturnType<typeof getOneGoal>>, TError = void>(id: number, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getOneGoal>>, TError, TData>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetOneGoalQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getOneGoal>>> = ({ signal }) => getOneGoal(id, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getOneGoal>>, TError, TData> & { queryKey: QueryKey }
}

export type GetOneGoalQueryResult = NonNullable<Awaited<ReturnType<typeof getOneGoal>>>
export type GetOneGoalQueryError = void

/**
 * @summary Get one Goal
 */
export const useGetOneGoal = <TData = Awaited<ReturnType<typeof getOneGoal>>, TError = void>(
 id: number, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getOneGoal>>, TError, TData>, }

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getGetOneGoalQueryOptions(id,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Update one Goal
 */
export const updateOneGoal = (
    id: number,
    goal: Goal,
 ) => {
      
      
      return clientInstance<void>(
      {url: `/goal/${id}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: goal
    },
      );
    }
  


export const getUpdateOneGoalMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateOneGoal>>, TError,{id: number;data: Goal}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof updateOneGoal>>, TError,{id: number;data: Goal}, TContext> => {
const {mutation: mutationOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateOneGoal>>, {id: number;data: Goal}> = (props) => {
          const {id,data} = props ?? {};

          return  updateOneGoal(id,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateOneGoalMutationResult = NonNullable<Awaited<ReturnType<typeof updateOneGoal>>>
    export type UpdateOneGoalMutationBody = Goal
    export type UpdateOneGoalMutationError = void

    /**
 * @summary Update one Goal
 */
export const useUpdateOneGoal = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateOneGoal>>, TError,{id: number;data: Goal}, TContext>, }
): UseMutationResult<
        Awaited<ReturnType<typeof updateOneGoal>>,
        TError,
        {id: number;data: Goal},
        TContext
      > => {

      const mutationOptions = getUpdateOneGoalMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * @summary Delete one Goal
 */
export const deleteOneGoal = (
    id: number,
 ) => {
      
      
      return clientInstance<void>(
      {url: `/goal/${id}`, method: 'DELETE'
    },
      );
    }
  


export const getDeleteOneGoalMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteOneGoal>>, TError,{id: number}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof deleteOneGoal>>, TError,{id: number}, TContext> => {
const {mutation: mutationOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteOneGoal>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  deleteOneGoal(id,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteOneGoalMutationResult = NonNullable<Awaited<ReturnType<typeof deleteOneGoal>>>
    
    export type DeleteOneGoalMutationError = void

    /**
 * @summary Delete one Goal
 */
export const useDeleteOneGoal = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteOneGoal>>, TError,{id: number}, TContext>, }
): UseMutationResult<
        Awaited<ReturnType<typeof deleteOneGoal>>,
        TError,
        {id: number},
        TContext
      > => {

      const mutationOptions = getDeleteOneGoalMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * @summary Upload a file for Goal
 */
export const uploadGoal = (
    
 ) => {
      
      
      return clientInstance<void>(
      {url: `/goal/upload`, method: 'POST'
    },
      );
    }
  


export const getUploadGoalMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof uploadGoal>>, TError,void, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof uploadGoal>>, TError,void, TContext> => {
const {mutation: mutationOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof uploadGoal>>, void> = () => {
          

          return  uploadGoal()
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UploadGoalMutationResult = NonNullable<Awaited<ReturnType<typeof uploadGoal>>>
    
    export type UploadGoalMutationError = void

    /**
 * @summary Upload a file for Goal
 */
export const useUploadGoal = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof uploadGoal>>, TError,void, TContext>, }
): UseMutationResult<
        Awaited<ReturnType<typeof uploadGoal>>,
        TError,
        void,
        TContext
      > => {

      const mutationOptions = getUploadGoalMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * @summary Download file related to Goal
 */
export const downloadGoal = (
    filename: string,
 signal?: AbortSignal
) => {
      
      
      return clientInstance<void>(
      {url: `/goal/download/${filename}`, method: 'GET', signal
    },
      );
    }
  

export const getDownloadGoalQueryKey = (filename: string,) => {
    return [`/goal/download/${filename}`] as const;
    }

    
export const getDownloadGoalQueryOptions = <TData = Awaited<ReturnType<typeof downloadGoal>>, TError = void>(filename: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof downloadGoal>>, TError, TData>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getDownloadGoalQueryKey(filename);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof downloadGoal>>> = ({ signal }) => downloadGoal(filename, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(filename), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof downloadGoal>>, TError, TData> & { queryKey: QueryKey }
}

export type DownloadGoalQueryResult = NonNullable<Awaited<ReturnType<typeof downloadGoal>>>
export type DownloadGoalQueryError = void

/**
 * @summary Download file related to Goal
 */
export const useDownloadGoal = <TData = Awaited<ReturnType<typeof downloadGoal>>, TError = void>(
 filename: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof downloadGoal>>, TError, TData>, }

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getDownloadGoalQueryOptions(filename,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



