/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * I Watch Football API
 * The API Docs for I Watch Football
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query'
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query'
import type {
  StreamFixtureInsightDto
} from './iWatchFootballAPI.schemas'
import { clientInstance } from '../client-instance';




/**
 * @summary List configured LLM integrations (staff)
 */
export const insightsControllerListLlm = (
    
 signal?: AbortSignal
) => {
      
      
      return clientInstance<void>(
      {url: `/insights/integrations/llm`, method: 'GET', signal
    },
      );
    }
  

export const getInsightsControllerListLlmQueryKey = () => {
    return [`/insights/integrations/llm`] as const;
    }

    
export const getInsightsControllerListLlmQueryOptions = <TData = Awaited<ReturnType<typeof insightsControllerListLlm>>, TError = unknown>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof insightsControllerListLlm>>, TError, TData>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getInsightsControllerListLlmQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof insightsControllerListLlm>>> = ({ signal }) => insightsControllerListLlm(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof insightsControllerListLlm>>, TError, TData> & { queryKey: QueryKey }
}

export type InsightsControllerListLlmQueryResult = NonNullable<Awaited<ReturnType<typeof insightsControllerListLlm>>>
export type InsightsControllerListLlmQueryError = unknown

/**
 * @summary List configured LLM integrations (staff)
 */
export const useInsightsControllerListLlm = <TData = Awaited<ReturnType<typeof insightsControllerListLlm>>, TError = unknown>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof insightsControllerListLlm>>, TError, TData>, }

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getInsightsControllerListLlmQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Stream AI match insight as SSE
 */
export const insightsControllerStreamFixtureInsight = (
    fixtureId: number,
    streamFixtureInsightDto?: StreamFixtureInsightDto,
 ) => {
      
      
      return clientInstance<void>(
      {url: `/insights/fixtures/${fixtureId}/stream`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: streamFixtureInsightDto
    },
      );
    }
  


export const getInsightsControllerStreamFixtureInsightMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof insightsControllerStreamFixtureInsight>>, TError,{fixtureId: number;data: StreamFixtureInsightDto}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof insightsControllerStreamFixtureInsight>>, TError,{fixtureId: number;data: StreamFixtureInsightDto}, TContext> => {
const {mutation: mutationOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof insightsControllerStreamFixtureInsight>>, {fixtureId: number;data: StreamFixtureInsightDto}> = (props) => {
          const {fixtureId,data} = props ?? {};

          return  insightsControllerStreamFixtureInsight(fixtureId,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type InsightsControllerStreamFixtureInsightMutationResult = NonNullable<Awaited<ReturnType<typeof insightsControllerStreamFixtureInsight>>>
    export type InsightsControllerStreamFixtureInsightMutationBody = StreamFixtureInsightDto
    export type InsightsControllerStreamFixtureInsightMutationError = unknown

    /**
 * @summary Stream AI match insight as SSE
 */
export const useInsightsControllerStreamFixtureInsight = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof insightsControllerStreamFixtureInsight>>, TError,{fixtureId: number;data: StreamFixtureInsightDto}, TContext>, }
): UseMutationResult<
        Awaited<ReturnType<typeof insightsControllerStreamFixtureInsight>>,
        TError,
        {fixtureId: number;data: StreamFixtureInsightDto},
        TContext
      > => {

      const mutationOptions = getInsightsControllerStreamFixtureInsightMutationOptions(options);

      return useMutation(mutationOptions);
    }
    