/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * I Watch Football API
 * The API Docs for I Watch Football
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query'
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query'
import type {
  CreateLogDTO,
  GetCountLogParams,
  GetQueryLogParams,
  Log,
  LogControllerGetMyHistory200
} from './iWatchFootballAPI.schemas'
import { clientInstance } from '../client-instance';




/**
 * @summary Get match log history with freemium gating (verified limit for free users)
 */
export const logControllerGetMyHistory = (
    
 signal?: AbortSignal
) => {
      
      
      return clientInstance<LogControllerGetMyHistory200>(
      {url: `/log/my-history`, method: 'GET', signal
    },
      );
    }
  

export const getLogControllerGetMyHistoryQueryKey = () => {
    return [`/log/my-history`] as const;
    }

    
export const getLogControllerGetMyHistoryQueryOptions = <TData = Awaited<ReturnType<typeof logControllerGetMyHistory>>, TError = void>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof logControllerGetMyHistory>>, TError, TData>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getLogControllerGetMyHistoryQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof logControllerGetMyHistory>>> = ({ signal }) => logControllerGetMyHistory(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof logControllerGetMyHistory>>, TError, TData> & { queryKey: QueryKey }
}

export type LogControllerGetMyHistoryQueryResult = NonNullable<Awaited<ReturnType<typeof logControllerGetMyHistory>>>
export type LogControllerGetMyHistoryQueryError = void

/**
 * @summary Get match log history with freemium gating (verified limit for free users)
 */
export const useLogControllerGetMyHistory = <TData = Awaited<ReturnType<typeof logControllerGetMyHistory>>, TError = void>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof logControllerGetMyHistory>>, TError, TData>, }

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getLogControllerGetMyHistoryQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Create Log
 */
export const createLog = (
    createLogDTO: CreateLogDTO,
 ) => {
      
      
      return clientInstance<Log>(
      {url: `/log`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createLogDTO
    },
      );
    }
  


export const getCreateLogMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createLog>>, TError,{data: CreateLogDTO}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof createLog>>, TError,{data: CreateLogDTO}, TContext> => {
const {mutation: mutationOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createLog>>, {data: CreateLogDTO}> = (props) => {
          const {data} = props ?? {};

          return  createLog(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateLogMutationResult = NonNullable<Awaited<ReturnType<typeof createLog>>>
    export type CreateLogMutationBody = CreateLogDTO
    export type CreateLogMutationError = void

    /**
 * @summary Create Log
 */
export const useCreateLog = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createLog>>, TError,{data: CreateLogDTO}, TContext>, }
): UseMutationResult<
        Awaited<ReturnType<typeof createLog>>,
        TError,
        {data: CreateLogDTO},
        TContext
      > => {

      const mutationOptions = getCreateLogMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * @summary Get all Logs
 */
export const getAllLog = (
    
 signal?: AbortSignal
) => {
      
      
      return clientInstance<Log[]>(
      {url: `/log`, method: 'GET', signal
    },
      );
    }
  

export const getGetAllLogQueryKey = () => {
    return [`/log`] as const;
    }

    
export const getGetAllLogQueryOptions = <TData = Awaited<ReturnType<typeof getAllLog>>, TError = void>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getAllLog>>, TError, TData>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAllLogQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAllLog>>> = ({ signal }) => getAllLog(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAllLog>>, TError, TData> & { queryKey: QueryKey }
}

export type GetAllLogQueryResult = NonNullable<Awaited<ReturnType<typeof getAllLog>>>
export type GetAllLogQueryError = void

/**
 * @summary Get all Logs
 */
export const useGetAllLog = <TData = Awaited<ReturnType<typeof getAllLog>>, TError = void>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getAllLog>>, TError, TData>, }

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getGetAllLogQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Get all Logs
 */
export const getQueryLog = (
    params?: GetQueryLogParams,
 signal?: AbortSignal
) => {
      
      
      return clientInstance<Log[]>(
      {url: `/log/query`, method: 'GET',
        params, signal
    },
      );
    }
  

export const getGetQueryLogQueryKey = (params?: GetQueryLogParams,) => {
    return [`/log/query`, ...(params ? [params]: [])] as const;
    }

    
export const getGetQueryLogQueryOptions = <TData = Awaited<ReturnType<typeof getQueryLog>>, TError = void>(params?: GetQueryLogParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getQueryLog>>, TError, TData>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetQueryLogQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getQueryLog>>> = ({ signal }) => getQueryLog(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getQueryLog>>, TError, TData> & { queryKey: QueryKey }
}

export type GetQueryLogQueryResult = NonNullable<Awaited<ReturnType<typeof getQueryLog>>>
export type GetQueryLogQueryError = void

/**
 * @summary Get all Logs
 */
export const useGetQueryLog = <TData = Awaited<ReturnType<typeof getQueryLog>>, TError = void>(
 params?: GetQueryLogParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getQueryLog>>, TError, TData>, }

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getGetQueryLogQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Get count of Logs
 */
export const getCountLog = (
    params?: GetCountLogParams,
 signal?: AbortSignal
) => {
      
      
      return clientInstance<number>(
      {url: `/log/count`, method: 'GET',
        params, signal
    },
      );
    }
  

export const getGetCountLogQueryKey = (params?: GetCountLogParams,) => {
    return [`/log/count`, ...(params ? [params]: [])] as const;
    }

    
export const getGetCountLogQueryOptions = <TData = Awaited<ReturnType<typeof getCountLog>>, TError = void>(params?: GetCountLogParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getCountLog>>, TError, TData>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetCountLogQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getCountLog>>> = ({ signal }) => getCountLog(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getCountLog>>, TError, TData> & { queryKey: QueryKey }
}

export type GetCountLogQueryResult = NonNullable<Awaited<ReturnType<typeof getCountLog>>>
export type GetCountLogQueryError = void

/**
 * @summary Get count of Logs
 */
export const useGetCountLog = <TData = Awaited<ReturnType<typeof getCountLog>>, TError = void>(
 params?: GetCountLogParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getCountLog>>, TError, TData>, }

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getGetCountLogQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Get one Log
 */
export const getOneLog = (
    id: number,
 signal?: AbortSignal
) => {
      
      
      return clientInstance<Log>(
      {url: `/log/${id}`, method: 'GET', signal
    },
      );
    }
  

export const getGetOneLogQueryKey = (id: number,) => {
    return [`/log/${id}`] as const;
    }

    
export const getGetOneLogQueryOptions = <TData = Awaited<ReturnType<typeof getOneLog>>, TError = void>(id: number, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getOneLog>>, TError, TData>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetOneLogQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getOneLog>>> = ({ signal }) => getOneLog(id, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getOneLog>>, TError, TData> & { queryKey: QueryKey }
}

export type GetOneLogQueryResult = NonNullable<Awaited<ReturnType<typeof getOneLog>>>
export type GetOneLogQueryError = void

/**
 * @summary Get one Log
 */
export const useGetOneLog = <TData = Awaited<ReturnType<typeof getOneLog>>, TError = void>(
 id: number, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getOneLog>>, TError, TData>, }

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getGetOneLogQueryOptions(id,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Update one Log
 */
export const updateOneLog = (
    id: number,
    log: Log,
 ) => {
      
      
      return clientInstance<void>(
      {url: `/log/${id}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: log
    },
      );
    }
  


export const getUpdateOneLogMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateOneLog>>, TError,{id: number;data: Log}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof updateOneLog>>, TError,{id: number;data: Log}, TContext> => {
const {mutation: mutationOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateOneLog>>, {id: number;data: Log}> = (props) => {
          const {id,data} = props ?? {};

          return  updateOneLog(id,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateOneLogMutationResult = NonNullable<Awaited<ReturnType<typeof updateOneLog>>>
    export type UpdateOneLogMutationBody = Log
    export type UpdateOneLogMutationError = void

    /**
 * @summary Update one Log
 */
export const useUpdateOneLog = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateOneLog>>, TError,{id: number;data: Log}, TContext>, }
): UseMutationResult<
        Awaited<ReturnType<typeof updateOneLog>>,
        TError,
        {id: number;data: Log},
        TContext
      > => {

      const mutationOptions = getUpdateOneLogMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * @summary Delete one Log
 */
export const deleteOneLog = (
    id: number,
 ) => {
      
      
      return clientInstance<void>(
      {url: `/log/${id}`, method: 'DELETE'
    },
      );
    }
  


export const getDeleteOneLogMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteOneLog>>, TError,{id: number}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof deleteOneLog>>, TError,{id: number}, TContext> => {
const {mutation: mutationOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteOneLog>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  deleteOneLog(id,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteOneLogMutationResult = NonNullable<Awaited<ReturnType<typeof deleteOneLog>>>
    
    export type DeleteOneLogMutationError = void

    /**
 * @summary Delete one Log
 */
export const useDeleteOneLog = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteOneLog>>, TError,{id: number}, TContext>, }
): UseMutationResult<
        Awaited<ReturnType<typeof deleteOneLog>>,
        TError,
        {id: number},
        TContext
      > => {

      const mutationOptions = getDeleteOneLogMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * @summary Upload a file for Log
 */
export const uploadLog = (
    
 ) => {
      
      
      return clientInstance<void>(
      {url: `/log/upload`, method: 'POST'
    },
      );
    }
  


export const getUploadLogMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof uploadLog>>, TError,void, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof uploadLog>>, TError,void, TContext> => {
const {mutation: mutationOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof uploadLog>>, void> = () => {
          

          return  uploadLog()
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UploadLogMutationResult = NonNullable<Awaited<ReturnType<typeof uploadLog>>>
    
    export type UploadLogMutationError = void

    /**
 * @summary Upload a file for Log
 */
export const useUploadLog = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof uploadLog>>, TError,void, TContext>, }
): UseMutationResult<
        Awaited<ReturnType<typeof uploadLog>>,
        TError,
        void,
        TContext
      > => {

      const mutationOptions = getUploadLogMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * @summary Download file related to Log
 */
export const downloadLog = (
    filename: string,
 signal?: AbortSignal
) => {
      
      
      return clientInstance<void>(
      {url: `/log/download/${filename}`, method: 'GET', signal
    },
      );
    }
  

export const getDownloadLogQueryKey = (filename: string,) => {
    return [`/log/download/${filename}`] as const;
    }

    
export const getDownloadLogQueryOptions = <TData = Awaited<ReturnType<typeof downloadLog>>, TError = void>(filename: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof downloadLog>>, TError, TData>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getDownloadLogQueryKey(filename);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof downloadLog>>> = ({ signal }) => downloadLog(filename, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(filename), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof downloadLog>>, TError, TData> & { queryKey: QueryKey }
}

export type DownloadLogQueryResult = NonNullable<Awaited<ReturnType<typeof downloadLog>>>
export type DownloadLogQueryError = void

/**
 * @summary Download file related to Log
 */
export const useDownloadLog = <TData = Awaited<ReturnType<typeof downloadLog>>, TError = void>(
 filename: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof downloadLog>>, TError, TData>, }

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getDownloadLogQueryOptions(filename,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



