/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * I Watch Football API
 * The API Docs for I Watch Football
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import { clientInstance } from '../client-instance';
/**
 * @summary Get match log history with freemium gating (verified limit for free users)
 */
export const logControllerGetMyHistory = (signal) => {
    return clientInstance({ url: `/log/my-history`, method: 'GET', signal
    });
};
export const getLogControllerGetMyHistoryQueryKey = () => {
    return [`/log/my-history`];
};
export const getLogControllerGetMyHistoryQueryOptions = (options) => {
    var _a;
    const { query: queryOptions } = options !== null && options !== void 0 ? options : {};
    const queryKey = (_a = queryOptions === null || queryOptions === void 0 ? void 0 : queryOptions.queryKey) !== null && _a !== void 0 ? _a : getLogControllerGetMyHistoryQueryKey();
    const queryFn = ({ signal }) => logControllerGetMyHistory(signal);
    return Object.assign({ queryKey, queryFn }, queryOptions);
};
/**
 * @summary Get match log history with freemium gating (verified limit for free users)
 */
export const useLogControllerGetMyHistory = (options) => {
    const queryOptions = getLogControllerGetMyHistoryQueryOptions(options);
    const query = useQuery(queryOptions);
    query.queryKey = queryOptions.queryKey;
    return query;
};
/**
 * @summary Create Log
 */
export const createLog = (createLogDTO) => {
    return clientInstance({ url: `/log`, method: 'POST',
        headers: { 'Content-Type': 'application/json', },
        data: createLogDTO
    });
};
export const getCreateLogMutationOptions = (options) => {
    const { mutation: mutationOptions } = options !== null && options !== void 0 ? options : {};
    const mutationFn = (props) => {
        const { data } = props !== null && props !== void 0 ? props : {};
        return createLog(data);
    };
    return Object.assign({ mutationFn }, mutationOptions);
};
/**
* @summary Create Log
*/
export const useCreateLog = (options) => {
    const mutationOptions = getCreateLogMutationOptions(options);
    return useMutation(mutationOptions);
};
/**
* @summary Get all Logs
*/
export const getAllLog = (signal) => {
    return clientInstance({ url: `/log`, method: 'GET', signal
    });
};
export const getGetAllLogQueryKey = () => {
    return [`/log`];
};
export const getGetAllLogQueryOptions = (options) => {
    var _a;
    const { query: queryOptions } = options !== null && options !== void 0 ? options : {};
    const queryKey = (_a = queryOptions === null || queryOptions === void 0 ? void 0 : queryOptions.queryKey) !== null && _a !== void 0 ? _a : getGetAllLogQueryKey();
    const queryFn = ({ signal }) => getAllLog(signal);
    return Object.assign({ queryKey, queryFn }, queryOptions);
};
/**
 * @summary Get all Logs
 */
export const useGetAllLog = (options) => {
    const queryOptions = getGetAllLogQueryOptions(options);
    const query = useQuery(queryOptions);
    query.queryKey = queryOptions.queryKey;
    return query;
};
/**
 * @summary Get all Logs
 */
export const getQueryLog = (params, signal) => {
    return clientInstance({ url: `/log/query`, method: 'GET',
        params, signal
    });
};
export const getGetQueryLogQueryKey = (params) => {
    return [`/log/query`, ...(params ? [params] : [])];
};
export const getGetQueryLogQueryOptions = (params, options) => {
    var _a;
    const { query: queryOptions } = options !== null && options !== void 0 ? options : {};
    const queryKey = (_a = queryOptions === null || queryOptions === void 0 ? void 0 : queryOptions.queryKey) !== null && _a !== void 0 ? _a : getGetQueryLogQueryKey(params);
    const queryFn = ({ signal }) => getQueryLog(params, signal);
    return Object.assign({ queryKey, queryFn }, queryOptions);
};
/**
 * @summary Get all Logs
 */
export const useGetQueryLog = (params, options) => {
    const queryOptions = getGetQueryLogQueryOptions(params, options);
    const query = useQuery(queryOptions);
    query.queryKey = queryOptions.queryKey;
    return query;
};
/**
 * @summary Get count of Logs
 */
export const getCountLog = (params, signal) => {
    return clientInstance({ url: `/log/count`, method: 'GET',
        params, signal
    });
};
export const getGetCountLogQueryKey = (params) => {
    return [`/log/count`, ...(params ? [params] : [])];
};
export const getGetCountLogQueryOptions = (params, options) => {
    var _a;
    const { query: queryOptions } = options !== null && options !== void 0 ? options : {};
    const queryKey = (_a = queryOptions === null || queryOptions === void 0 ? void 0 : queryOptions.queryKey) !== null && _a !== void 0 ? _a : getGetCountLogQueryKey(params);
    const queryFn = ({ signal }) => getCountLog(params, signal);
    return Object.assign({ queryKey, queryFn }, queryOptions);
};
/**
 * @summary Get count of Logs
 */
export const useGetCountLog = (params, options) => {
    const queryOptions = getGetCountLogQueryOptions(params, options);
    const query = useQuery(queryOptions);
    query.queryKey = queryOptions.queryKey;
    return query;
};
/**
 * @summary Get one Log
 */
export const getOneLog = (id, signal) => {
    return clientInstance({ url: `/log/${id}`, method: 'GET', signal
    });
};
export const getGetOneLogQueryKey = (id) => {
    return [`/log/${id}`];
};
export const getGetOneLogQueryOptions = (id, options) => {
    var _a;
    const { query: queryOptions } = options !== null && options !== void 0 ? options : {};
    const queryKey = (_a = queryOptions === null || queryOptions === void 0 ? void 0 : queryOptions.queryKey) !== null && _a !== void 0 ? _a : getGetOneLogQueryKey(id);
    const queryFn = ({ signal }) => getOneLog(id, signal);
    return Object.assign({ queryKey, queryFn, enabled: !!(id) }, queryOptions);
};
/**
 * @summary Get one Log
 */
export const useGetOneLog = (id, options) => {
    const queryOptions = getGetOneLogQueryOptions(id, options);
    const query = useQuery(queryOptions);
    query.queryKey = queryOptions.queryKey;
    return query;
};
/**
 * @summary Update one Log
 */
export const updateOneLog = (id, log) => {
    return clientInstance({ url: `/log/${id}`, method: 'PATCH',
        headers: { 'Content-Type': 'application/json', },
        data: log
    });
};
export const getUpdateOneLogMutationOptions = (options) => {
    const { mutation: mutationOptions } = options !== null && options !== void 0 ? options : {};
    const mutationFn = (props) => {
        const { id, data } = props !== null && props !== void 0 ? props : {};
        return updateOneLog(id, data);
    };
    return Object.assign({ mutationFn }, mutationOptions);
};
/**
* @summary Update one Log
*/
export const useUpdateOneLog = (options) => {
    const mutationOptions = getUpdateOneLogMutationOptions(options);
    return useMutation(mutationOptions);
};
/**
* @summary Delete one Log
*/
export const deleteOneLog = (id) => {
    return clientInstance({ url: `/log/${id}`, method: 'DELETE'
    });
};
export const getDeleteOneLogMutationOptions = (options) => {
    const { mutation: mutationOptions } = options !== null && options !== void 0 ? options : {};
    const mutationFn = (props) => {
        const { id } = props !== null && props !== void 0 ? props : {};
        return deleteOneLog(id);
    };
    return Object.assign({ mutationFn }, mutationOptions);
};
/**
* @summary Delete one Log
*/
export const useDeleteOneLog = (options) => {
    const mutationOptions = getDeleteOneLogMutationOptions(options);
    return useMutation(mutationOptions);
};
/**
* @summary Upload a file for Log
*/
export const uploadLog = () => {
    return clientInstance({ url: `/log/upload`, method: 'POST'
    });
};
export const getUploadLogMutationOptions = (options) => {
    const { mutation: mutationOptions } = options !== null && options !== void 0 ? options : {};
    const mutationFn = () => {
        return uploadLog();
    };
    return Object.assign({ mutationFn }, mutationOptions);
};
/**
* @summary Upload a file for Log
*/
export const useUploadLog = (options) => {
    const mutationOptions = getUploadLogMutationOptions(options);
    return useMutation(mutationOptions);
};
/**
* @summary Download file related to Log
*/
export const downloadLog = (filename, signal) => {
    return clientInstance({ url: `/log/download/${filename}`, method: 'GET', signal
    });
};
export const getDownloadLogQueryKey = (filename) => {
    return [`/log/download/${filename}`];
};
export const getDownloadLogQueryOptions = (filename, options) => {
    var _a;
    const { query: queryOptions } = options !== null && options !== void 0 ? options : {};
    const queryKey = (_a = queryOptions === null || queryOptions === void 0 ? void 0 : queryOptions.queryKey) !== null && _a !== void 0 ? _a : getDownloadLogQueryKey(filename);
    const queryFn = ({ signal }) => downloadLog(filename, signal);
    return Object.assign({ queryKey, queryFn, enabled: !!(filename) }, queryOptions);
};
/**
 * @summary Download file related to Log
 */
export const useDownloadLog = (filename, options) => {
    const queryOptions = getDownloadLogQueryOptions(filename, options);
    const query = useQuery(queryOptions);
    query.queryKey = queryOptions.queryKey;
    return query;
};
//# sourceMappingURL=log.js.map