/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * I Watch Football API
 * The API Docs for I Watch Football
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import { clientInstance } from '../client-instance';
/**
 * @summary Create LoyaltyEvent
 */
export const createLoyaltyEvent = (createLoyaltyEventDTO) => {
    return clientInstance({ url: `/loyaltyEvent`, method: 'POST',
        headers: { 'Content-Type': 'application/json', },
        data: createLoyaltyEventDTO
    });
};
export const getCreateLoyaltyEventMutationOptions = (options) => {
    const { mutation: mutationOptions } = options !== null && options !== void 0 ? options : {};
    const mutationFn = (props) => {
        const { data } = props !== null && props !== void 0 ? props : {};
        return createLoyaltyEvent(data);
    };
    return Object.assign({ mutationFn }, mutationOptions);
};
/**
* @summary Create LoyaltyEvent
*/
export const useCreateLoyaltyEvent = (options) => {
    const mutationOptions = getCreateLoyaltyEventMutationOptions(options);
    return useMutation(mutationOptions);
};
/**
* @summary Get all LoyaltyEvents
*/
export const getAllLoyaltyEvent = (signal) => {
    return clientInstance({ url: `/loyaltyEvent`, method: 'GET', signal
    });
};
export const getGetAllLoyaltyEventQueryKey = () => {
    return [`/loyaltyEvent`];
};
export const getGetAllLoyaltyEventQueryOptions = (options) => {
    var _a;
    const { query: queryOptions } = options !== null && options !== void 0 ? options : {};
    const queryKey = (_a = queryOptions === null || queryOptions === void 0 ? void 0 : queryOptions.queryKey) !== null && _a !== void 0 ? _a : getGetAllLoyaltyEventQueryKey();
    const queryFn = ({ signal }) => getAllLoyaltyEvent(signal);
    return Object.assign({ queryKey, queryFn }, queryOptions);
};
/**
 * @summary Get all LoyaltyEvents
 */
export const useGetAllLoyaltyEvent = (options) => {
    const queryOptions = getGetAllLoyaltyEventQueryOptions(options);
    const query = useQuery(queryOptions);
    query.queryKey = queryOptions.queryKey;
    return query;
};
/**
 * @summary Get all LoyaltyEvents
 */
export const getQueryLoyaltyEvent = (params, signal) => {
    return clientInstance({ url: `/loyaltyEvent/query`, method: 'GET',
        params, signal
    });
};
export const getGetQueryLoyaltyEventQueryKey = (params) => {
    return [`/loyaltyEvent/query`, ...(params ? [params] : [])];
};
export const getGetQueryLoyaltyEventQueryOptions = (params, options) => {
    var _a;
    const { query: queryOptions } = options !== null && options !== void 0 ? options : {};
    const queryKey = (_a = queryOptions === null || queryOptions === void 0 ? void 0 : queryOptions.queryKey) !== null && _a !== void 0 ? _a : getGetQueryLoyaltyEventQueryKey(params);
    const queryFn = ({ signal }) => getQueryLoyaltyEvent(params, signal);
    return Object.assign({ queryKey, queryFn }, queryOptions);
};
/**
 * @summary Get all LoyaltyEvents
 */
export const useGetQueryLoyaltyEvent = (params, options) => {
    const queryOptions = getGetQueryLoyaltyEventQueryOptions(params, options);
    const query = useQuery(queryOptions);
    query.queryKey = queryOptions.queryKey;
    return query;
};
/**
 * @summary Get count of LoyaltyEvents
 */
export const getCountLoyaltyEvent = (params, signal) => {
    return clientInstance({ url: `/loyaltyEvent/count`, method: 'GET',
        params, signal
    });
};
export const getGetCountLoyaltyEventQueryKey = (params) => {
    return [`/loyaltyEvent/count`, ...(params ? [params] : [])];
};
export const getGetCountLoyaltyEventQueryOptions = (params, options) => {
    var _a;
    const { query: queryOptions } = options !== null && options !== void 0 ? options : {};
    const queryKey = (_a = queryOptions === null || queryOptions === void 0 ? void 0 : queryOptions.queryKey) !== null && _a !== void 0 ? _a : getGetCountLoyaltyEventQueryKey(params);
    const queryFn = ({ signal }) => getCountLoyaltyEvent(params, signal);
    return Object.assign({ queryKey, queryFn }, queryOptions);
};
/**
 * @summary Get count of LoyaltyEvents
 */
export const useGetCountLoyaltyEvent = (params, options) => {
    const queryOptions = getGetCountLoyaltyEventQueryOptions(params, options);
    const query = useQuery(queryOptions);
    query.queryKey = queryOptions.queryKey;
    return query;
};
/**
 * @summary Get one LoyaltyEvent
 */
export const getOneLoyaltyEvent = (id, signal) => {
    return clientInstance({ url: `/loyaltyEvent/${id}`, method: 'GET', signal
    });
};
export const getGetOneLoyaltyEventQueryKey = (id) => {
    return [`/loyaltyEvent/${id}`];
};
export const getGetOneLoyaltyEventQueryOptions = (id, options) => {
    var _a;
    const { query: queryOptions } = options !== null && options !== void 0 ? options : {};
    const queryKey = (_a = queryOptions === null || queryOptions === void 0 ? void 0 : queryOptions.queryKey) !== null && _a !== void 0 ? _a : getGetOneLoyaltyEventQueryKey(id);
    const queryFn = ({ signal }) => getOneLoyaltyEvent(id, signal);
    return Object.assign({ queryKey, queryFn, enabled: !!(id) }, queryOptions);
};
/**
 * @summary Get one LoyaltyEvent
 */
export const useGetOneLoyaltyEvent = (id, options) => {
    const queryOptions = getGetOneLoyaltyEventQueryOptions(id, options);
    const query = useQuery(queryOptions);
    query.queryKey = queryOptions.queryKey;
    return query;
};
/**
 * @summary Update one LoyaltyEvent
 */
export const updateOneLoyaltyEvent = (id, loyaltyEvent) => {
    return clientInstance({ url: `/loyaltyEvent/${id}`, method: 'PATCH',
        headers: { 'Content-Type': 'application/json', },
        data: loyaltyEvent
    });
};
export const getUpdateOneLoyaltyEventMutationOptions = (options) => {
    const { mutation: mutationOptions } = options !== null && options !== void 0 ? options : {};
    const mutationFn = (props) => {
        const { id, data } = props !== null && props !== void 0 ? props : {};
        return updateOneLoyaltyEvent(id, data);
    };
    return Object.assign({ mutationFn }, mutationOptions);
};
/**
* @summary Update one LoyaltyEvent
*/
export const useUpdateOneLoyaltyEvent = (options) => {
    const mutationOptions = getUpdateOneLoyaltyEventMutationOptions(options);
    return useMutation(mutationOptions);
};
/**
* @summary Delete one LoyaltyEvent
*/
export const deleteOneLoyaltyEvent = (id) => {
    return clientInstance({ url: `/loyaltyEvent/${id}`, method: 'DELETE'
    });
};
export const getDeleteOneLoyaltyEventMutationOptions = (options) => {
    const { mutation: mutationOptions } = options !== null && options !== void 0 ? options : {};
    const mutationFn = (props) => {
        const { id } = props !== null && props !== void 0 ? props : {};
        return deleteOneLoyaltyEvent(id);
    };
    return Object.assign({ mutationFn }, mutationOptions);
};
/**
* @summary Delete one LoyaltyEvent
*/
export const useDeleteOneLoyaltyEvent = (options) => {
    const mutationOptions = getDeleteOneLoyaltyEventMutationOptions(options);
    return useMutation(mutationOptions);
};
/**
* @summary Upload a file for LoyaltyEvent
*/
export const uploadLoyaltyEvent = () => {
    return clientInstance({ url: `/loyaltyEvent/upload`, method: 'POST'
    });
};
export const getUploadLoyaltyEventMutationOptions = (options) => {
    const { mutation: mutationOptions } = options !== null && options !== void 0 ? options : {};
    const mutationFn = () => {
        return uploadLoyaltyEvent();
    };
    return Object.assign({ mutationFn }, mutationOptions);
};
/**
* @summary Upload a file for LoyaltyEvent
*/
export const useUploadLoyaltyEvent = (options) => {
    const mutationOptions = getUploadLoyaltyEventMutationOptions(options);
    return useMutation(mutationOptions);
};
/**
* @summary Download file related to LoyaltyEvent
*/
export const downloadLoyaltyEvent = (filename, signal) => {
    return clientInstance({ url: `/loyaltyEvent/download/${filename}`, method: 'GET', signal
    });
};
export const getDownloadLoyaltyEventQueryKey = (filename) => {
    return [`/loyaltyEvent/download/${filename}`];
};
export const getDownloadLoyaltyEventQueryOptions = (filename, options) => {
    var _a;
    const { query: queryOptions } = options !== null && options !== void 0 ? options : {};
    const queryKey = (_a = queryOptions === null || queryOptions === void 0 ? void 0 : queryOptions.queryKey) !== null && _a !== void 0 ? _a : getDownloadLoyaltyEventQueryKey(filename);
    const queryFn = ({ signal }) => downloadLoyaltyEvent(filename, signal);
    return Object.assign({ queryKey, queryFn, enabled: !!(filename) }, queryOptions);
};
/**
 * @summary Download file related to LoyaltyEvent
 */
export const useDownloadLoyaltyEvent = (filename, options) => {
    const queryOptions = getDownloadLoyaltyEventQueryOptions(filename, options);
    const query = useQuery(queryOptions);
    query.queryKey = queryOptions.queryKey;
    return query;
};
//# sourceMappingURL=loyalty-event.js.map