/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * I Watch Football API
 * The API Docs for I Watch Football
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import { clientInstance } from '../client-instance';
/**
 * @summary Create LoyaltyScheme
 */
export const createLoyaltyScheme = (createLoyaltySchemeDTO) => {
    return clientInstance({ url: `/loyaltyScheme`, method: 'POST',
        headers: { 'Content-Type': 'application/json', },
        data: createLoyaltySchemeDTO
    });
};
export const getCreateLoyaltySchemeMutationOptions = (options) => {
    const { mutation: mutationOptions } = options !== null && options !== void 0 ? options : {};
    const mutationFn = (props) => {
        const { data } = props !== null && props !== void 0 ? props : {};
        return createLoyaltyScheme(data);
    };
    return Object.assign({ mutationFn }, mutationOptions);
};
/**
* @summary Create LoyaltyScheme
*/
export const useCreateLoyaltyScheme = (options) => {
    const mutationOptions = getCreateLoyaltySchemeMutationOptions(options);
    return useMutation(mutationOptions);
};
/**
* @summary Get all LoyaltySchemes
*/
export const getAllLoyaltyScheme = (signal) => {
    return clientInstance({ url: `/loyaltyScheme`, method: 'GET', signal
    });
};
export const getGetAllLoyaltySchemeQueryKey = () => {
    return [`/loyaltyScheme`];
};
export const getGetAllLoyaltySchemeQueryOptions = (options) => {
    var _a;
    const { query: queryOptions } = options !== null && options !== void 0 ? options : {};
    const queryKey = (_a = queryOptions === null || queryOptions === void 0 ? void 0 : queryOptions.queryKey) !== null && _a !== void 0 ? _a : getGetAllLoyaltySchemeQueryKey();
    const queryFn = ({ signal }) => getAllLoyaltyScheme(signal);
    return Object.assign({ queryKey, queryFn }, queryOptions);
};
/**
 * @summary Get all LoyaltySchemes
 */
export const useGetAllLoyaltyScheme = (options) => {
    const queryOptions = getGetAllLoyaltySchemeQueryOptions(options);
    const query = useQuery(queryOptions);
    query.queryKey = queryOptions.queryKey;
    return query;
};
/**
 * @summary Get all LoyaltySchemes
 */
export const getQueryLoyaltyScheme = (params, signal) => {
    return clientInstance({ url: `/loyaltyScheme/query`, method: 'GET',
        params, signal
    });
};
export const getGetQueryLoyaltySchemeQueryKey = (params) => {
    return [`/loyaltyScheme/query`, ...(params ? [params] : [])];
};
export const getGetQueryLoyaltySchemeQueryOptions = (params, options) => {
    var _a;
    const { query: queryOptions } = options !== null && options !== void 0 ? options : {};
    const queryKey = (_a = queryOptions === null || queryOptions === void 0 ? void 0 : queryOptions.queryKey) !== null && _a !== void 0 ? _a : getGetQueryLoyaltySchemeQueryKey(params);
    const queryFn = ({ signal }) => getQueryLoyaltyScheme(params, signal);
    return Object.assign({ queryKey, queryFn }, queryOptions);
};
/**
 * @summary Get all LoyaltySchemes
 */
export const useGetQueryLoyaltyScheme = (params, options) => {
    const queryOptions = getGetQueryLoyaltySchemeQueryOptions(params, options);
    const query = useQuery(queryOptions);
    query.queryKey = queryOptions.queryKey;
    return query;
};
/**
 * @summary Get count of LoyaltySchemes
 */
export const getCountLoyaltyScheme = (params, signal) => {
    return clientInstance({ url: `/loyaltyScheme/count`, method: 'GET',
        params, signal
    });
};
export const getGetCountLoyaltySchemeQueryKey = (params) => {
    return [`/loyaltyScheme/count`, ...(params ? [params] : [])];
};
export const getGetCountLoyaltySchemeQueryOptions = (params, options) => {
    var _a;
    const { query: queryOptions } = options !== null && options !== void 0 ? options : {};
    const queryKey = (_a = queryOptions === null || queryOptions === void 0 ? void 0 : queryOptions.queryKey) !== null && _a !== void 0 ? _a : getGetCountLoyaltySchemeQueryKey(params);
    const queryFn = ({ signal }) => getCountLoyaltyScheme(params, signal);
    return Object.assign({ queryKey, queryFn }, queryOptions);
};
/**
 * @summary Get count of LoyaltySchemes
 */
export const useGetCountLoyaltyScheme = (params, options) => {
    const queryOptions = getGetCountLoyaltySchemeQueryOptions(params, options);
    const query = useQuery(queryOptions);
    query.queryKey = queryOptions.queryKey;
    return query;
};
/**
 * @summary Get one LoyaltyScheme
 */
export const getOneLoyaltyScheme = (id, signal) => {
    return clientInstance({ url: `/loyaltyScheme/${id}`, method: 'GET', signal
    });
};
export const getGetOneLoyaltySchemeQueryKey = (id) => {
    return [`/loyaltyScheme/${id}`];
};
export const getGetOneLoyaltySchemeQueryOptions = (id, options) => {
    var _a;
    const { query: queryOptions } = options !== null && options !== void 0 ? options : {};
    const queryKey = (_a = queryOptions === null || queryOptions === void 0 ? void 0 : queryOptions.queryKey) !== null && _a !== void 0 ? _a : getGetOneLoyaltySchemeQueryKey(id);
    const queryFn = ({ signal }) => getOneLoyaltyScheme(id, signal);
    return Object.assign({ queryKey, queryFn, enabled: !!(id) }, queryOptions);
};
/**
 * @summary Get one LoyaltyScheme
 */
export const useGetOneLoyaltyScheme = (id, options) => {
    const queryOptions = getGetOneLoyaltySchemeQueryOptions(id, options);
    const query = useQuery(queryOptions);
    query.queryKey = queryOptions.queryKey;
    return query;
};
/**
 * @summary Update one LoyaltyScheme
 */
export const updateOneLoyaltyScheme = (id, loyaltyScheme) => {
    return clientInstance({ url: `/loyaltyScheme/${id}`, method: 'PATCH',
        headers: { 'Content-Type': 'application/json', },
        data: loyaltyScheme
    });
};
export const getUpdateOneLoyaltySchemeMutationOptions = (options) => {
    const { mutation: mutationOptions } = options !== null && options !== void 0 ? options : {};
    const mutationFn = (props) => {
        const { id, data } = props !== null && props !== void 0 ? props : {};
        return updateOneLoyaltyScheme(id, data);
    };
    return Object.assign({ mutationFn }, mutationOptions);
};
/**
* @summary Update one LoyaltyScheme
*/
export const useUpdateOneLoyaltyScheme = (options) => {
    const mutationOptions = getUpdateOneLoyaltySchemeMutationOptions(options);
    return useMutation(mutationOptions);
};
/**
* @summary Delete one LoyaltyScheme
*/
export const deleteOneLoyaltyScheme = (id) => {
    return clientInstance({ url: `/loyaltyScheme/${id}`, method: 'DELETE'
    });
};
export const getDeleteOneLoyaltySchemeMutationOptions = (options) => {
    const { mutation: mutationOptions } = options !== null && options !== void 0 ? options : {};
    const mutationFn = (props) => {
        const { id } = props !== null && props !== void 0 ? props : {};
        return deleteOneLoyaltyScheme(id);
    };
    return Object.assign({ mutationFn }, mutationOptions);
};
/**
* @summary Delete one LoyaltyScheme
*/
export const useDeleteOneLoyaltyScheme = (options) => {
    const mutationOptions = getDeleteOneLoyaltySchemeMutationOptions(options);
    return useMutation(mutationOptions);
};
/**
* @summary Upload a file for LoyaltyScheme
*/
export const uploadLoyaltyScheme = () => {
    return clientInstance({ url: `/loyaltyScheme/upload`, method: 'POST'
    });
};
export const getUploadLoyaltySchemeMutationOptions = (options) => {
    const { mutation: mutationOptions } = options !== null && options !== void 0 ? options : {};
    const mutationFn = () => {
        return uploadLoyaltyScheme();
    };
    return Object.assign({ mutationFn }, mutationOptions);
};
/**
* @summary Upload a file for LoyaltyScheme
*/
export const useUploadLoyaltyScheme = (options) => {
    const mutationOptions = getUploadLoyaltySchemeMutationOptions(options);
    return useMutation(mutationOptions);
};
/**
* @summary Download file related to LoyaltyScheme
*/
export const downloadLoyaltyScheme = (filename, signal) => {
    return clientInstance({ url: `/loyaltyScheme/download/${filename}`, method: 'GET', signal
    });
};
export const getDownloadLoyaltySchemeQueryKey = (filename) => {
    return [`/loyaltyScheme/download/${filename}`];
};
export const getDownloadLoyaltySchemeQueryOptions = (filename, options) => {
    var _a;
    const { query: queryOptions } = options !== null && options !== void 0 ? options : {};
    const queryKey = (_a = queryOptions === null || queryOptions === void 0 ? void 0 : queryOptions.queryKey) !== null && _a !== void 0 ? _a : getDownloadLoyaltySchemeQueryKey(filename);
    const queryFn = ({ signal }) => downloadLoyaltyScheme(filename, signal);
    return Object.assign({ queryKey, queryFn, enabled: !!(filename) }, queryOptions);
};
/**
 * @summary Download file related to LoyaltyScheme
 */
export const useDownloadLoyaltyScheme = (filename, options) => {
    const queryOptions = getDownloadLoyaltySchemeQueryOptions(filename, options);
    const query = useQuery(queryOptions);
    query.queryKey = queryOptions.queryKey;
    return query;
};
//# sourceMappingURL=loyalty-scheme.js.map