/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * I Watch Football API
 * The API Docs for I Watch Football
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import { clientInstance } from '../client-instance';
/**
 * @summary Create Manager
 */
export const createManager = (createManagerDTO) => {
    return clientInstance({ url: `/manager`, method: 'POST',
        headers: { 'Content-Type': 'application/json', },
        data: createManagerDTO
    });
};
export const getCreateManagerMutationOptions = (options) => {
    const { mutation: mutationOptions } = options !== null && options !== void 0 ? options : {};
    const mutationFn = (props) => {
        const { data } = props !== null && props !== void 0 ? props : {};
        return createManager(data);
    };
    return Object.assign({ mutationFn }, mutationOptions);
};
/**
* @summary Create Manager
*/
export const useCreateManager = (options) => {
    const mutationOptions = getCreateManagerMutationOptions(options);
    return useMutation(mutationOptions);
};
/**
* @summary Get all Managers
*/
export const getAllManager = (signal) => {
    return clientInstance({ url: `/manager`, method: 'GET', signal
    });
};
export const getGetAllManagerQueryKey = () => {
    return [`/manager`];
};
export const getGetAllManagerQueryOptions = (options) => {
    var _a;
    const { query: queryOptions } = options !== null && options !== void 0 ? options : {};
    const queryKey = (_a = queryOptions === null || queryOptions === void 0 ? void 0 : queryOptions.queryKey) !== null && _a !== void 0 ? _a : getGetAllManagerQueryKey();
    const queryFn = ({ signal }) => getAllManager(signal);
    return Object.assign({ queryKey, queryFn }, queryOptions);
};
/**
 * @summary Get all Managers
 */
export const useGetAllManager = (options) => {
    const queryOptions = getGetAllManagerQueryOptions(options);
    const query = useQuery(queryOptions);
    query.queryKey = queryOptions.queryKey;
    return query;
};
/**
 * @summary Get all Managers
 */
export const getQueryManager = (params, signal) => {
    return clientInstance({ url: `/manager/query`, method: 'GET',
        params, signal
    });
};
export const getGetQueryManagerQueryKey = (params) => {
    return [`/manager/query`, ...(params ? [params] : [])];
};
export const getGetQueryManagerQueryOptions = (params, options) => {
    var _a;
    const { query: queryOptions } = options !== null && options !== void 0 ? options : {};
    const queryKey = (_a = queryOptions === null || queryOptions === void 0 ? void 0 : queryOptions.queryKey) !== null && _a !== void 0 ? _a : getGetQueryManagerQueryKey(params);
    const queryFn = ({ signal }) => getQueryManager(params, signal);
    return Object.assign({ queryKey, queryFn }, queryOptions);
};
/**
 * @summary Get all Managers
 */
export const useGetQueryManager = (params, options) => {
    const queryOptions = getGetQueryManagerQueryOptions(params, options);
    const query = useQuery(queryOptions);
    query.queryKey = queryOptions.queryKey;
    return query;
};
/**
 * @summary Get count of Managers
 */
export const getCountManager = (params, signal) => {
    return clientInstance({ url: `/manager/count`, method: 'GET',
        params, signal
    });
};
export const getGetCountManagerQueryKey = (params) => {
    return [`/manager/count`, ...(params ? [params] : [])];
};
export const getGetCountManagerQueryOptions = (params, options) => {
    var _a;
    const { query: queryOptions } = options !== null && options !== void 0 ? options : {};
    const queryKey = (_a = queryOptions === null || queryOptions === void 0 ? void 0 : queryOptions.queryKey) !== null && _a !== void 0 ? _a : getGetCountManagerQueryKey(params);
    const queryFn = ({ signal }) => getCountManager(params, signal);
    return Object.assign({ queryKey, queryFn }, queryOptions);
};
/**
 * @summary Get count of Managers
 */
export const useGetCountManager = (params, options) => {
    const queryOptions = getGetCountManagerQueryOptions(params, options);
    const query = useQuery(queryOptions);
    query.queryKey = queryOptions.queryKey;
    return query;
};
/**
 * @summary Get one Manager
 */
export const getOneManager = (id, signal) => {
    return clientInstance({ url: `/manager/${id}`, method: 'GET', signal
    });
};
export const getGetOneManagerQueryKey = (id) => {
    return [`/manager/${id}`];
};
export const getGetOneManagerQueryOptions = (id, options) => {
    var _a;
    const { query: queryOptions } = options !== null && options !== void 0 ? options : {};
    const queryKey = (_a = queryOptions === null || queryOptions === void 0 ? void 0 : queryOptions.queryKey) !== null && _a !== void 0 ? _a : getGetOneManagerQueryKey(id);
    const queryFn = ({ signal }) => getOneManager(id, signal);
    return Object.assign({ queryKey, queryFn, enabled: !!(id) }, queryOptions);
};
/**
 * @summary Get one Manager
 */
export const useGetOneManager = (id, options) => {
    const queryOptions = getGetOneManagerQueryOptions(id, options);
    const query = useQuery(queryOptions);
    query.queryKey = queryOptions.queryKey;
    return query;
};
/**
 * @summary Update one Manager
 */
export const updateOneManager = (id, manager) => {
    return clientInstance({ url: `/manager/${id}`, method: 'PATCH',
        headers: { 'Content-Type': 'application/json', },
        data: manager
    });
};
export const getUpdateOneManagerMutationOptions = (options) => {
    const { mutation: mutationOptions } = options !== null && options !== void 0 ? options : {};
    const mutationFn = (props) => {
        const { id, data } = props !== null && props !== void 0 ? props : {};
        return updateOneManager(id, data);
    };
    return Object.assign({ mutationFn }, mutationOptions);
};
/**
* @summary Update one Manager
*/
export const useUpdateOneManager = (options) => {
    const mutationOptions = getUpdateOneManagerMutationOptions(options);
    return useMutation(mutationOptions);
};
/**
* @summary Delete one Manager
*/
export const deleteOneManager = (id) => {
    return clientInstance({ url: `/manager/${id}`, method: 'DELETE'
    });
};
export const getDeleteOneManagerMutationOptions = (options) => {
    const { mutation: mutationOptions } = options !== null && options !== void 0 ? options : {};
    const mutationFn = (props) => {
        const { id } = props !== null && props !== void 0 ? props : {};
        return deleteOneManager(id);
    };
    return Object.assign({ mutationFn }, mutationOptions);
};
/**
* @summary Delete one Manager
*/
export const useDeleteOneManager = (options) => {
    const mutationOptions = getDeleteOneManagerMutationOptions(options);
    return useMutation(mutationOptions);
};
/**
* @summary Upload a file for Manager
*/
export const uploadManager = () => {
    return clientInstance({ url: `/manager/upload`, method: 'POST'
    });
};
export const getUploadManagerMutationOptions = (options) => {
    const { mutation: mutationOptions } = options !== null && options !== void 0 ? options : {};
    const mutationFn = () => {
        return uploadManager();
    };
    return Object.assign({ mutationFn }, mutationOptions);
};
/**
* @summary Upload a file for Manager
*/
export const useUploadManager = (options) => {
    const mutationOptions = getUploadManagerMutationOptions(options);
    return useMutation(mutationOptions);
};
/**
* @summary Download file related to Manager
*/
export const downloadManager = (filename, signal) => {
    return clientInstance({ url: `/manager/download/${filename}`, method: 'GET', signal
    });
};
export const getDownloadManagerQueryKey = (filename) => {
    return [`/manager/download/${filename}`];
};
export const getDownloadManagerQueryOptions = (filename, options) => {
    var _a;
    const { query: queryOptions } = options !== null && options !== void 0 ? options : {};
    const queryKey = (_a = queryOptions === null || queryOptions === void 0 ? void 0 : queryOptions.queryKey) !== null && _a !== void 0 ? _a : getDownloadManagerQueryKey(filename);
    const queryFn = ({ signal }) => downloadManager(filename, signal);
    return Object.assign({ queryKey, queryFn, enabled: !!(filename) }, queryOptions);
};
/**
 * @summary Download file related to Manager
 */
export const useDownloadManager = (filename, options) => {
    const queryOptions = getDownloadManagerQueryOptions(filename, options);
    const query = useQuery(queryOptions);
    query.queryKey = queryOptions.queryKey;
    return query;
};
//# sourceMappingURL=manager.js.map