/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * I Watch Football API
 * The API Docs for I Watch Football
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query'
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query'
import type {
  ConfirmMarketplacePurchaseDto,
  CreateListingDto,
  MarketplaceCheckoutControllerConfirmPurchase200,
  MarketplaceCheckoutControllerGetFeePreview200,
  MarketplaceCheckoutControllerHoldListing200,
  MarketplaceListingControllerCancelListing200,
  MarketplaceListingControllerGetListings200,
  MarketplaceListingControllerGetListingsParams,
  UpdatePlatformConfigDto
} from './iWatchFootballAPI.schemas'
import { clientInstance } from '../client-instance';




/**
 * @summary Browse active marketplace listings
 */
export const marketplaceListingControllerGetListings = (
    params?: MarketplaceListingControllerGetListingsParams,
 signal?: AbortSignal
) => {
      
      
      return clientInstance<MarketplaceListingControllerGetListings200>(
      {url: `/marketplace/listings`, method: 'GET',
        params, signal
    },
      );
    }
  

export const getMarketplaceListingControllerGetListingsQueryKey = (params?: MarketplaceListingControllerGetListingsParams,) => {
    return [`/marketplace/listings`, ...(params ? [params]: [])] as const;
    }

    
export const getMarketplaceListingControllerGetListingsQueryOptions = <TData = Awaited<ReturnType<typeof marketplaceListingControllerGetListings>>, TError = void>(params?: MarketplaceListingControllerGetListingsParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof marketplaceListingControllerGetListings>>, TError, TData>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getMarketplaceListingControllerGetListingsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof marketplaceListingControllerGetListings>>> = ({ signal }) => marketplaceListingControllerGetListings(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof marketplaceListingControllerGetListings>>, TError, TData> & { queryKey: QueryKey }
}

export type MarketplaceListingControllerGetListingsQueryResult = NonNullable<Awaited<ReturnType<typeof marketplaceListingControllerGetListings>>>
export type MarketplaceListingControllerGetListingsQueryError = void

/**
 * @summary Browse active marketplace listings
 */
export const useMarketplaceListingControllerGetListings = <TData = Awaited<ReturnType<typeof marketplaceListingControllerGetListings>>, TError = void>(
 params?: MarketplaceListingControllerGetListingsParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof marketplaceListingControllerGetListings>>, TError, TData>, }

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getMarketplaceListingControllerGetListingsQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Browse active marketplace listings
 */
export const marketplaceListingControllerGetListings = (
    params?: MarketplaceListingControllerGetListingsParams,
 signal?: AbortSignal
) => {
      
      
      return clientInstance<MarketplaceListingControllerGetListings200>(
      {url: `/marketplace/listings`, method: 'GET',
        params, signal
    },
      );
    }
  

export const getMarketplaceListingControllerGetListingsQueryKey = (params?: MarketplaceListingControllerGetListingsParams,) => {
    return [`/marketplace/listings`, ...(params ? [params]: [])] as const;
    }

    
export const getMarketplaceListingControllerGetListingsQueryOptions = <TData = Awaited<ReturnType<typeof marketplaceListingControllerGetListings>>, TError = void>(params?: MarketplaceListingControllerGetListingsParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof marketplaceListingControllerGetListings>>, TError, TData>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getMarketplaceListingControllerGetListingsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof marketplaceListingControllerGetListings>>> = ({ signal }) => marketplaceListingControllerGetListings(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof marketplaceListingControllerGetListings>>, TError, TData> & { queryKey: QueryKey }
}

export type MarketplaceListingControllerGetListingsQueryResult = NonNullable<Awaited<ReturnType<typeof marketplaceListingControllerGetListings>>>
export type MarketplaceListingControllerGetListingsQueryError = void

/**
 * @summary Browse active marketplace listings
 */
export const useMarketplaceListingControllerGetListings = <TData = Awaited<ReturnType<typeof marketplaceListingControllerGetListings>>, TError = void>(
 params?: MarketplaceListingControllerGetListingsParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof marketplaceListingControllerGetListings>>, TError, TData>, }

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getMarketplaceListingControllerGetListingsQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary List an owned ticket for resale
 */
export const marketplaceListingControllerCreateListing = (
    createListingDto: CreateListingDto,
 ) => {
      
      
      return clientInstance<void>(
      {url: `/marketplace/listings`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createListingDto
    },
      );
    }
  


export const getMarketplaceListingControllerCreateListingMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof marketplaceListingControllerCreateListing>>, TError,{data: CreateListingDto}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof marketplaceListingControllerCreateListing>>, TError,{data: CreateListingDto}, TContext> => {
const {mutation: mutationOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof marketplaceListingControllerCreateListing>>, {data: CreateListingDto}> = (props) => {
          const {data} = props ?? {};

          return  marketplaceListingControllerCreateListing(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type MarketplaceListingControllerCreateListingMutationResult = NonNullable<Awaited<ReturnType<typeof marketplaceListingControllerCreateListing>>>
    export type MarketplaceListingControllerCreateListingMutationBody = CreateListingDto
    export type MarketplaceListingControllerCreateListingMutationError = void

    /**
 * @summary List an owned ticket for resale
 */
export const useMarketplaceListingControllerCreateListing = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof marketplaceListingControllerCreateListing>>, TError,{data: CreateListingDto}, TContext>, }
): UseMutationResult<
        Awaited<ReturnType<typeof marketplaceListingControllerCreateListing>>,
        TError,
        {data: CreateListingDto},
        TContext
      > => {

      const mutationOptions = getMarketplaceListingControllerCreateListingMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * @summary List an owned ticket for resale
 */
export const marketplaceListingControllerCreateListing = (
    createListingDto: CreateListingDto,
 ) => {
      
      
      return clientInstance<void>(
      {url: `/marketplace/listings`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createListingDto
    },
      );
    }
  


export const getMarketplaceListingControllerCreateListingMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof marketplaceListingControllerCreateListing>>, TError,{data: CreateListingDto}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof marketplaceListingControllerCreateListing>>, TError,{data: CreateListingDto}, TContext> => {
const {mutation: mutationOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof marketplaceListingControllerCreateListing>>, {data: CreateListingDto}> = (props) => {
          const {data} = props ?? {};

          return  marketplaceListingControllerCreateListing(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type MarketplaceListingControllerCreateListingMutationResult = NonNullable<Awaited<ReturnType<typeof marketplaceListingControllerCreateListing>>>
    export type MarketplaceListingControllerCreateListingMutationBody = CreateListingDto
    export type MarketplaceListingControllerCreateListingMutationError = void

    /**
 * @summary List an owned ticket for resale
 */
export const useMarketplaceListingControllerCreateListing = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof marketplaceListingControllerCreateListing>>, TError,{data: CreateListingDto}, TContext>, }
): UseMutationResult<
        Awaited<ReturnType<typeof marketplaceListingControllerCreateListing>>,
        TError,
        {data: CreateListingDto},
        TContext
      > => {

      const mutationOptions = getMarketplaceListingControllerCreateListingMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * @summary Get the authenticated user's own listings
 */
export const marketplaceListingControllerGetMyListings = (
    
 signal?: AbortSignal
) => {
      
      
      return clientInstance<void>(
      {url: `/marketplace/listings/my`, method: 'GET', signal
    },
      );
    }
  

export const getMarketplaceListingControllerGetMyListingsQueryKey = () => {
    return [`/marketplace/listings/my`] as const;
    }

    
export const getMarketplaceListingControllerGetMyListingsQueryOptions = <TData = Awaited<ReturnType<typeof marketplaceListingControllerGetMyListings>>, TError = void>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof marketplaceListingControllerGetMyListings>>, TError, TData>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getMarketplaceListingControllerGetMyListingsQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof marketplaceListingControllerGetMyListings>>> = ({ signal }) => marketplaceListingControllerGetMyListings(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof marketplaceListingControllerGetMyListings>>, TError, TData> & { queryKey: QueryKey }
}

export type MarketplaceListingControllerGetMyListingsQueryResult = NonNullable<Awaited<ReturnType<typeof marketplaceListingControllerGetMyListings>>>
export type MarketplaceListingControllerGetMyListingsQueryError = void

/**
 * @summary Get the authenticated user's own listings
 */
export const useMarketplaceListingControllerGetMyListings = <TData = Awaited<ReturnType<typeof marketplaceListingControllerGetMyListings>>, TError = void>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof marketplaceListingControllerGetMyListings>>, TError, TData>, }

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getMarketplaceListingControllerGetMyListingsQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Get the authenticated user's own listings
 */
export const marketplaceListingControllerGetMyListings = (
    
 signal?: AbortSignal
) => {
      
      
      return clientInstance<void>(
      {url: `/marketplace/listings/my`, method: 'GET', signal
    },
      );
    }
  

export const getMarketplaceListingControllerGetMyListingsQueryKey = () => {
    return [`/marketplace/listings/my`] as const;
    }

    
export const getMarketplaceListingControllerGetMyListingsQueryOptions = <TData = Awaited<ReturnType<typeof marketplaceListingControllerGetMyListings>>, TError = void>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof marketplaceListingControllerGetMyListings>>, TError, TData>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getMarketplaceListingControllerGetMyListingsQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof marketplaceListingControllerGetMyListings>>> = ({ signal }) => marketplaceListingControllerGetMyListings(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof marketplaceListingControllerGetMyListings>>, TError, TData> & { queryKey: QueryKey }
}

export type MarketplaceListingControllerGetMyListingsQueryResult = NonNullable<Awaited<ReturnType<typeof marketplaceListingControllerGetMyListings>>>
export type MarketplaceListingControllerGetMyListingsQueryError = void

/**
 * @summary Get the authenticated user's own listings
 */
export const useMarketplaceListingControllerGetMyListings = <TData = Awaited<ReturnType<typeof marketplaceListingControllerGetMyListings>>, TError = void>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof marketplaceListingControllerGetMyListings>>, TError, TData>, }

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getMarketplaceListingControllerGetMyListingsQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Get a single marketplace listing by id
 */
export const marketplaceListingControllerGetListing = (
    id: number,
 signal?: AbortSignal
) => {
      
      
      return clientInstance<void>(
      {url: `/marketplace/listings/${id}`, method: 'GET', signal
    },
      );
    }
  

export const getMarketplaceListingControllerGetListingQueryKey = (id: number,) => {
    return [`/marketplace/listings/${id}`] as const;
    }

    
export const getMarketplaceListingControllerGetListingQueryOptions = <TData = Awaited<ReturnType<typeof marketplaceListingControllerGetListing>>, TError = void>(id: number, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof marketplaceListingControllerGetListing>>, TError, TData>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getMarketplaceListingControllerGetListingQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof marketplaceListingControllerGetListing>>> = ({ signal }) => marketplaceListingControllerGetListing(id, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof marketplaceListingControllerGetListing>>, TError, TData> & { queryKey: QueryKey }
}

export type MarketplaceListingControllerGetListingQueryResult = NonNullable<Awaited<ReturnType<typeof marketplaceListingControllerGetListing>>>
export type MarketplaceListingControllerGetListingQueryError = void

/**
 * @summary Get a single marketplace listing by id
 */
export const useMarketplaceListingControllerGetListing = <TData = Awaited<ReturnType<typeof marketplaceListingControllerGetListing>>, TError = void>(
 id: number, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof marketplaceListingControllerGetListing>>, TError, TData>, }

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getMarketplaceListingControllerGetListingQueryOptions(id,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Get a single marketplace listing by id
 */
export const marketplaceListingControllerGetListing = (
    id: number,
 signal?: AbortSignal
) => {
      
      
      return clientInstance<void>(
      {url: `/marketplace/listings/${id}`, method: 'GET', signal
    },
      );
    }
  

export const getMarketplaceListingControllerGetListingQueryKey = (id: number,) => {
    return [`/marketplace/listings/${id}`] as const;
    }

    
export const getMarketplaceListingControllerGetListingQueryOptions = <TData = Awaited<ReturnType<typeof marketplaceListingControllerGetListing>>, TError = void>(id: number, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof marketplaceListingControllerGetListing>>, TError, TData>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getMarketplaceListingControllerGetListingQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof marketplaceListingControllerGetListing>>> = ({ signal }) => marketplaceListingControllerGetListing(id, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof marketplaceListingControllerGetListing>>, TError, TData> & { queryKey: QueryKey }
}

export type MarketplaceListingControllerGetListingQueryResult = NonNullable<Awaited<ReturnType<typeof marketplaceListingControllerGetListing>>>
export type MarketplaceListingControllerGetListingQueryError = void

/**
 * @summary Get a single marketplace listing by id
 */
export const useMarketplaceListingControllerGetListing = <TData = Awaited<ReturnType<typeof marketplaceListingControllerGetListing>>, TError = void>(
 id: number, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof marketplaceListingControllerGetListing>>, TError, TData>, }

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getMarketplaceListingControllerGetListingQueryOptions(id,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Cancel an active listing (seller only). Ticket returned to seller.
 */
export const marketplaceListingControllerCancelListing = (
    id: number,
 ) => {
      
      
      return clientInstance<MarketplaceListingControllerCancelListing200>(
      {url: `/marketplace/listings/${id}`, method: 'DELETE'
    },
      );
    }
  


export const getMarketplaceListingControllerCancelListingMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof marketplaceListingControllerCancelListing>>, TError,{id: number}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof marketplaceListingControllerCancelListing>>, TError,{id: number}, TContext> => {
const {mutation: mutationOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof marketplaceListingControllerCancelListing>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  marketplaceListingControllerCancelListing(id,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type MarketplaceListingControllerCancelListingMutationResult = NonNullable<Awaited<ReturnType<typeof marketplaceListingControllerCancelListing>>>
    
    export type MarketplaceListingControllerCancelListingMutationError = void

    /**
 * @summary Cancel an active listing (seller only). Ticket returned to seller.
 */
export const useMarketplaceListingControllerCancelListing = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof marketplaceListingControllerCancelListing>>, TError,{id: number}, TContext>, }
): UseMutationResult<
        Awaited<ReturnType<typeof marketplaceListingControllerCancelListing>>,
        TError,
        {id: number},
        TContext
      > => {

      const mutationOptions = getMarketplaceListingControllerCancelListingMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * @summary Cancel an active listing (seller only). Ticket returned to seller.
 */
export const marketplaceListingControllerCancelListing = (
    id: number,
 ) => {
      
      
      return clientInstance<MarketplaceListingControllerCancelListing200>(
      {url: `/marketplace/listings/${id}`, method: 'DELETE'
    },
      );
    }
  


export const getMarketplaceListingControllerCancelListingMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof marketplaceListingControllerCancelListing>>, TError,{id: number}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof marketplaceListingControllerCancelListing>>, TError,{id: number}, TContext> => {
const {mutation: mutationOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof marketplaceListingControllerCancelListing>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  marketplaceListingControllerCancelListing(id,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type MarketplaceListingControllerCancelListingMutationResult = NonNullable<Awaited<ReturnType<typeof marketplaceListingControllerCancelListing>>>
    
    export type MarketplaceListingControllerCancelListingMutationError = void

    /**
 * @summary Cancel an active listing (seller only). Ticket returned to seller.
 */
export const useMarketplaceListingControllerCancelListing = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof marketplaceListingControllerCancelListing>>, TError,{id: number}, TContext>, }
): UseMutationResult<
        Awaited<ReturnType<typeof marketplaceListingControllerCancelListing>>,
        TError,
        {id: number},
        TContext
      > => {

      const mutationOptions = getMarketplaceListingControllerCancelListingMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * @summary Reserve a listing exclusively before payment (15 min hold)
 */
export const marketplaceCheckoutControllerHoldListing = (
    listingId: number,
 ) => {
      
      
      return clientInstance<MarketplaceCheckoutControllerHoldListing200>(
      {url: `/marketplace/hold/${listingId}`, method: 'POST'
    },
      );
    }
  


export const getMarketplaceCheckoutControllerHoldListingMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof marketplaceCheckoutControllerHoldListing>>, TError,{listingId: number}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof marketplaceCheckoutControllerHoldListing>>, TError,{listingId: number}, TContext> => {
const {mutation: mutationOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof marketplaceCheckoutControllerHoldListing>>, {listingId: number}> = (props) => {
          const {listingId} = props ?? {};

          return  marketplaceCheckoutControllerHoldListing(listingId,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type MarketplaceCheckoutControllerHoldListingMutationResult = NonNullable<Awaited<ReturnType<typeof marketplaceCheckoutControllerHoldListing>>>
    
    export type MarketplaceCheckoutControllerHoldListingMutationError = void

    /**
 * @summary Reserve a listing exclusively before payment (15 min hold)
 */
export const useMarketplaceCheckoutControllerHoldListing = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof marketplaceCheckoutControllerHoldListing>>, TError,{listingId: number}, TContext>, }
): UseMutationResult<
        Awaited<ReturnType<typeof marketplaceCheckoutControllerHoldListing>>,
        TError,
        {listingId: number},
        TContext
      > => {

      const mutationOptions = getMarketplaceCheckoutControllerHoldListingMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * @summary Reserve a listing exclusively before payment (15 min hold)
 */
export const marketplaceCheckoutControllerHoldListing = (
    listingId: number,
 ) => {
      
      
      return clientInstance<MarketplaceCheckoutControllerHoldListing200>(
      {url: `/marketplace/hold/${listingId}`, method: 'POST'
    },
      );
    }
  


export const getMarketplaceCheckoutControllerHoldListingMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof marketplaceCheckoutControllerHoldListing>>, TError,{listingId: number}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof marketplaceCheckoutControllerHoldListing>>, TError,{listingId: number}, TContext> => {
const {mutation: mutationOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof marketplaceCheckoutControllerHoldListing>>, {listingId: number}> = (props) => {
          const {listingId} = props ?? {};

          return  marketplaceCheckoutControllerHoldListing(listingId,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type MarketplaceCheckoutControllerHoldListingMutationResult = NonNullable<Awaited<ReturnType<typeof marketplaceCheckoutControllerHoldListing>>>
    
    export type MarketplaceCheckoutControllerHoldListingMutationError = void

    /**
 * @summary Reserve a listing exclusively before payment (15 min hold)
 */
export const useMarketplaceCheckoutControllerHoldListing = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof marketplaceCheckoutControllerHoldListing>>, TError,{listingId: number}, TContext>, }
): UseMutationResult<
        Awaited<ReturnType<typeof marketplaceCheckoutControllerHoldListing>>,
        TError,
        {listingId: number},
        TContext
      > => {

      const mutationOptions = getMarketplaceCheckoutControllerHoldListingMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * @summary Get the fee breakdown for a listing before purchasing
 */
export const marketplaceCheckoutControllerGetFeePreview = (
    listingId: number,
 signal?: AbortSignal
) => {
      
      
      return clientInstance<MarketplaceCheckoutControllerGetFeePreview200>(
      {url: `/marketplace/listings/${listingId}/fee-preview`, method: 'GET', signal
    },
      );
    }
  

export const getMarketplaceCheckoutControllerGetFeePreviewQueryKey = (listingId: number,) => {
    return [`/marketplace/listings/${listingId}/fee-preview`] as const;
    }

    
export const getMarketplaceCheckoutControllerGetFeePreviewQueryOptions = <TData = Awaited<ReturnType<typeof marketplaceCheckoutControllerGetFeePreview>>, TError = void>(listingId: number, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof marketplaceCheckoutControllerGetFeePreview>>, TError, TData>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getMarketplaceCheckoutControllerGetFeePreviewQueryKey(listingId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof marketplaceCheckoutControllerGetFeePreview>>> = ({ signal }) => marketplaceCheckoutControllerGetFeePreview(listingId, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(listingId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof marketplaceCheckoutControllerGetFeePreview>>, TError, TData> & { queryKey: QueryKey }
}

export type MarketplaceCheckoutControllerGetFeePreviewQueryResult = NonNullable<Awaited<ReturnType<typeof marketplaceCheckoutControllerGetFeePreview>>>
export type MarketplaceCheckoutControllerGetFeePreviewQueryError = void

/**
 * @summary Get the fee breakdown for a listing before purchasing
 */
export const useMarketplaceCheckoutControllerGetFeePreview = <TData = Awaited<ReturnType<typeof marketplaceCheckoutControllerGetFeePreview>>, TError = void>(
 listingId: number, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof marketplaceCheckoutControllerGetFeePreview>>, TError, TData>, }

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getMarketplaceCheckoutControllerGetFeePreviewQueryOptions(listingId,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Get the fee breakdown for a listing before purchasing
 */
export const marketplaceCheckoutControllerGetFeePreview = (
    listingId: number,
 signal?: AbortSignal
) => {
      
      
      return clientInstance<MarketplaceCheckoutControllerGetFeePreview200>(
      {url: `/marketplace/listings/${listingId}/fee-preview`, method: 'GET', signal
    },
      );
    }
  

export const getMarketplaceCheckoutControllerGetFeePreviewQueryKey = (listingId: number,) => {
    return [`/marketplace/listings/${listingId}/fee-preview`] as const;
    }

    
export const getMarketplaceCheckoutControllerGetFeePreviewQueryOptions = <TData = Awaited<ReturnType<typeof marketplaceCheckoutControllerGetFeePreview>>, TError = void>(listingId: number, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof marketplaceCheckoutControllerGetFeePreview>>, TError, TData>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getMarketplaceCheckoutControllerGetFeePreviewQueryKey(listingId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof marketplaceCheckoutControllerGetFeePreview>>> = ({ signal }) => marketplaceCheckoutControllerGetFeePreview(listingId, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(listingId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof marketplaceCheckoutControllerGetFeePreview>>, TError, TData> & { queryKey: QueryKey }
}

export type MarketplaceCheckoutControllerGetFeePreviewQueryResult = NonNullable<Awaited<ReturnType<typeof marketplaceCheckoutControllerGetFeePreview>>>
export type MarketplaceCheckoutControllerGetFeePreviewQueryError = void

/**
 * @summary Get the fee breakdown for a listing before purchasing
 */
export const useMarketplaceCheckoutControllerGetFeePreview = <TData = Awaited<ReturnType<typeof marketplaceCheckoutControllerGetFeePreview>>, TError = void>(
 listingId: number, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof marketplaceCheckoutControllerGetFeePreview>>, TError, TData>, }

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getMarketplaceCheckoutControllerGetFeePreviewQueryOptions(listingId,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Complete a marketplace ticket purchase (atomic: payment + ticket transfer + seller credit)
 */
export const marketplaceCheckoutControllerConfirmPurchase = (
    confirmMarketplacePurchaseDto: ConfirmMarketplacePurchaseDto,
 ) => {
      
      
      return clientInstance<MarketplaceCheckoutControllerConfirmPurchase200>(
      {url: `/marketplace/checkout/confirm`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: confirmMarketplacePurchaseDto
    },
      );
    }
  


export const getMarketplaceCheckoutControllerConfirmPurchaseMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof marketplaceCheckoutControllerConfirmPurchase>>, TError,{data: ConfirmMarketplacePurchaseDto}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof marketplaceCheckoutControllerConfirmPurchase>>, TError,{data: ConfirmMarketplacePurchaseDto}, TContext> => {
const {mutation: mutationOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof marketplaceCheckoutControllerConfirmPurchase>>, {data: ConfirmMarketplacePurchaseDto}> = (props) => {
          const {data} = props ?? {};

          return  marketplaceCheckoutControllerConfirmPurchase(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type MarketplaceCheckoutControllerConfirmPurchaseMutationResult = NonNullable<Awaited<ReturnType<typeof marketplaceCheckoutControllerConfirmPurchase>>>
    export type MarketplaceCheckoutControllerConfirmPurchaseMutationBody = ConfirmMarketplacePurchaseDto
    export type MarketplaceCheckoutControllerConfirmPurchaseMutationError = void

    /**
 * @summary Complete a marketplace ticket purchase (atomic: payment + ticket transfer + seller credit)
 */
export const useMarketplaceCheckoutControllerConfirmPurchase = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof marketplaceCheckoutControllerConfirmPurchase>>, TError,{data: ConfirmMarketplacePurchaseDto}, TContext>, }
): UseMutationResult<
        Awaited<ReturnType<typeof marketplaceCheckoutControllerConfirmPurchase>>,
        TError,
        {data: ConfirmMarketplacePurchaseDto},
        TContext
      > => {

      const mutationOptions = getMarketplaceCheckoutControllerConfirmPurchaseMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * @summary Complete a marketplace ticket purchase (atomic: payment + ticket transfer + seller credit)
 */
export const marketplaceCheckoutControllerConfirmPurchase = (
    confirmMarketplacePurchaseDto: ConfirmMarketplacePurchaseDto,
 ) => {
      
      
      return clientInstance<MarketplaceCheckoutControllerConfirmPurchase200>(
      {url: `/marketplace/checkout/confirm`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: confirmMarketplacePurchaseDto
    },
      );
    }
  


export const getMarketplaceCheckoutControllerConfirmPurchaseMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof marketplaceCheckoutControllerConfirmPurchase>>, TError,{data: ConfirmMarketplacePurchaseDto}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof marketplaceCheckoutControllerConfirmPurchase>>, TError,{data: ConfirmMarketplacePurchaseDto}, TContext> => {
const {mutation: mutationOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof marketplaceCheckoutControllerConfirmPurchase>>, {data: ConfirmMarketplacePurchaseDto}> = (props) => {
          const {data} = props ?? {};

          return  marketplaceCheckoutControllerConfirmPurchase(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type MarketplaceCheckoutControllerConfirmPurchaseMutationResult = NonNullable<Awaited<ReturnType<typeof marketplaceCheckoutControllerConfirmPurchase>>>
    export type MarketplaceCheckoutControllerConfirmPurchaseMutationBody = ConfirmMarketplacePurchaseDto
    export type MarketplaceCheckoutControllerConfirmPurchaseMutationError = void

    /**
 * @summary Complete a marketplace ticket purchase (atomic: payment + ticket transfer + seller credit)
 */
export const useMarketplaceCheckoutControllerConfirmPurchase = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof marketplaceCheckoutControllerConfirmPurchase>>, TError,{data: ConfirmMarketplacePurchaseDto}, TContext>, }
): UseMutationResult<
        Awaited<ReturnType<typeof marketplaceCheckoutControllerConfirmPurchase>>,
        TError,
        {data: ConfirmMarketplacePurchaseDto},
        TContext
      > => {

      const mutationOptions = getMarketplaceCheckoutControllerConfirmPurchaseMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * @summary Update a platform config value (admin only)
 */
export const marketplaceCheckoutControllerUpdateConfig = (
    key: string,
    updatePlatformConfigDto: UpdatePlatformConfigDto,
 ) => {
      
      
      return clientInstance<void>(
      {url: `/marketplace/config/${key}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: updatePlatformConfigDto
    },
      );
    }
  


export const getMarketplaceCheckoutControllerUpdateConfigMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof marketplaceCheckoutControllerUpdateConfig>>, TError,{key: string;data: UpdatePlatformConfigDto}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof marketplaceCheckoutControllerUpdateConfig>>, TError,{key: string;data: UpdatePlatformConfigDto}, TContext> => {
const {mutation: mutationOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof marketplaceCheckoutControllerUpdateConfig>>, {key: string;data: UpdatePlatformConfigDto}> = (props) => {
          const {key,data} = props ?? {};

          return  marketplaceCheckoutControllerUpdateConfig(key,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type MarketplaceCheckoutControllerUpdateConfigMutationResult = NonNullable<Awaited<ReturnType<typeof marketplaceCheckoutControllerUpdateConfig>>>
    export type MarketplaceCheckoutControllerUpdateConfigMutationBody = UpdatePlatformConfigDto
    export type MarketplaceCheckoutControllerUpdateConfigMutationError = void

    /**
 * @summary Update a platform config value (admin only)
 */
export const useMarketplaceCheckoutControllerUpdateConfig = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof marketplaceCheckoutControllerUpdateConfig>>, TError,{key: string;data: UpdatePlatformConfigDto}, TContext>, }
): UseMutationResult<
        Awaited<ReturnType<typeof marketplaceCheckoutControllerUpdateConfig>>,
        TError,
        {key: string;data: UpdatePlatformConfigDto},
        TContext
      > => {

      const mutationOptions = getMarketplaceCheckoutControllerUpdateConfigMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * @summary Update a platform config value (admin only)
 */
export const marketplaceCheckoutControllerUpdateConfig = (
    key: string,
    updatePlatformConfigDto: UpdatePlatformConfigDto,
 ) => {
      
      
      return clientInstance<void>(
      {url: `/marketplace/config/${key}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: updatePlatformConfigDto
    },
      );
    }
  


export const getMarketplaceCheckoutControllerUpdateConfigMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof marketplaceCheckoutControllerUpdateConfig>>, TError,{key: string;data: UpdatePlatformConfigDto}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof marketplaceCheckoutControllerUpdateConfig>>, TError,{key: string;data: UpdatePlatformConfigDto}, TContext> => {
const {mutation: mutationOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof marketplaceCheckoutControllerUpdateConfig>>, {key: string;data: UpdatePlatformConfigDto}> = (props) => {
          const {key,data} = props ?? {};

          return  marketplaceCheckoutControllerUpdateConfig(key,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type MarketplaceCheckoutControllerUpdateConfigMutationResult = NonNullable<Awaited<ReturnType<typeof marketplaceCheckoutControllerUpdateConfig>>>
    export type MarketplaceCheckoutControllerUpdateConfigMutationBody = UpdatePlatformConfigDto
    export type MarketplaceCheckoutControllerUpdateConfigMutationError = void

    /**
 * @summary Update a platform config value (admin only)
 */
export const useMarketplaceCheckoutControllerUpdateConfig = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof marketplaceCheckoutControllerUpdateConfig>>, TError,{key: string;data: UpdatePlatformConfigDto}, TContext>, }
): UseMutationResult<
        Awaited<ReturnType<typeof marketplaceCheckoutControllerUpdateConfig>>,
        TError,
        {key: string;data: UpdatePlatformConfigDto},
        TContext
      > => {

      const mutationOptions = getMarketplaceCheckoutControllerUpdateConfigMutationOptions(options);

      return useMutation(mutationOptions);
    }
    