/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * I Watch Football API
 * The API Docs for I Watch Football
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import { clientInstance } from '../client-instance';
/**
 * @summary Create NewsArticle
 */
export const createNewsArticle = (createNewsArticleDTO) => {
    return clientInstance({ url: `/newsArticle`, method: 'POST',
        headers: { 'Content-Type': 'application/json', },
        data: createNewsArticleDTO
    });
};
export const getCreateNewsArticleMutationOptions = (options) => {
    const { mutation: mutationOptions } = options !== null && options !== void 0 ? options : {};
    const mutationFn = (props) => {
        const { data } = props !== null && props !== void 0 ? props : {};
        return createNewsArticle(data);
    };
    return Object.assign({ mutationFn }, mutationOptions);
};
/**
* @summary Create NewsArticle
*/
export const useCreateNewsArticle = (options) => {
    const mutationOptions = getCreateNewsArticleMutationOptions(options);
    return useMutation(mutationOptions);
};
/**
* @summary Get all NewsArticles
*/
export const getAllNewsArticle = (signal) => {
    return clientInstance({ url: `/newsArticle`, method: 'GET', signal
    });
};
export const getGetAllNewsArticleQueryKey = () => {
    return [`/newsArticle`];
};
export const getGetAllNewsArticleQueryOptions = (options) => {
    var _a;
    const { query: queryOptions } = options !== null && options !== void 0 ? options : {};
    const queryKey = (_a = queryOptions === null || queryOptions === void 0 ? void 0 : queryOptions.queryKey) !== null && _a !== void 0 ? _a : getGetAllNewsArticleQueryKey();
    const queryFn = ({ signal }) => getAllNewsArticle(signal);
    return Object.assign({ queryKey, queryFn }, queryOptions);
};
/**
 * @summary Get all NewsArticles
 */
export const useGetAllNewsArticle = (options) => {
    const queryOptions = getGetAllNewsArticleQueryOptions(options);
    const query = useQuery(queryOptions);
    query.queryKey = queryOptions.queryKey;
    return query;
};
/**
 * @summary Get all NewsArticles
 */
export const getQueryNewsArticle = (params, signal) => {
    return clientInstance({ url: `/newsArticle/query`, method: 'GET',
        params, signal
    });
};
export const getGetQueryNewsArticleQueryKey = (params) => {
    return [`/newsArticle/query`, ...(params ? [params] : [])];
};
export const getGetQueryNewsArticleQueryOptions = (params, options) => {
    var _a;
    const { query: queryOptions } = options !== null && options !== void 0 ? options : {};
    const queryKey = (_a = queryOptions === null || queryOptions === void 0 ? void 0 : queryOptions.queryKey) !== null && _a !== void 0 ? _a : getGetQueryNewsArticleQueryKey(params);
    const queryFn = ({ signal }) => getQueryNewsArticle(params, signal);
    return Object.assign({ queryKey, queryFn }, queryOptions);
};
/**
 * @summary Get all NewsArticles
 */
export const useGetQueryNewsArticle = (params, options) => {
    const queryOptions = getGetQueryNewsArticleQueryOptions(params, options);
    const query = useQuery(queryOptions);
    query.queryKey = queryOptions.queryKey;
    return query;
};
/**
 * @summary Get count of NewsArticles
 */
export const getCountNewsArticle = (params, signal) => {
    return clientInstance({ url: `/newsArticle/count`, method: 'GET',
        params, signal
    });
};
export const getGetCountNewsArticleQueryKey = (params) => {
    return [`/newsArticle/count`, ...(params ? [params] : [])];
};
export const getGetCountNewsArticleQueryOptions = (params, options) => {
    var _a;
    const { query: queryOptions } = options !== null && options !== void 0 ? options : {};
    const queryKey = (_a = queryOptions === null || queryOptions === void 0 ? void 0 : queryOptions.queryKey) !== null && _a !== void 0 ? _a : getGetCountNewsArticleQueryKey(params);
    const queryFn = ({ signal }) => getCountNewsArticle(params, signal);
    return Object.assign({ queryKey, queryFn }, queryOptions);
};
/**
 * @summary Get count of NewsArticles
 */
export const useGetCountNewsArticle = (params, options) => {
    const queryOptions = getGetCountNewsArticleQueryOptions(params, options);
    const query = useQuery(queryOptions);
    query.queryKey = queryOptions.queryKey;
    return query;
};
/**
 * @summary Get one NewsArticle
 */
export const getOneNewsArticle = (id, signal) => {
    return clientInstance({ url: `/newsArticle/${id}`, method: 'GET', signal
    });
};
export const getGetOneNewsArticleQueryKey = (id) => {
    return [`/newsArticle/${id}`];
};
export const getGetOneNewsArticleQueryOptions = (id, options) => {
    var _a;
    const { query: queryOptions } = options !== null && options !== void 0 ? options : {};
    const queryKey = (_a = queryOptions === null || queryOptions === void 0 ? void 0 : queryOptions.queryKey) !== null && _a !== void 0 ? _a : getGetOneNewsArticleQueryKey(id);
    const queryFn = ({ signal }) => getOneNewsArticle(id, signal);
    return Object.assign({ queryKey, queryFn, enabled: !!(id) }, queryOptions);
};
/**
 * @summary Get one NewsArticle
 */
export const useGetOneNewsArticle = (id, options) => {
    const queryOptions = getGetOneNewsArticleQueryOptions(id, options);
    const query = useQuery(queryOptions);
    query.queryKey = queryOptions.queryKey;
    return query;
};
/**
 * @summary Update one NewsArticle
 */
export const updateOneNewsArticle = (id, newsArticle) => {
    return clientInstance({ url: `/newsArticle/${id}`, method: 'PATCH',
        headers: { 'Content-Type': 'application/json', },
        data: newsArticle
    });
};
export const getUpdateOneNewsArticleMutationOptions = (options) => {
    const { mutation: mutationOptions } = options !== null && options !== void 0 ? options : {};
    const mutationFn = (props) => {
        const { id, data } = props !== null && props !== void 0 ? props : {};
        return updateOneNewsArticle(id, data);
    };
    return Object.assign({ mutationFn }, mutationOptions);
};
/**
* @summary Update one NewsArticle
*/
export const useUpdateOneNewsArticle = (options) => {
    const mutationOptions = getUpdateOneNewsArticleMutationOptions(options);
    return useMutation(mutationOptions);
};
/**
* @summary Delete one NewsArticle
*/
export const deleteOneNewsArticle = (id) => {
    return clientInstance({ url: `/newsArticle/${id}`, method: 'DELETE'
    });
};
export const getDeleteOneNewsArticleMutationOptions = (options) => {
    const { mutation: mutationOptions } = options !== null && options !== void 0 ? options : {};
    const mutationFn = (props) => {
        const { id } = props !== null && props !== void 0 ? props : {};
        return deleteOneNewsArticle(id);
    };
    return Object.assign({ mutationFn }, mutationOptions);
};
/**
* @summary Delete one NewsArticle
*/
export const useDeleteOneNewsArticle = (options) => {
    const mutationOptions = getDeleteOneNewsArticleMutationOptions(options);
    return useMutation(mutationOptions);
};
/**
* @summary Upload a file for NewsArticle
*/
export const uploadNewsArticle = () => {
    return clientInstance({ url: `/newsArticle/upload`, method: 'POST'
    });
};
export const getUploadNewsArticleMutationOptions = (options) => {
    const { mutation: mutationOptions } = options !== null && options !== void 0 ? options : {};
    const mutationFn = () => {
        return uploadNewsArticle();
    };
    return Object.assign({ mutationFn }, mutationOptions);
};
/**
* @summary Upload a file for NewsArticle
*/
export const useUploadNewsArticle = (options) => {
    const mutationOptions = getUploadNewsArticleMutationOptions(options);
    return useMutation(mutationOptions);
};
/**
* @summary Download file related to NewsArticle
*/
export const downloadNewsArticle = (filename, signal) => {
    return clientInstance({ url: `/newsArticle/download/${filename}`, method: 'GET', signal
    });
};
export const getDownloadNewsArticleQueryKey = (filename) => {
    return [`/newsArticle/download/${filename}`];
};
export const getDownloadNewsArticleQueryOptions = (filename, options) => {
    var _a;
    const { query: queryOptions } = options !== null && options !== void 0 ? options : {};
    const queryKey = (_a = queryOptions === null || queryOptions === void 0 ? void 0 : queryOptions.queryKey) !== null && _a !== void 0 ? _a : getDownloadNewsArticleQueryKey(filename);
    const queryFn = ({ signal }) => downloadNewsArticle(filename, signal);
    return Object.assign({ queryKey, queryFn, enabled: !!(filename) }, queryOptions);
};
/**
 * @summary Download file related to NewsArticle
 */
export const useDownloadNewsArticle = (filename, options) => {
    const queryOptions = getDownloadNewsArticleQueryOptions(filename, options);
    const query = useQuery(queryOptions);
    query.queryKey = queryOptions.queryKey;
    return query;
};
//# sourceMappingURL=news-article.js.map