/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * I Watch Football API
 * The API Docs for I Watch Football
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query'
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query'
import type {
  CreatePaymentDTO,
  GetCountPaymentParams,
  GetQueryPaymentParams,
  Payment
} from './iWatchFootballAPI.schemas'
import { clientInstance } from '../client-instance';




/**
 * @summary Create Payment
 */
export const createPayment = (
    createPaymentDTO: CreatePaymentDTO,
 ) => {
      
      
      return clientInstance<Payment>(
      {url: `/payment`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createPaymentDTO
    },
      );
    }
  


export const getCreatePaymentMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createPayment>>, TError,{data: CreatePaymentDTO}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof createPayment>>, TError,{data: CreatePaymentDTO}, TContext> => {
const {mutation: mutationOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createPayment>>, {data: CreatePaymentDTO}> = (props) => {
          const {data} = props ?? {};

          return  createPayment(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreatePaymentMutationResult = NonNullable<Awaited<ReturnType<typeof createPayment>>>
    export type CreatePaymentMutationBody = CreatePaymentDTO
    export type CreatePaymentMutationError = void

    /**
 * @summary Create Payment
 */
export const useCreatePayment = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createPayment>>, TError,{data: CreatePaymentDTO}, TContext>, }
): UseMutationResult<
        Awaited<ReturnType<typeof createPayment>>,
        TError,
        {data: CreatePaymentDTO},
        TContext
      > => {

      const mutationOptions = getCreatePaymentMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * @summary Get all Payments
 */
export const getAllPayment = (
    
 signal?: AbortSignal
) => {
      
      
      return clientInstance<Payment[]>(
      {url: `/payment`, method: 'GET', signal
    },
      );
    }
  

export const getGetAllPaymentQueryKey = () => {
    return [`/payment`] as const;
    }

    
export const getGetAllPaymentQueryOptions = <TData = Awaited<ReturnType<typeof getAllPayment>>, TError = void>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getAllPayment>>, TError, TData>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAllPaymentQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAllPayment>>> = ({ signal }) => getAllPayment(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAllPayment>>, TError, TData> & { queryKey: QueryKey }
}

export type GetAllPaymentQueryResult = NonNullable<Awaited<ReturnType<typeof getAllPayment>>>
export type GetAllPaymentQueryError = void

/**
 * @summary Get all Payments
 */
export const useGetAllPayment = <TData = Awaited<ReturnType<typeof getAllPayment>>, TError = void>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getAllPayment>>, TError, TData>, }

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getGetAllPaymentQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Get all Payments
 */
export const getQueryPayment = (
    params?: GetQueryPaymentParams,
 signal?: AbortSignal
) => {
      
      
      return clientInstance<Payment[]>(
      {url: `/payment/query`, method: 'GET',
        params, signal
    },
      );
    }
  

export const getGetQueryPaymentQueryKey = (params?: GetQueryPaymentParams,) => {
    return [`/payment/query`, ...(params ? [params]: [])] as const;
    }

    
export const getGetQueryPaymentQueryOptions = <TData = Awaited<ReturnType<typeof getQueryPayment>>, TError = void>(params?: GetQueryPaymentParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getQueryPayment>>, TError, TData>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetQueryPaymentQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getQueryPayment>>> = ({ signal }) => getQueryPayment(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getQueryPayment>>, TError, TData> & { queryKey: QueryKey }
}

export type GetQueryPaymentQueryResult = NonNullable<Awaited<ReturnType<typeof getQueryPayment>>>
export type GetQueryPaymentQueryError = void

/**
 * @summary Get all Payments
 */
export const useGetQueryPayment = <TData = Awaited<ReturnType<typeof getQueryPayment>>, TError = void>(
 params?: GetQueryPaymentParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getQueryPayment>>, TError, TData>, }

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getGetQueryPaymentQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Get count of Payments
 */
export const getCountPayment = (
    params?: GetCountPaymentParams,
 signal?: AbortSignal
) => {
      
      
      return clientInstance<number>(
      {url: `/payment/count`, method: 'GET',
        params, signal
    },
      );
    }
  

export const getGetCountPaymentQueryKey = (params?: GetCountPaymentParams,) => {
    return [`/payment/count`, ...(params ? [params]: [])] as const;
    }

    
export const getGetCountPaymentQueryOptions = <TData = Awaited<ReturnType<typeof getCountPayment>>, TError = void>(params?: GetCountPaymentParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getCountPayment>>, TError, TData>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetCountPaymentQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getCountPayment>>> = ({ signal }) => getCountPayment(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getCountPayment>>, TError, TData> & { queryKey: QueryKey }
}

export type GetCountPaymentQueryResult = NonNullable<Awaited<ReturnType<typeof getCountPayment>>>
export type GetCountPaymentQueryError = void

/**
 * @summary Get count of Payments
 */
export const useGetCountPayment = <TData = Awaited<ReturnType<typeof getCountPayment>>, TError = void>(
 params?: GetCountPaymentParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getCountPayment>>, TError, TData>, }

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getGetCountPaymentQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Get one Payment
 */
export const getOnePayment = (
    id: number,
 signal?: AbortSignal
) => {
      
      
      return clientInstance<Payment>(
      {url: `/payment/${id}`, method: 'GET', signal
    },
      );
    }
  

export const getGetOnePaymentQueryKey = (id: number,) => {
    return [`/payment/${id}`] as const;
    }

    
export const getGetOnePaymentQueryOptions = <TData = Awaited<ReturnType<typeof getOnePayment>>, TError = void>(id: number, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getOnePayment>>, TError, TData>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetOnePaymentQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getOnePayment>>> = ({ signal }) => getOnePayment(id, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getOnePayment>>, TError, TData> & { queryKey: QueryKey }
}

export type GetOnePaymentQueryResult = NonNullable<Awaited<ReturnType<typeof getOnePayment>>>
export type GetOnePaymentQueryError = void

/**
 * @summary Get one Payment
 */
export const useGetOnePayment = <TData = Awaited<ReturnType<typeof getOnePayment>>, TError = void>(
 id: number, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getOnePayment>>, TError, TData>, }

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getGetOnePaymentQueryOptions(id,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Update one Payment
 */
export const updateOnePayment = (
    id: number,
    payment: Payment,
 ) => {
      
      
      return clientInstance<void>(
      {url: `/payment/${id}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: payment
    },
      );
    }
  


export const getUpdateOnePaymentMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateOnePayment>>, TError,{id: number;data: Payment}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof updateOnePayment>>, TError,{id: number;data: Payment}, TContext> => {
const {mutation: mutationOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateOnePayment>>, {id: number;data: Payment}> = (props) => {
          const {id,data} = props ?? {};

          return  updateOnePayment(id,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateOnePaymentMutationResult = NonNullable<Awaited<ReturnType<typeof updateOnePayment>>>
    export type UpdateOnePaymentMutationBody = Payment
    export type UpdateOnePaymentMutationError = void

    /**
 * @summary Update one Payment
 */
export const useUpdateOnePayment = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateOnePayment>>, TError,{id: number;data: Payment}, TContext>, }
): UseMutationResult<
        Awaited<ReturnType<typeof updateOnePayment>>,
        TError,
        {id: number;data: Payment},
        TContext
      > => {

      const mutationOptions = getUpdateOnePaymentMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * @summary Delete one Payment
 */
export const deleteOnePayment = (
    id: number,
 ) => {
      
      
      return clientInstance<void>(
      {url: `/payment/${id}`, method: 'DELETE'
    },
      );
    }
  


export const getDeleteOnePaymentMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteOnePayment>>, TError,{id: number}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof deleteOnePayment>>, TError,{id: number}, TContext> => {
const {mutation: mutationOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteOnePayment>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  deleteOnePayment(id,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteOnePaymentMutationResult = NonNullable<Awaited<ReturnType<typeof deleteOnePayment>>>
    
    export type DeleteOnePaymentMutationError = void

    /**
 * @summary Delete one Payment
 */
export const useDeleteOnePayment = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteOnePayment>>, TError,{id: number}, TContext>, }
): UseMutationResult<
        Awaited<ReturnType<typeof deleteOnePayment>>,
        TError,
        {id: number},
        TContext
      > => {

      const mutationOptions = getDeleteOnePaymentMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * @summary Upload a file for Payment
 */
export const uploadPayment = (
    
 ) => {
      
      
      return clientInstance<void>(
      {url: `/payment/upload`, method: 'POST'
    },
      );
    }
  


export const getUploadPaymentMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof uploadPayment>>, TError,void, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof uploadPayment>>, TError,void, TContext> => {
const {mutation: mutationOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof uploadPayment>>, void> = () => {
          

          return  uploadPayment()
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UploadPaymentMutationResult = NonNullable<Awaited<ReturnType<typeof uploadPayment>>>
    
    export type UploadPaymentMutationError = void

    /**
 * @summary Upload a file for Payment
 */
export const useUploadPayment = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof uploadPayment>>, TError,void, TContext>, }
): UseMutationResult<
        Awaited<ReturnType<typeof uploadPayment>>,
        TError,
        void,
        TContext
      > => {

      const mutationOptions = getUploadPaymentMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * @summary Download file related to Payment
 */
export const downloadPayment = (
    filename: string,
 signal?: AbortSignal
) => {
      
      
      return clientInstance<void>(
      {url: `/payment/download/${filename}`, method: 'GET', signal
    },
      );
    }
  

export const getDownloadPaymentQueryKey = (filename: string,) => {
    return [`/payment/download/${filename}`] as const;
    }

    
export const getDownloadPaymentQueryOptions = <TData = Awaited<ReturnType<typeof downloadPayment>>, TError = void>(filename: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof downloadPayment>>, TError, TData>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getDownloadPaymentQueryKey(filename);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof downloadPayment>>> = ({ signal }) => downloadPayment(filename, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(filename), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof downloadPayment>>, TError, TData> & { queryKey: QueryKey }
}

export type DownloadPaymentQueryResult = NonNullable<Awaited<ReturnType<typeof downloadPayment>>>
export type DownloadPaymentQueryError = void

/**
 * @summary Download file related to Payment
 */
export const useDownloadPayment = <TData = Awaited<ReturnType<typeof downloadPayment>>, TError = void>(
 filename: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof downloadPayment>>, TError, TData>, }

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getDownloadPaymentQueryOptions(filename,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



