/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * I Watch Football API
 * The API Docs for I Watch Football
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import { clientInstance } from '../client-instance';
/**
 * @summary Create Player
 */
export const createPlayer = (createPlayerDTO) => {
    return clientInstance({ url: `/player`, method: 'POST',
        headers: { 'Content-Type': 'application/json', },
        data: createPlayerDTO
    });
};
export const getCreatePlayerMutationOptions = (options) => {
    const { mutation: mutationOptions } = options !== null && options !== void 0 ? options : {};
    const mutationFn = (props) => {
        const { data } = props !== null && props !== void 0 ? props : {};
        return createPlayer(data);
    };
    return Object.assign({ mutationFn }, mutationOptions);
};
/**
* @summary Create Player
*/
export const useCreatePlayer = (options) => {
    const mutationOptions = getCreatePlayerMutationOptions(options);
    return useMutation(mutationOptions);
};
/**
* @summary Get all Players
*/
export const getAllPlayer = (signal) => {
    return clientInstance({ url: `/player`, method: 'GET', signal
    });
};
export const getGetAllPlayerQueryKey = () => {
    return [`/player`];
};
export const getGetAllPlayerQueryOptions = (options) => {
    var _a;
    const { query: queryOptions } = options !== null && options !== void 0 ? options : {};
    const queryKey = (_a = queryOptions === null || queryOptions === void 0 ? void 0 : queryOptions.queryKey) !== null && _a !== void 0 ? _a : getGetAllPlayerQueryKey();
    const queryFn = ({ signal }) => getAllPlayer(signal);
    return Object.assign({ queryKey, queryFn }, queryOptions);
};
/**
 * @summary Get all Players
 */
export const useGetAllPlayer = (options) => {
    const queryOptions = getGetAllPlayerQueryOptions(options);
    const query = useQuery(queryOptions);
    query.queryKey = queryOptions.queryKey;
    return query;
};
/**
 * @summary Get all Players
 */
export const getQueryPlayer = (params, signal) => {
    return clientInstance({ url: `/player/query`, method: 'GET',
        params, signal
    });
};
export const getGetQueryPlayerQueryKey = (params) => {
    return [`/player/query`, ...(params ? [params] : [])];
};
export const getGetQueryPlayerQueryOptions = (params, options) => {
    var _a;
    const { query: queryOptions } = options !== null && options !== void 0 ? options : {};
    const queryKey = (_a = queryOptions === null || queryOptions === void 0 ? void 0 : queryOptions.queryKey) !== null && _a !== void 0 ? _a : getGetQueryPlayerQueryKey(params);
    const queryFn = ({ signal }) => getQueryPlayer(params, signal);
    return Object.assign({ queryKey, queryFn }, queryOptions);
};
/**
 * @summary Get all Players
 */
export const useGetQueryPlayer = (params, options) => {
    const queryOptions = getGetQueryPlayerQueryOptions(params, options);
    const query = useQuery(queryOptions);
    query.queryKey = queryOptions.queryKey;
    return query;
};
/**
 * @summary Get count of Players
 */
export const getCountPlayer = (params, signal) => {
    return clientInstance({ url: `/player/count`, method: 'GET',
        params, signal
    });
};
export const getGetCountPlayerQueryKey = (params) => {
    return [`/player/count`, ...(params ? [params] : [])];
};
export const getGetCountPlayerQueryOptions = (params, options) => {
    var _a;
    const { query: queryOptions } = options !== null && options !== void 0 ? options : {};
    const queryKey = (_a = queryOptions === null || queryOptions === void 0 ? void 0 : queryOptions.queryKey) !== null && _a !== void 0 ? _a : getGetCountPlayerQueryKey(params);
    const queryFn = ({ signal }) => getCountPlayer(params, signal);
    return Object.assign({ queryKey, queryFn }, queryOptions);
};
/**
 * @summary Get count of Players
 */
export const useGetCountPlayer = (params, options) => {
    const queryOptions = getGetCountPlayerQueryOptions(params, options);
    const query = useQuery(queryOptions);
    query.queryKey = queryOptions.queryKey;
    return query;
};
/**
 * @summary Get one Player
 */
export const getOnePlayer = (id, signal) => {
    return clientInstance({ url: `/player/${id}`, method: 'GET', signal
    });
};
export const getGetOnePlayerQueryKey = (id) => {
    return [`/player/${id}`];
};
export const getGetOnePlayerQueryOptions = (id, options) => {
    var _a;
    const { query: queryOptions } = options !== null && options !== void 0 ? options : {};
    const queryKey = (_a = queryOptions === null || queryOptions === void 0 ? void 0 : queryOptions.queryKey) !== null && _a !== void 0 ? _a : getGetOnePlayerQueryKey(id);
    const queryFn = ({ signal }) => getOnePlayer(id, signal);
    return Object.assign({ queryKey, queryFn, enabled: !!(id) }, queryOptions);
};
/**
 * @summary Get one Player
 */
export const useGetOnePlayer = (id, options) => {
    const queryOptions = getGetOnePlayerQueryOptions(id, options);
    const query = useQuery(queryOptions);
    query.queryKey = queryOptions.queryKey;
    return query;
};
/**
 * @summary Update one Player
 */
export const updateOnePlayer = (id, player) => {
    return clientInstance({ url: `/player/${id}`, method: 'PATCH',
        headers: { 'Content-Type': 'application/json', },
        data: player
    });
};
export const getUpdateOnePlayerMutationOptions = (options) => {
    const { mutation: mutationOptions } = options !== null && options !== void 0 ? options : {};
    const mutationFn = (props) => {
        const { id, data } = props !== null && props !== void 0 ? props : {};
        return updateOnePlayer(id, data);
    };
    return Object.assign({ mutationFn }, mutationOptions);
};
/**
* @summary Update one Player
*/
export const useUpdateOnePlayer = (options) => {
    const mutationOptions = getUpdateOnePlayerMutationOptions(options);
    return useMutation(mutationOptions);
};
/**
* @summary Delete one Player
*/
export const deleteOnePlayer = (id) => {
    return clientInstance({ url: `/player/${id}`, method: 'DELETE'
    });
};
export const getDeleteOnePlayerMutationOptions = (options) => {
    const { mutation: mutationOptions } = options !== null && options !== void 0 ? options : {};
    const mutationFn = (props) => {
        const { id } = props !== null && props !== void 0 ? props : {};
        return deleteOnePlayer(id);
    };
    return Object.assign({ mutationFn }, mutationOptions);
};
/**
* @summary Delete one Player
*/
export const useDeleteOnePlayer = (options) => {
    const mutationOptions = getDeleteOnePlayerMutationOptions(options);
    return useMutation(mutationOptions);
};
/**
* @summary Upload a file for Player
*/
export const uploadPlayer = () => {
    return clientInstance({ url: `/player/upload`, method: 'POST'
    });
};
export const getUploadPlayerMutationOptions = (options) => {
    const { mutation: mutationOptions } = options !== null && options !== void 0 ? options : {};
    const mutationFn = () => {
        return uploadPlayer();
    };
    return Object.assign({ mutationFn }, mutationOptions);
};
/**
* @summary Upload a file for Player
*/
export const useUploadPlayer = (options) => {
    const mutationOptions = getUploadPlayerMutationOptions(options);
    return useMutation(mutationOptions);
};
/**
* @summary Download file related to Player
*/
export const downloadPlayer = (filename, signal) => {
    return clientInstance({ url: `/player/download/${filename}`, method: 'GET', signal
    });
};
export const getDownloadPlayerQueryKey = (filename) => {
    return [`/player/download/${filename}`];
};
export const getDownloadPlayerQueryOptions = (filename, options) => {
    var _a;
    const { query: queryOptions } = options !== null && options !== void 0 ? options : {};
    const queryKey = (_a = queryOptions === null || queryOptions === void 0 ? void 0 : queryOptions.queryKey) !== null && _a !== void 0 ? _a : getDownloadPlayerQueryKey(filename);
    const queryFn = ({ signal }) => downloadPlayer(filename, signal);
    return Object.assign({ queryKey, queryFn, enabled: !!(filename) }, queryOptions);
};
/**
 * @summary Download file related to Player
 */
export const useDownloadPlayer = (filename, options) => {
    const queryOptions = getDownloadPlayerQueryOptions(filename, options);
    const query = useQuery(queryOptions);
    query.queryKey = queryOptions.queryKey;
    return query;
};
//# sourceMappingURL=player.js.map