/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * I Watch Football API
 * The API Docs for I Watch Football
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query'
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query'
import type {
  CreatePlayerLineUpDTO,
  GetCountPlayerLineUpParams,
  GetQueryPlayerLineUpParams,
  PlayerLineUp
} from './iWatchFootballAPI.schemas'
import { clientInstance } from '../client-instance';




/**
 * @summary Create PlayerLineUp
 */
export const createPlayerLineUp = (
    createPlayerLineUpDTO: CreatePlayerLineUpDTO,
 ) => {
      
      
      return clientInstance<PlayerLineUp>(
      {url: `/playerLineUp`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createPlayerLineUpDTO
    },
      );
    }
  


export const getCreatePlayerLineUpMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createPlayerLineUp>>, TError,{data: CreatePlayerLineUpDTO}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof createPlayerLineUp>>, TError,{data: CreatePlayerLineUpDTO}, TContext> => {
const {mutation: mutationOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createPlayerLineUp>>, {data: CreatePlayerLineUpDTO}> = (props) => {
          const {data} = props ?? {};

          return  createPlayerLineUp(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreatePlayerLineUpMutationResult = NonNullable<Awaited<ReturnType<typeof createPlayerLineUp>>>
    export type CreatePlayerLineUpMutationBody = CreatePlayerLineUpDTO
    export type CreatePlayerLineUpMutationError = void

    /**
 * @summary Create PlayerLineUp
 */
export const useCreatePlayerLineUp = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createPlayerLineUp>>, TError,{data: CreatePlayerLineUpDTO}, TContext>, }
): UseMutationResult<
        Awaited<ReturnType<typeof createPlayerLineUp>>,
        TError,
        {data: CreatePlayerLineUpDTO},
        TContext
      > => {

      const mutationOptions = getCreatePlayerLineUpMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * @summary Get all PlayerLineUps
 */
export const getAllPlayerLineUp = (
    
 signal?: AbortSignal
) => {
      
      
      return clientInstance<PlayerLineUp[]>(
      {url: `/playerLineUp`, method: 'GET', signal
    },
      );
    }
  

export const getGetAllPlayerLineUpQueryKey = () => {
    return [`/playerLineUp`] as const;
    }

    
export const getGetAllPlayerLineUpQueryOptions = <TData = Awaited<ReturnType<typeof getAllPlayerLineUp>>, TError = void>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getAllPlayerLineUp>>, TError, TData>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAllPlayerLineUpQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAllPlayerLineUp>>> = ({ signal }) => getAllPlayerLineUp(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAllPlayerLineUp>>, TError, TData> & { queryKey: QueryKey }
}

export type GetAllPlayerLineUpQueryResult = NonNullable<Awaited<ReturnType<typeof getAllPlayerLineUp>>>
export type GetAllPlayerLineUpQueryError = void

/**
 * @summary Get all PlayerLineUps
 */
export const useGetAllPlayerLineUp = <TData = Awaited<ReturnType<typeof getAllPlayerLineUp>>, TError = void>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getAllPlayerLineUp>>, TError, TData>, }

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getGetAllPlayerLineUpQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Get all PlayerLineUps
 */
export const getQueryPlayerLineUp = (
    params?: GetQueryPlayerLineUpParams,
 signal?: AbortSignal
) => {
      
      
      return clientInstance<PlayerLineUp[]>(
      {url: `/playerLineUp/query`, method: 'GET',
        params, signal
    },
      );
    }
  

export const getGetQueryPlayerLineUpQueryKey = (params?: GetQueryPlayerLineUpParams,) => {
    return [`/playerLineUp/query`, ...(params ? [params]: [])] as const;
    }

    
export const getGetQueryPlayerLineUpQueryOptions = <TData = Awaited<ReturnType<typeof getQueryPlayerLineUp>>, TError = void>(params?: GetQueryPlayerLineUpParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getQueryPlayerLineUp>>, TError, TData>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetQueryPlayerLineUpQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getQueryPlayerLineUp>>> = ({ signal }) => getQueryPlayerLineUp(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getQueryPlayerLineUp>>, TError, TData> & { queryKey: QueryKey }
}

export type GetQueryPlayerLineUpQueryResult = NonNullable<Awaited<ReturnType<typeof getQueryPlayerLineUp>>>
export type GetQueryPlayerLineUpQueryError = void

/**
 * @summary Get all PlayerLineUps
 */
export const useGetQueryPlayerLineUp = <TData = Awaited<ReturnType<typeof getQueryPlayerLineUp>>, TError = void>(
 params?: GetQueryPlayerLineUpParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getQueryPlayerLineUp>>, TError, TData>, }

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getGetQueryPlayerLineUpQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Get count of PlayerLineUps
 */
export const getCountPlayerLineUp = (
    params?: GetCountPlayerLineUpParams,
 signal?: AbortSignal
) => {
      
      
      return clientInstance<number>(
      {url: `/playerLineUp/count`, method: 'GET',
        params, signal
    },
      );
    }
  

export const getGetCountPlayerLineUpQueryKey = (params?: GetCountPlayerLineUpParams,) => {
    return [`/playerLineUp/count`, ...(params ? [params]: [])] as const;
    }

    
export const getGetCountPlayerLineUpQueryOptions = <TData = Awaited<ReturnType<typeof getCountPlayerLineUp>>, TError = void>(params?: GetCountPlayerLineUpParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getCountPlayerLineUp>>, TError, TData>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetCountPlayerLineUpQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getCountPlayerLineUp>>> = ({ signal }) => getCountPlayerLineUp(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getCountPlayerLineUp>>, TError, TData> & { queryKey: QueryKey }
}

export type GetCountPlayerLineUpQueryResult = NonNullable<Awaited<ReturnType<typeof getCountPlayerLineUp>>>
export type GetCountPlayerLineUpQueryError = void

/**
 * @summary Get count of PlayerLineUps
 */
export const useGetCountPlayerLineUp = <TData = Awaited<ReturnType<typeof getCountPlayerLineUp>>, TError = void>(
 params?: GetCountPlayerLineUpParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getCountPlayerLineUp>>, TError, TData>, }

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getGetCountPlayerLineUpQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Get one PlayerLineUp
 */
export const getOnePlayerLineUp = (
    id: number,
 signal?: AbortSignal
) => {
      
      
      return clientInstance<PlayerLineUp>(
      {url: `/playerLineUp/${id}`, method: 'GET', signal
    },
      );
    }
  

export const getGetOnePlayerLineUpQueryKey = (id: number,) => {
    return [`/playerLineUp/${id}`] as const;
    }

    
export const getGetOnePlayerLineUpQueryOptions = <TData = Awaited<ReturnType<typeof getOnePlayerLineUp>>, TError = void>(id: number, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getOnePlayerLineUp>>, TError, TData>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetOnePlayerLineUpQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getOnePlayerLineUp>>> = ({ signal }) => getOnePlayerLineUp(id, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getOnePlayerLineUp>>, TError, TData> & { queryKey: QueryKey }
}

export type GetOnePlayerLineUpQueryResult = NonNullable<Awaited<ReturnType<typeof getOnePlayerLineUp>>>
export type GetOnePlayerLineUpQueryError = void

/**
 * @summary Get one PlayerLineUp
 */
export const useGetOnePlayerLineUp = <TData = Awaited<ReturnType<typeof getOnePlayerLineUp>>, TError = void>(
 id: number, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getOnePlayerLineUp>>, TError, TData>, }

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getGetOnePlayerLineUpQueryOptions(id,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Update one PlayerLineUp
 */
export const updateOnePlayerLineUp = (
    id: number,
    playerLineUp: PlayerLineUp,
 ) => {
      
      
      return clientInstance<void>(
      {url: `/playerLineUp/${id}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: playerLineUp
    },
      );
    }
  


export const getUpdateOnePlayerLineUpMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateOnePlayerLineUp>>, TError,{id: number;data: PlayerLineUp}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof updateOnePlayerLineUp>>, TError,{id: number;data: PlayerLineUp}, TContext> => {
const {mutation: mutationOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateOnePlayerLineUp>>, {id: number;data: PlayerLineUp}> = (props) => {
          const {id,data} = props ?? {};

          return  updateOnePlayerLineUp(id,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateOnePlayerLineUpMutationResult = NonNullable<Awaited<ReturnType<typeof updateOnePlayerLineUp>>>
    export type UpdateOnePlayerLineUpMutationBody = PlayerLineUp
    export type UpdateOnePlayerLineUpMutationError = void

    /**
 * @summary Update one PlayerLineUp
 */
export const useUpdateOnePlayerLineUp = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateOnePlayerLineUp>>, TError,{id: number;data: PlayerLineUp}, TContext>, }
): UseMutationResult<
        Awaited<ReturnType<typeof updateOnePlayerLineUp>>,
        TError,
        {id: number;data: PlayerLineUp},
        TContext
      > => {

      const mutationOptions = getUpdateOnePlayerLineUpMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * @summary Delete one PlayerLineUp
 */
export const deleteOnePlayerLineUp = (
    id: number,
 ) => {
      
      
      return clientInstance<void>(
      {url: `/playerLineUp/${id}`, method: 'DELETE'
    },
      );
    }
  


export const getDeleteOnePlayerLineUpMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteOnePlayerLineUp>>, TError,{id: number}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof deleteOnePlayerLineUp>>, TError,{id: number}, TContext> => {
const {mutation: mutationOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteOnePlayerLineUp>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  deleteOnePlayerLineUp(id,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteOnePlayerLineUpMutationResult = NonNullable<Awaited<ReturnType<typeof deleteOnePlayerLineUp>>>
    
    export type DeleteOnePlayerLineUpMutationError = void

    /**
 * @summary Delete one PlayerLineUp
 */
export const useDeleteOnePlayerLineUp = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteOnePlayerLineUp>>, TError,{id: number}, TContext>, }
): UseMutationResult<
        Awaited<ReturnType<typeof deleteOnePlayerLineUp>>,
        TError,
        {id: number},
        TContext
      > => {

      const mutationOptions = getDeleteOnePlayerLineUpMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * @summary Upload a file for PlayerLineUp
 */
export const uploadPlayerLineUp = (
    
 ) => {
      
      
      return clientInstance<void>(
      {url: `/playerLineUp/upload`, method: 'POST'
    },
      );
    }
  


export const getUploadPlayerLineUpMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof uploadPlayerLineUp>>, TError,void, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof uploadPlayerLineUp>>, TError,void, TContext> => {
const {mutation: mutationOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof uploadPlayerLineUp>>, void> = () => {
          

          return  uploadPlayerLineUp()
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UploadPlayerLineUpMutationResult = NonNullable<Awaited<ReturnType<typeof uploadPlayerLineUp>>>
    
    export type UploadPlayerLineUpMutationError = void

    /**
 * @summary Upload a file for PlayerLineUp
 */
export const useUploadPlayerLineUp = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof uploadPlayerLineUp>>, TError,void, TContext>, }
): UseMutationResult<
        Awaited<ReturnType<typeof uploadPlayerLineUp>>,
        TError,
        void,
        TContext
      > => {

      const mutationOptions = getUploadPlayerLineUpMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * @summary Download file related to PlayerLineUp
 */
export const downloadPlayerLineUp = (
    filename: string,
 signal?: AbortSignal
) => {
      
      
      return clientInstance<void>(
      {url: `/playerLineUp/download/${filename}`, method: 'GET', signal
    },
      );
    }
  

export const getDownloadPlayerLineUpQueryKey = (filename: string,) => {
    return [`/playerLineUp/download/${filename}`] as const;
    }

    
export const getDownloadPlayerLineUpQueryOptions = <TData = Awaited<ReturnType<typeof downloadPlayerLineUp>>, TError = void>(filename: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof downloadPlayerLineUp>>, TError, TData>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getDownloadPlayerLineUpQueryKey(filename);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof downloadPlayerLineUp>>> = ({ signal }) => downloadPlayerLineUp(filename, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(filename), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof downloadPlayerLineUp>>, TError, TData> & { queryKey: QueryKey }
}

export type DownloadPlayerLineUpQueryResult = NonNullable<Awaited<ReturnType<typeof downloadPlayerLineUp>>>
export type DownloadPlayerLineUpQueryError = void

/**
 * @summary Download file related to PlayerLineUp
 */
export const useDownloadPlayerLineUp = <TData = Awaited<ReturnType<typeof downloadPlayerLineUp>>, TError = void>(
 filename: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof downloadPlayerLineUp>>, TError, TData>, }

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getDownloadPlayerLineUpQueryOptions(filename,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



