/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * I Watch Football API
 * The API Docs for I Watch Football
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import { clientInstance } from '../client-instance';
/**
 * @summary Create PlayerLineUp
 */
export const createPlayerLineUp = (createPlayerLineUpDTO) => {
    return clientInstance({ url: `/playerLineUp`, method: 'POST',
        headers: { 'Content-Type': 'application/json', },
        data: createPlayerLineUpDTO
    });
};
export const getCreatePlayerLineUpMutationOptions = (options) => {
    const { mutation: mutationOptions } = options !== null && options !== void 0 ? options : {};
    const mutationFn = (props) => {
        const { data } = props !== null && props !== void 0 ? props : {};
        return createPlayerLineUp(data);
    };
    return Object.assign({ mutationFn }, mutationOptions);
};
/**
* @summary Create PlayerLineUp
*/
export const useCreatePlayerLineUp = (options) => {
    const mutationOptions = getCreatePlayerLineUpMutationOptions(options);
    return useMutation(mutationOptions);
};
/**
* @summary Get all PlayerLineUps
*/
export const getAllPlayerLineUp = (signal) => {
    return clientInstance({ url: `/playerLineUp`, method: 'GET', signal
    });
};
export const getGetAllPlayerLineUpQueryKey = () => {
    return [`/playerLineUp`];
};
export const getGetAllPlayerLineUpQueryOptions = (options) => {
    var _a;
    const { query: queryOptions } = options !== null && options !== void 0 ? options : {};
    const queryKey = (_a = queryOptions === null || queryOptions === void 0 ? void 0 : queryOptions.queryKey) !== null && _a !== void 0 ? _a : getGetAllPlayerLineUpQueryKey();
    const queryFn = ({ signal }) => getAllPlayerLineUp(signal);
    return Object.assign({ queryKey, queryFn }, queryOptions);
};
/**
 * @summary Get all PlayerLineUps
 */
export const useGetAllPlayerLineUp = (options) => {
    const queryOptions = getGetAllPlayerLineUpQueryOptions(options);
    const query = useQuery(queryOptions);
    query.queryKey = queryOptions.queryKey;
    return query;
};
/**
 * @summary Get all PlayerLineUps
 */
export const getQueryPlayerLineUp = (params, signal) => {
    return clientInstance({ url: `/playerLineUp/query`, method: 'GET',
        params, signal
    });
};
export const getGetQueryPlayerLineUpQueryKey = (params) => {
    return [`/playerLineUp/query`, ...(params ? [params] : [])];
};
export const getGetQueryPlayerLineUpQueryOptions = (params, options) => {
    var _a;
    const { query: queryOptions } = options !== null && options !== void 0 ? options : {};
    const queryKey = (_a = queryOptions === null || queryOptions === void 0 ? void 0 : queryOptions.queryKey) !== null && _a !== void 0 ? _a : getGetQueryPlayerLineUpQueryKey(params);
    const queryFn = ({ signal }) => getQueryPlayerLineUp(params, signal);
    return Object.assign({ queryKey, queryFn }, queryOptions);
};
/**
 * @summary Get all PlayerLineUps
 */
export const useGetQueryPlayerLineUp = (params, options) => {
    const queryOptions = getGetQueryPlayerLineUpQueryOptions(params, options);
    const query = useQuery(queryOptions);
    query.queryKey = queryOptions.queryKey;
    return query;
};
/**
 * @summary Get count of PlayerLineUps
 */
export const getCountPlayerLineUp = (params, signal) => {
    return clientInstance({ url: `/playerLineUp/count`, method: 'GET',
        params, signal
    });
};
export const getGetCountPlayerLineUpQueryKey = (params) => {
    return [`/playerLineUp/count`, ...(params ? [params] : [])];
};
export const getGetCountPlayerLineUpQueryOptions = (params, options) => {
    var _a;
    const { query: queryOptions } = options !== null && options !== void 0 ? options : {};
    const queryKey = (_a = queryOptions === null || queryOptions === void 0 ? void 0 : queryOptions.queryKey) !== null && _a !== void 0 ? _a : getGetCountPlayerLineUpQueryKey(params);
    const queryFn = ({ signal }) => getCountPlayerLineUp(params, signal);
    return Object.assign({ queryKey, queryFn }, queryOptions);
};
/**
 * @summary Get count of PlayerLineUps
 */
export const useGetCountPlayerLineUp = (params, options) => {
    const queryOptions = getGetCountPlayerLineUpQueryOptions(params, options);
    const query = useQuery(queryOptions);
    query.queryKey = queryOptions.queryKey;
    return query;
};
/**
 * @summary Get one PlayerLineUp
 */
export const getOnePlayerLineUp = (id, signal) => {
    return clientInstance({ url: `/playerLineUp/${id}`, method: 'GET', signal
    });
};
export const getGetOnePlayerLineUpQueryKey = (id) => {
    return [`/playerLineUp/${id}`];
};
export const getGetOnePlayerLineUpQueryOptions = (id, options) => {
    var _a;
    const { query: queryOptions } = options !== null && options !== void 0 ? options : {};
    const queryKey = (_a = queryOptions === null || queryOptions === void 0 ? void 0 : queryOptions.queryKey) !== null && _a !== void 0 ? _a : getGetOnePlayerLineUpQueryKey(id);
    const queryFn = ({ signal }) => getOnePlayerLineUp(id, signal);
    return Object.assign({ queryKey, queryFn, enabled: !!(id) }, queryOptions);
};
/**
 * @summary Get one PlayerLineUp
 */
export const useGetOnePlayerLineUp = (id, options) => {
    const queryOptions = getGetOnePlayerLineUpQueryOptions(id, options);
    const query = useQuery(queryOptions);
    query.queryKey = queryOptions.queryKey;
    return query;
};
/**
 * @summary Update one PlayerLineUp
 */
export const updateOnePlayerLineUp = (id, playerLineUp) => {
    return clientInstance({ url: `/playerLineUp/${id}`, method: 'PATCH',
        headers: { 'Content-Type': 'application/json', },
        data: playerLineUp
    });
};
export const getUpdateOnePlayerLineUpMutationOptions = (options) => {
    const { mutation: mutationOptions } = options !== null && options !== void 0 ? options : {};
    const mutationFn = (props) => {
        const { id, data } = props !== null && props !== void 0 ? props : {};
        return updateOnePlayerLineUp(id, data);
    };
    return Object.assign({ mutationFn }, mutationOptions);
};
/**
* @summary Update one PlayerLineUp
*/
export const useUpdateOnePlayerLineUp = (options) => {
    const mutationOptions = getUpdateOnePlayerLineUpMutationOptions(options);
    return useMutation(mutationOptions);
};
/**
* @summary Delete one PlayerLineUp
*/
export const deleteOnePlayerLineUp = (id) => {
    return clientInstance({ url: `/playerLineUp/${id}`, method: 'DELETE'
    });
};
export const getDeleteOnePlayerLineUpMutationOptions = (options) => {
    const { mutation: mutationOptions } = options !== null && options !== void 0 ? options : {};
    const mutationFn = (props) => {
        const { id } = props !== null && props !== void 0 ? props : {};
        return deleteOnePlayerLineUp(id);
    };
    return Object.assign({ mutationFn }, mutationOptions);
};
/**
* @summary Delete one PlayerLineUp
*/
export const useDeleteOnePlayerLineUp = (options) => {
    const mutationOptions = getDeleteOnePlayerLineUpMutationOptions(options);
    return useMutation(mutationOptions);
};
/**
* @summary Upload a file for PlayerLineUp
*/
export const uploadPlayerLineUp = () => {
    return clientInstance({ url: `/playerLineUp/upload`, method: 'POST'
    });
};
export const getUploadPlayerLineUpMutationOptions = (options) => {
    const { mutation: mutationOptions } = options !== null && options !== void 0 ? options : {};
    const mutationFn = () => {
        return uploadPlayerLineUp();
    };
    return Object.assign({ mutationFn }, mutationOptions);
};
/**
* @summary Upload a file for PlayerLineUp
*/
export const useUploadPlayerLineUp = (options) => {
    const mutationOptions = getUploadPlayerLineUpMutationOptions(options);
    return useMutation(mutationOptions);
};
/**
* @summary Download file related to PlayerLineUp
*/
export const downloadPlayerLineUp = (filename, signal) => {
    return clientInstance({ url: `/playerLineUp/download/${filename}`, method: 'GET', signal
    });
};
export const getDownloadPlayerLineUpQueryKey = (filename) => {
    return [`/playerLineUp/download/${filename}`];
};
export const getDownloadPlayerLineUpQueryOptions = (filename, options) => {
    var _a;
    const { query: queryOptions } = options !== null && options !== void 0 ? options : {};
    const queryKey = (_a = queryOptions === null || queryOptions === void 0 ? void 0 : queryOptions.queryKey) !== null && _a !== void 0 ? _a : getDownloadPlayerLineUpQueryKey(filename);
    const queryFn = ({ signal }) => downloadPlayerLineUp(filename, signal);
    return Object.assign({ queryKey, queryFn, enabled: !!(filename) }, queryOptions);
};
/**
 * @summary Download file related to PlayerLineUp
 */
export const useDownloadPlayerLineUp = (filename, options) => {
    const queryOptions = getDownloadPlayerLineUpQueryOptions(filename, options);
    const query = useQuery(queryOptions);
    query.queryKey = queryOptions.queryKey;
    return query;
};
//# sourceMappingURL=player-line-up.js.map