/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * I Watch Football API
 * The API Docs for I Watch Football
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import { clientInstance } from '../client-instance';
/**
 * @summary Create Position
 */
export const createPosition = (createPositionDTO) => {
    return clientInstance({ url: `/position`, method: 'POST',
        headers: { 'Content-Type': 'application/json', },
        data: createPositionDTO
    });
};
export const getCreatePositionMutationOptions = (options) => {
    const { mutation: mutationOptions } = options !== null && options !== void 0 ? options : {};
    const mutationFn = (props) => {
        const { data } = props !== null && props !== void 0 ? props : {};
        return createPosition(data);
    };
    return Object.assign({ mutationFn }, mutationOptions);
};
/**
* @summary Create Position
*/
export const useCreatePosition = (options) => {
    const mutationOptions = getCreatePositionMutationOptions(options);
    return useMutation(mutationOptions);
};
/**
* @summary Get all Positions
*/
export const getAllPosition = (signal) => {
    return clientInstance({ url: `/position`, method: 'GET', signal
    });
};
export const getGetAllPositionQueryKey = () => {
    return [`/position`];
};
export const getGetAllPositionQueryOptions = (options) => {
    var _a;
    const { query: queryOptions } = options !== null && options !== void 0 ? options : {};
    const queryKey = (_a = queryOptions === null || queryOptions === void 0 ? void 0 : queryOptions.queryKey) !== null && _a !== void 0 ? _a : getGetAllPositionQueryKey();
    const queryFn = ({ signal }) => getAllPosition(signal);
    return Object.assign({ queryKey, queryFn }, queryOptions);
};
/**
 * @summary Get all Positions
 */
export const useGetAllPosition = (options) => {
    const queryOptions = getGetAllPositionQueryOptions(options);
    const query = useQuery(queryOptions);
    query.queryKey = queryOptions.queryKey;
    return query;
};
/**
 * @summary Get all Positions
 */
export const getQueryPosition = (params, signal) => {
    return clientInstance({ url: `/position/query`, method: 'GET',
        params, signal
    });
};
export const getGetQueryPositionQueryKey = (params) => {
    return [`/position/query`, ...(params ? [params] : [])];
};
export const getGetQueryPositionQueryOptions = (params, options) => {
    var _a;
    const { query: queryOptions } = options !== null && options !== void 0 ? options : {};
    const queryKey = (_a = queryOptions === null || queryOptions === void 0 ? void 0 : queryOptions.queryKey) !== null && _a !== void 0 ? _a : getGetQueryPositionQueryKey(params);
    const queryFn = ({ signal }) => getQueryPosition(params, signal);
    return Object.assign({ queryKey, queryFn }, queryOptions);
};
/**
 * @summary Get all Positions
 */
export const useGetQueryPosition = (params, options) => {
    const queryOptions = getGetQueryPositionQueryOptions(params, options);
    const query = useQuery(queryOptions);
    query.queryKey = queryOptions.queryKey;
    return query;
};
/**
 * @summary Get count of Positions
 */
export const getCountPosition = (params, signal) => {
    return clientInstance({ url: `/position/count`, method: 'GET',
        params, signal
    });
};
export const getGetCountPositionQueryKey = (params) => {
    return [`/position/count`, ...(params ? [params] : [])];
};
export const getGetCountPositionQueryOptions = (params, options) => {
    var _a;
    const { query: queryOptions } = options !== null && options !== void 0 ? options : {};
    const queryKey = (_a = queryOptions === null || queryOptions === void 0 ? void 0 : queryOptions.queryKey) !== null && _a !== void 0 ? _a : getGetCountPositionQueryKey(params);
    const queryFn = ({ signal }) => getCountPosition(params, signal);
    return Object.assign({ queryKey, queryFn }, queryOptions);
};
/**
 * @summary Get count of Positions
 */
export const useGetCountPosition = (params, options) => {
    const queryOptions = getGetCountPositionQueryOptions(params, options);
    const query = useQuery(queryOptions);
    query.queryKey = queryOptions.queryKey;
    return query;
};
/**
 * @summary Get one Position
 */
export const getOnePosition = (id, signal) => {
    return clientInstance({ url: `/position/${id}`, method: 'GET', signal
    });
};
export const getGetOnePositionQueryKey = (id) => {
    return [`/position/${id}`];
};
export const getGetOnePositionQueryOptions = (id, options) => {
    var _a;
    const { query: queryOptions } = options !== null && options !== void 0 ? options : {};
    const queryKey = (_a = queryOptions === null || queryOptions === void 0 ? void 0 : queryOptions.queryKey) !== null && _a !== void 0 ? _a : getGetOnePositionQueryKey(id);
    const queryFn = ({ signal }) => getOnePosition(id, signal);
    return Object.assign({ queryKey, queryFn, enabled: !!(id) }, queryOptions);
};
/**
 * @summary Get one Position
 */
export const useGetOnePosition = (id, options) => {
    const queryOptions = getGetOnePositionQueryOptions(id, options);
    const query = useQuery(queryOptions);
    query.queryKey = queryOptions.queryKey;
    return query;
};
/**
 * @summary Update one Position
 */
export const updateOnePosition = (id, position) => {
    return clientInstance({ url: `/position/${id}`, method: 'PATCH',
        headers: { 'Content-Type': 'application/json', },
        data: position
    });
};
export const getUpdateOnePositionMutationOptions = (options) => {
    const { mutation: mutationOptions } = options !== null && options !== void 0 ? options : {};
    const mutationFn = (props) => {
        const { id, data } = props !== null && props !== void 0 ? props : {};
        return updateOnePosition(id, data);
    };
    return Object.assign({ mutationFn }, mutationOptions);
};
/**
* @summary Update one Position
*/
export const useUpdateOnePosition = (options) => {
    const mutationOptions = getUpdateOnePositionMutationOptions(options);
    return useMutation(mutationOptions);
};
/**
* @summary Delete one Position
*/
export const deleteOnePosition = (id) => {
    return clientInstance({ url: `/position/${id}`, method: 'DELETE'
    });
};
export const getDeleteOnePositionMutationOptions = (options) => {
    const { mutation: mutationOptions } = options !== null && options !== void 0 ? options : {};
    const mutationFn = (props) => {
        const { id } = props !== null && props !== void 0 ? props : {};
        return deleteOnePosition(id);
    };
    return Object.assign({ mutationFn }, mutationOptions);
};
/**
* @summary Delete one Position
*/
export const useDeleteOnePosition = (options) => {
    const mutationOptions = getDeleteOnePositionMutationOptions(options);
    return useMutation(mutationOptions);
};
/**
* @summary Upload a file for Position
*/
export const uploadPosition = () => {
    return clientInstance({ url: `/position/upload`, method: 'POST'
    });
};
export const getUploadPositionMutationOptions = (options) => {
    const { mutation: mutationOptions } = options !== null && options !== void 0 ? options : {};
    const mutationFn = () => {
        return uploadPosition();
    };
    return Object.assign({ mutationFn }, mutationOptions);
};
/**
* @summary Upload a file for Position
*/
export const useUploadPosition = (options) => {
    const mutationOptions = getUploadPositionMutationOptions(options);
    return useMutation(mutationOptions);
};
/**
* @summary Download file related to Position
*/
export const downloadPosition = (filename, signal) => {
    return clientInstance({ url: `/position/download/${filename}`, method: 'GET', signal
    });
};
export const getDownloadPositionQueryKey = (filename) => {
    return [`/position/download/${filename}`];
};
export const getDownloadPositionQueryOptions = (filename, options) => {
    var _a;
    const { query: queryOptions } = options !== null && options !== void 0 ? options : {};
    const queryKey = (_a = queryOptions === null || queryOptions === void 0 ? void 0 : queryOptions.queryKey) !== null && _a !== void 0 ? _a : getDownloadPositionQueryKey(filename);
    const queryFn = ({ signal }) => downloadPosition(filename, signal);
    return Object.assign({ queryKey, queryFn, enabled: !!(filename) }, queryOptions);
};
/**
 * @summary Download file related to Position
 */
export const useDownloadPosition = (filename, options) => {
    const queryOptions = getDownloadPositionQueryOptions(filename, options);
    const query = useQuery(queryOptions);
    query.queryKey = queryOptions.queryKey;
    return query;
};
//# sourceMappingURL=position.js.map