/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * I Watch Football API
 * The API Docs for I Watch Football
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query'
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query'
import type {
  CreateStadiumDTO,
  GetCountStadiumParams,
  GetQueryStadiumParams,
  Stadium
} from './iWatchFootballAPI.schemas'
import { clientInstance } from '../client-instance';




/**
 * @summary Create Stadium
 */
export const createStadium = (
    createStadiumDTO: CreateStadiumDTO,
 ) => {
      
      
      return clientInstance<Stadium>(
      {url: `/stadium`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createStadiumDTO
    },
      );
    }
  


export const getCreateStadiumMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createStadium>>, TError,{data: CreateStadiumDTO}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof createStadium>>, TError,{data: CreateStadiumDTO}, TContext> => {
const {mutation: mutationOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createStadium>>, {data: CreateStadiumDTO}> = (props) => {
          const {data} = props ?? {};

          return  createStadium(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateStadiumMutationResult = NonNullable<Awaited<ReturnType<typeof createStadium>>>
    export type CreateStadiumMutationBody = CreateStadiumDTO
    export type CreateStadiumMutationError = void

    /**
 * @summary Create Stadium
 */
export const useCreateStadium = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createStadium>>, TError,{data: CreateStadiumDTO}, TContext>, }
): UseMutationResult<
        Awaited<ReturnType<typeof createStadium>>,
        TError,
        {data: CreateStadiumDTO},
        TContext
      > => {

      const mutationOptions = getCreateStadiumMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * @summary Get all Stadiums
 */
export const getAllStadium = (
    
 signal?: AbortSignal
) => {
      
      
      return clientInstance<Stadium[]>(
      {url: `/stadium`, method: 'GET', signal
    },
      );
    }
  

export const getGetAllStadiumQueryKey = () => {
    return [`/stadium`] as const;
    }

    
export const getGetAllStadiumQueryOptions = <TData = Awaited<ReturnType<typeof getAllStadium>>, TError = void>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getAllStadium>>, TError, TData>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAllStadiumQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAllStadium>>> = ({ signal }) => getAllStadium(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAllStadium>>, TError, TData> & { queryKey: QueryKey }
}

export type GetAllStadiumQueryResult = NonNullable<Awaited<ReturnType<typeof getAllStadium>>>
export type GetAllStadiumQueryError = void

/**
 * @summary Get all Stadiums
 */
export const useGetAllStadium = <TData = Awaited<ReturnType<typeof getAllStadium>>, TError = void>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getAllStadium>>, TError, TData>, }

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getGetAllStadiumQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Get all Stadiums
 */
export const getQueryStadium = (
    params?: GetQueryStadiumParams,
 signal?: AbortSignal
) => {
      
      
      return clientInstance<Stadium[]>(
      {url: `/stadium/query`, method: 'GET',
        params, signal
    },
      );
    }
  

export const getGetQueryStadiumQueryKey = (params?: GetQueryStadiumParams,) => {
    return [`/stadium/query`, ...(params ? [params]: [])] as const;
    }

    
export const getGetQueryStadiumQueryOptions = <TData = Awaited<ReturnType<typeof getQueryStadium>>, TError = void>(params?: GetQueryStadiumParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getQueryStadium>>, TError, TData>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetQueryStadiumQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getQueryStadium>>> = ({ signal }) => getQueryStadium(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getQueryStadium>>, TError, TData> & { queryKey: QueryKey }
}

export type GetQueryStadiumQueryResult = NonNullable<Awaited<ReturnType<typeof getQueryStadium>>>
export type GetQueryStadiumQueryError = void

/**
 * @summary Get all Stadiums
 */
export const useGetQueryStadium = <TData = Awaited<ReturnType<typeof getQueryStadium>>, TError = void>(
 params?: GetQueryStadiumParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getQueryStadium>>, TError, TData>, }

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getGetQueryStadiumQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Get count of Stadiums
 */
export const getCountStadium = (
    params?: GetCountStadiumParams,
 signal?: AbortSignal
) => {
      
      
      return clientInstance<number>(
      {url: `/stadium/count`, method: 'GET',
        params, signal
    },
      );
    }
  

export const getGetCountStadiumQueryKey = (params?: GetCountStadiumParams,) => {
    return [`/stadium/count`, ...(params ? [params]: [])] as const;
    }

    
export const getGetCountStadiumQueryOptions = <TData = Awaited<ReturnType<typeof getCountStadium>>, TError = void>(params?: GetCountStadiumParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getCountStadium>>, TError, TData>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetCountStadiumQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getCountStadium>>> = ({ signal }) => getCountStadium(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getCountStadium>>, TError, TData> & { queryKey: QueryKey }
}

export type GetCountStadiumQueryResult = NonNullable<Awaited<ReturnType<typeof getCountStadium>>>
export type GetCountStadiumQueryError = void

/**
 * @summary Get count of Stadiums
 */
export const useGetCountStadium = <TData = Awaited<ReturnType<typeof getCountStadium>>, TError = void>(
 params?: GetCountStadiumParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getCountStadium>>, TError, TData>, }

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getGetCountStadiumQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Get one Stadium
 */
export const getOneStadium = (
    id: number,
 signal?: AbortSignal
) => {
      
      
      return clientInstance<Stadium>(
      {url: `/stadium/${id}`, method: 'GET', signal
    },
      );
    }
  

export const getGetOneStadiumQueryKey = (id: number,) => {
    return [`/stadium/${id}`] as const;
    }

    
export const getGetOneStadiumQueryOptions = <TData = Awaited<ReturnType<typeof getOneStadium>>, TError = void>(id: number, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getOneStadium>>, TError, TData>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetOneStadiumQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getOneStadium>>> = ({ signal }) => getOneStadium(id, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getOneStadium>>, TError, TData> & { queryKey: QueryKey }
}

export type GetOneStadiumQueryResult = NonNullable<Awaited<ReturnType<typeof getOneStadium>>>
export type GetOneStadiumQueryError = void

/**
 * @summary Get one Stadium
 */
export const useGetOneStadium = <TData = Awaited<ReturnType<typeof getOneStadium>>, TError = void>(
 id: number, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getOneStadium>>, TError, TData>, }

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getGetOneStadiumQueryOptions(id,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Update one Stadium
 */
export const updateOneStadium = (
    id: number,
    stadium: Stadium,
 ) => {
      
      
      return clientInstance<void>(
      {url: `/stadium/${id}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: stadium
    },
      );
    }
  


export const getUpdateOneStadiumMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateOneStadium>>, TError,{id: number;data: Stadium}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof updateOneStadium>>, TError,{id: number;data: Stadium}, TContext> => {
const {mutation: mutationOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateOneStadium>>, {id: number;data: Stadium}> = (props) => {
          const {id,data} = props ?? {};

          return  updateOneStadium(id,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateOneStadiumMutationResult = NonNullable<Awaited<ReturnType<typeof updateOneStadium>>>
    export type UpdateOneStadiumMutationBody = Stadium
    export type UpdateOneStadiumMutationError = void

    /**
 * @summary Update one Stadium
 */
export const useUpdateOneStadium = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateOneStadium>>, TError,{id: number;data: Stadium}, TContext>, }
): UseMutationResult<
        Awaited<ReturnType<typeof updateOneStadium>>,
        TError,
        {id: number;data: Stadium},
        TContext
      > => {

      const mutationOptions = getUpdateOneStadiumMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * @summary Delete one Stadium
 */
export const deleteOneStadium = (
    id: number,
 ) => {
      
      
      return clientInstance<void>(
      {url: `/stadium/${id}`, method: 'DELETE'
    },
      );
    }
  


export const getDeleteOneStadiumMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteOneStadium>>, TError,{id: number}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof deleteOneStadium>>, TError,{id: number}, TContext> => {
const {mutation: mutationOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteOneStadium>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  deleteOneStadium(id,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteOneStadiumMutationResult = NonNullable<Awaited<ReturnType<typeof deleteOneStadium>>>
    
    export type DeleteOneStadiumMutationError = void

    /**
 * @summary Delete one Stadium
 */
export const useDeleteOneStadium = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteOneStadium>>, TError,{id: number}, TContext>, }
): UseMutationResult<
        Awaited<ReturnType<typeof deleteOneStadium>>,
        TError,
        {id: number},
        TContext
      > => {

      const mutationOptions = getDeleteOneStadiumMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * @summary Upload a file for Stadium
 */
export const uploadStadium = (
    
 ) => {
      
      
      return clientInstance<void>(
      {url: `/stadium/upload`, method: 'POST'
    },
      );
    }
  


export const getUploadStadiumMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof uploadStadium>>, TError,void, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof uploadStadium>>, TError,void, TContext> => {
const {mutation: mutationOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof uploadStadium>>, void> = () => {
          

          return  uploadStadium()
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UploadStadiumMutationResult = NonNullable<Awaited<ReturnType<typeof uploadStadium>>>
    
    export type UploadStadiumMutationError = void

    /**
 * @summary Upload a file for Stadium
 */
export const useUploadStadium = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof uploadStadium>>, TError,void, TContext>, }
): UseMutationResult<
        Awaited<ReturnType<typeof uploadStadium>>,
        TError,
        void,
        TContext
      > => {

      const mutationOptions = getUploadStadiumMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * @summary Download file related to Stadium
 */
export const downloadStadium = (
    filename: string,
 signal?: AbortSignal
) => {
      
      
      return clientInstance<void>(
      {url: `/stadium/download/${filename}`, method: 'GET', signal
    },
      );
    }
  

export const getDownloadStadiumQueryKey = (filename: string,) => {
    return [`/stadium/download/${filename}`] as const;
    }

    
export const getDownloadStadiumQueryOptions = <TData = Awaited<ReturnType<typeof downloadStadium>>, TError = void>(filename: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof downloadStadium>>, TError, TData>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getDownloadStadiumQueryKey(filename);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof downloadStadium>>> = ({ signal }) => downloadStadium(filename, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(filename), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof downloadStadium>>, TError, TData> & { queryKey: QueryKey }
}

export type DownloadStadiumQueryResult = NonNullable<Awaited<ReturnType<typeof downloadStadium>>>
export type DownloadStadiumQueryError = void

/**
 * @summary Download file related to Stadium
 */
export const useDownloadStadium = <TData = Awaited<ReturnType<typeof downloadStadium>>, TError = void>(
 filename: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof downloadStadium>>, TError, TData>, }

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getDownloadStadiumQueryOptions(filename,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



