/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * I Watch Football API
 * The API Docs for I Watch Football
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query'
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query'
import type {
  StatsBombControllerGetAvailableMatches200,
  StatsBombControllerGetSyncStatus200,
  StatsBombControllerSyncData200,
  StatsBombControllerTestSyncEventsOnly200,
  StatsBombControllerTestSyncPlayersOnly200,
  StatsBombControllerTestSyncSingleMatch200,
  StatsBombControllerTestSyncTeamsOnly200,
  StatsBombControllerTestTeamCreation200,
  StatsBombControllerTestTeamTypeDetection200Item
} from './iWatchFootballAPI.schemas'
import { clientInstance } from '../client-instance';




/**
 * Fetches data from StatsBomb Open Data repository and syncs it with the local database
 * @summary Sync StatsBomb data to database
 */
export const statsBombControllerSyncData = (
    
 ) => {
      
      
      return clientInstance<StatsBombControllerSyncData200>(
      {url: `/statsbomb/sync`, method: 'POST'
    },
      );
    }
  


export const getStatsBombControllerSyncDataMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof statsBombControllerSyncData>>, TError,void, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof statsBombControllerSyncData>>, TError,void, TContext> => {
const {mutation: mutationOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof statsBombControllerSyncData>>, void> = () => {
          

          return  statsBombControllerSyncData()
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type StatsBombControllerSyncDataMutationResult = NonNullable<Awaited<ReturnType<typeof statsBombControllerSyncData>>>
    
    export type StatsBombControllerSyncDataMutationError = void

    /**
 * @summary Sync StatsBomb data to database
 */
export const useStatsBombControllerSyncData = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof statsBombControllerSyncData>>, TError,void, TContext>, }
): UseMutationResult<
        Awaited<ReturnType<typeof statsBombControllerSyncData>>,
        TError,
        void,
        TContext
      > => {

      const mutationOptions = getStatsBombControllerSyncDataMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * Returns current database statistics and sync status
 * @summary Get sync status and statistics
 */
export const statsBombControllerGetSyncStatus = (
    
 signal?: AbortSignal
) => {
      
      
      return clientInstance<StatsBombControllerGetSyncStatus200>(
      {url: `/statsbomb/status`, method: 'GET', signal
    },
      );
    }
  

export const getStatsBombControllerGetSyncStatusQueryKey = () => {
    return [`/statsbomb/status`] as const;
    }

    
export const getStatsBombControllerGetSyncStatusQueryOptions = <TData = Awaited<ReturnType<typeof statsBombControllerGetSyncStatus>>, TError = unknown>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof statsBombControllerGetSyncStatus>>, TError, TData>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getStatsBombControllerGetSyncStatusQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof statsBombControllerGetSyncStatus>>> = ({ signal }) => statsBombControllerGetSyncStatus(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof statsBombControllerGetSyncStatus>>, TError, TData> & { queryKey: QueryKey }
}

export type StatsBombControllerGetSyncStatusQueryResult = NonNullable<Awaited<ReturnType<typeof statsBombControllerGetSyncStatus>>>
export type StatsBombControllerGetSyncStatusQueryError = unknown

/**
 * @summary Get sync status and statistics
 */
export const useStatsBombControllerGetSyncStatus = <TData = Awaited<ReturnType<typeof statsBombControllerGetSyncStatus>>, TError = unknown>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof statsBombControllerGetSyncStatus>>, TError, TData>, }

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getStatsBombControllerGetSyncStatusQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * Fetches and syncs only competition data from StatsBomb
 * @summary Sync competitions only
 */
export const statsBombControllerSyncCompetitions = (
    
 ) => {
      
      
      return clientInstance<void>(
      {url: `/statsbomb/sync/competitions`, method: 'POST'
    },
      );
    }
  


export const getStatsBombControllerSyncCompetitionsMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof statsBombControllerSyncCompetitions>>, TError,void, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof statsBombControllerSyncCompetitions>>, TError,void, TContext> => {
const {mutation: mutationOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof statsBombControllerSyncCompetitions>>, void> = () => {
          

          return  statsBombControllerSyncCompetitions()
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type StatsBombControllerSyncCompetitionsMutationResult = NonNullable<Awaited<ReturnType<typeof statsBombControllerSyncCompetitions>>>
    
    export type StatsBombControllerSyncCompetitionsMutationError = unknown

    /**
 * @summary Sync competitions only
 */
export const useStatsBombControllerSyncCompetitions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof statsBombControllerSyncCompetitions>>, TError,void, TContext>, }
): UseMutationResult<
        Awaited<ReturnType<typeof statsBombControllerSyncCompetitions>>,
        TError,
        void,
        TContext
      > => {

      const mutationOptions = getStatsBombControllerSyncCompetitionsMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * Fetches and syncs only team and player data from StatsBomb
 * @summary Sync teams and players only
 */
export const statsBombControllerSyncTeams = (
    
 ) => {
      
      
      return clientInstance<void>(
      {url: `/statsbomb/sync/teams`, method: 'POST'
    },
      );
    }
  


export const getStatsBombControllerSyncTeamsMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof statsBombControllerSyncTeams>>, TError,void, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof statsBombControllerSyncTeams>>, TError,void, TContext> => {
const {mutation: mutationOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof statsBombControllerSyncTeams>>, void> = () => {
          

          return  statsBombControllerSyncTeams()
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type StatsBombControllerSyncTeamsMutationResult = NonNullable<Awaited<ReturnType<typeof statsBombControllerSyncTeams>>>
    
    export type StatsBombControllerSyncTeamsMutationError = unknown

    /**
 * @summary Sync teams and players only
 */
export const useStatsBombControllerSyncTeams = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof statsBombControllerSyncTeams>>, TError,void, TContext>, }
): UseMutationResult<
        Awaited<ReturnType<typeof statsBombControllerSyncTeams>>,
        TError,
        void,
        TContext
      > => {

      const mutationOptions = getStatsBombControllerSyncTeamsMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * Fetches and syncs only fixture data from StatsBomb
 * @summary Sync fixtures only
 */
export const statsBombControllerSyncFixtures = (
    
 ) => {
      
      
      return clientInstance<void>(
      {url: `/statsbomb/sync/fixtures`, method: 'POST'
    },
      );
    }
  


export const getStatsBombControllerSyncFixturesMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof statsBombControllerSyncFixtures>>, TError,void, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof statsBombControllerSyncFixtures>>, TError,void, TContext> => {
const {mutation: mutationOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof statsBombControllerSyncFixtures>>, void> = () => {
          

          return  statsBombControllerSyncFixtures()
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type StatsBombControllerSyncFixturesMutationResult = NonNullable<Awaited<ReturnType<typeof statsBombControllerSyncFixtures>>>
    
    export type StatsBombControllerSyncFixturesMutationError = unknown

    /**
 * @summary Sync fixtures only
 */
export const useStatsBombControllerSyncFixtures = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof statsBombControllerSyncFixtures>>, TError,void, TContext>, }
): UseMutationResult<
        Awaited<ReturnType<typeof statsBombControllerSyncFixtures>>,
        TError,
        void,
        TContext
      > => {

      const mutationOptions = getStatsBombControllerSyncFixturesMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * Tests the team type detection logic with sample data to verify it correctly identifies club vs country teams
 * @summary Test team type detection
 */
export const statsBombControllerTestTeamTypeDetection = (
    
 signal?: AbortSignal
) => {
      
      
      return clientInstance<StatsBombControllerTestTeamTypeDetection200Item[]>(
      {url: `/statsbomb/test/team-types`, method: 'GET', signal
    },
      );
    }
  

export const getStatsBombControllerTestTeamTypeDetectionQueryKey = () => {
    return [`/statsbomb/test/team-types`] as const;
    }

    
export const getStatsBombControllerTestTeamTypeDetectionQueryOptions = <TData = Awaited<ReturnType<typeof statsBombControllerTestTeamTypeDetection>>, TError = unknown>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof statsBombControllerTestTeamTypeDetection>>, TError, TData>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getStatsBombControllerTestTeamTypeDetectionQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof statsBombControllerTestTeamTypeDetection>>> = ({ signal }) => statsBombControllerTestTeamTypeDetection(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof statsBombControllerTestTeamTypeDetection>>, TError, TData> & { queryKey: QueryKey }
}

export type StatsBombControllerTestTeamTypeDetectionQueryResult = NonNullable<Awaited<ReturnType<typeof statsBombControllerTestTeamTypeDetection>>>
export type StatsBombControllerTestTeamTypeDetectionQueryError = unknown

/**
 * @summary Test team type detection
 */
export const useStatsBombControllerTestTeamTypeDetection = <TData = Awaited<ReturnType<typeof statsBombControllerTestTeamTypeDetection>>, TError = unknown>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof statsBombControllerTestTeamTypeDetection>>, TError, TData>, }

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getStatsBombControllerTestTeamTypeDetectionQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * Tests the team creation functionality to verify it works correctly
 * @summary Test team creation
 */
export const statsBombControllerTestTeamCreation = (
    
 ) => {
      
      
      return clientInstance<StatsBombControllerTestTeamCreation200>(
      {url: `/statsbomb/test/team-creation`, method: 'POST'
    },
      );
    }
  


export const getStatsBombControllerTestTeamCreationMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof statsBombControllerTestTeamCreation>>, TError,void, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof statsBombControllerTestTeamCreation>>, TError,void, TContext> => {
const {mutation: mutationOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof statsBombControllerTestTeamCreation>>, void> = () => {
          

          return  statsBombControllerTestTeamCreation()
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type StatsBombControllerTestTeamCreationMutationResult = NonNullable<Awaited<ReturnType<typeof statsBombControllerTestTeamCreation>>>
    
    export type StatsBombControllerTestTeamCreationMutationError = unknown

    /**
 * @summary Test team creation
 */
export const useStatsBombControllerTestTeamCreation = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof statsBombControllerTestTeamCreation>>, TError,void, TContext>, }
): UseMutationResult<
        Awaited<ReturnType<typeof statsBombControllerTestTeamCreation>>,
        TError,
        void,
        TContext
      > => {

      const mutationOptions = getStatsBombControllerTestTeamCreationMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * Tests syncing only teams from StatsBomb data to verify the process works
 * @summary Test sync teams only
 */
export const statsBombControllerTestSyncTeamsOnly = (
    
 ) => {
      
      
      return clientInstance<StatsBombControllerTestSyncTeamsOnly200>(
      {url: `/statsbomb/test/sync-teams-only`, method: 'POST'
    },
      );
    }
  


export const getStatsBombControllerTestSyncTeamsOnlyMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof statsBombControllerTestSyncTeamsOnly>>, TError,void, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof statsBombControllerTestSyncTeamsOnly>>, TError,void, TContext> => {
const {mutation: mutationOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof statsBombControllerTestSyncTeamsOnly>>, void> = () => {
          

          return  statsBombControllerTestSyncTeamsOnly()
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type StatsBombControllerTestSyncTeamsOnlyMutationResult = NonNullable<Awaited<ReturnType<typeof statsBombControllerTestSyncTeamsOnly>>>
    
    export type StatsBombControllerTestSyncTeamsOnlyMutationError = unknown

    /**
 * @summary Test sync teams only
 */
export const useStatsBombControllerTestSyncTeamsOnly = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof statsBombControllerTestSyncTeamsOnly>>, TError,void, TContext>, }
): UseMutationResult<
        Awaited<ReturnType<typeof statsBombControllerTestSyncTeamsOnly>>,
        TError,
        void,
        TContext
      > => {

      const mutationOptions = getStatsBombControllerTestSyncTeamsOnlyMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * Tests syncing only events from StatsBomb data to verify the process works
 * @summary Test sync events only
 */
export const statsBombControllerTestSyncEventsOnly = (
    
 ) => {
      
      
      return clientInstance<StatsBombControllerTestSyncEventsOnly200>(
      {url: `/statsbomb/test/sync-events-only`, method: 'POST'
    },
      );
    }
  


export const getStatsBombControllerTestSyncEventsOnlyMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof statsBombControllerTestSyncEventsOnly>>, TError,void, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof statsBombControllerTestSyncEventsOnly>>, TError,void, TContext> => {
const {mutation: mutationOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof statsBombControllerTestSyncEventsOnly>>, void> = () => {
          

          return  statsBombControllerTestSyncEventsOnly()
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type StatsBombControllerTestSyncEventsOnlyMutationResult = NonNullable<Awaited<ReturnType<typeof statsBombControllerTestSyncEventsOnly>>>
    
    export type StatsBombControllerTestSyncEventsOnlyMutationError = unknown

    /**
 * @summary Test sync events only
 */
export const useStatsBombControllerTestSyncEventsOnly = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof statsBombControllerTestSyncEventsOnly>>, TError,void, TContext>, }
): UseMutationResult<
        Awaited<ReturnType<typeof statsBombControllerTestSyncEventsOnly>>,
        TError,
        void,
        TContext
      > => {

      const mutationOptions = getStatsBombControllerTestSyncEventsOnlyMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * Tests syncing only players from StatsBomb data to verify the process works
 * @summary Test sync players only
 */
export const statsBombControllerTestSyncPlayersOnly = (
    
 ) => {
      
      
      return clientInstance<StatsBombControllerTestSyncPlayersOnly200>(
      {url: `/statsbomb/test/sync-players-only`, method: 'POST'
    },
      );
    }
  


export const getStatsBombControllerTestSyncPlayersOnlyMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof statsBombControllerTestSyncPlayersOnly>>, TError,void, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof statsBombControllerTestSyncPlayersOnly>>, TError,void, TContext> => {
const {mutation: mutationOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof statsBombControllerTestSyncPlayersOnly>>, void> = () => {
          

          return  statsBombControllerTestSyncPlayersOnly()
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type StatsBombControllerTestSyncPlayersOnlyMutationResult = NonNullable<Awaited<ReturnType<typeof statsBombControllerTestSyncPlayersOnly>>>
    
    export type StatsBombControllerTestSyncPlayersOnlyMutationError = unknown

    /**
 * @summary Test sync players only
 */
export const useStatsBombControllerTestSyncPlayersOnly = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof statsBombControllerTestSyncPlayersOnly>>, TError,void, TContext>, }
): UseMutationResult<
        Awaited<ReturnType<typeof statsBombControllerTestSyncPlayersOnly>>,
        TError,
        void,
        TContext
      > => {

      const mutationOptions = getStatsBombControllerTestSyncPlayersOnlyMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * Tests syncing teams, players, and all events (goals, cards, substitutions) from a specific match ID to debug the process
 * @summary Test sync complete match data from a single match
 */
export const statsBombControllerTestSyncSingleMatch = (
    matchId: number,
 ) => {
      
      
      return clientInstance<StatsBombControllerTestSyncSingleMatch200>(
      {url: `/statsbomb/test/sync-single-match/${matchId}`, method: 'POST'
    },
      );
    }
  


export const getStatsBombControllerTestSyncSingleMatchMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof statsBombControllerTestSyncSingleMatch>>, TError,{matchId: number}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof statsBombControllerTestSyncSingleMatch>>, TError,{matchId: number}, TContext> => {
const {mutation: mutationOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof statsBombControllerTestSyncSingleMatch>>, {matchId: number}> = (props) => {
          const {matchId} = props ?? {};

          return  statsBombControllerTestSyncSingleMatch(matchId,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type StatsBombControllerTestSyncSingleMatchMutationResult = NonNullable<Awaited<ReturnType<typeof statsBombControllerTestSyncSingleMatch>>>
    
    export type StatsBombControllerTestSyncSingleMatchMutationError = unknown

    /**
 * @summary Test sync complete match data from a single match
 */
export const useStatsBombControllerTestSyncSingleMatch = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof statsBombControllerTestSyncSingleMatch>>, TError,{matchId: number}, TContext>, }
): UseMutationResult<
        Awaited<ReturnType<typeof statsBombControllerTestSyncSingleMatch>>,
        TError,
        {matchId: number},
        TContext
      > => {

      const mutationOptions = getStatsBombControllerTestSyncSingleMatchMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * Returns a list of available match IDs that can be used for single match testing
 * @summary Get available match IDs for testing
 */
export const statsBombControllerGetAvailableMatches = (
    
 signal?: AbortSignal
) => {
      
      
      return clientInstance<StatsBombControllerGetAvailableMatches200>(
      {url: `/statsbomb/test/available-matches`, method: 'GET', signal
    },
      );
    }
  

export const getStatsBombControllerGetAvailableMatchesQueryKey = () => {
    return [`/statsbomb/test/available-matches`] as const;
    }

    
export const getStatsBombControllerGetAvailableMatchesQueryOptions = <TData = Awaited<ReturnType<typeof statsBombControllerGetAvailableMatches>>, TError = unknown>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof statsBombControllerGetAvailableMatches>>, TError, TData>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getStatsBombControllerGetAvailableMatchesQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof statsBombControllerGetAvailableMatches>>> = ({ signal }) => statsBombControllerGetAvailableMatches(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof statsBombControllerGetAvailableMatches>>, TError, TData> & { queryKey: QueryKey }
}

export type StatsBombControllerGetAvailableMatchesQueryResult = NonNullable<Awaited<ReturnType<typeof statsBombControllerGetAvailableMatches>>>
export type StatsBombControllerGetAvailableMatchesQueryError = unknown

/**
 * @summary Get available match IDs for testing
 */
export const useStatsBombControllerGetAvailableMatches = <TData = Awaited<ReturnType<typeof statsBombControllerGetAvailableMatches>>, TError = unknown>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof statsBombControllerGetAvailableMatches>>, TError, TData>, }

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getStatsBombControllerGetAvailableMatchesQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



