/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * I Watch Football API
 * The API Docs for I Watch Football
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import { clientInstance } from '../client-instance';
/**
 * @summary Create TeamStadium
 */
export const createTeamStadium = (createTeamStadiumDTO) => {
    return clientInstance({ url: `/team-stadium`, method: 'POST',
        headers: { 'Content-Type': 'application/json', },
        data: createTeamStadiumDTO
    });
};
export const getCreateTeamStadiumMutationOptions = (options) => {
    const { mutation: mutationOptions } = options !== null && options !== void 0 ? options : {};
    const mutationFn = (props) => {
        const { data } = props !== null && props !== void 0 ? props : {};
        return createTeamStadium(data);
    };
    return Object.assign({ mutationFn }, mutationOptions);
};
/**
* @summary Create TeamStadium
*/
export const useCreateTeamStadium = (options) => {
    const mutationOptions = getCreateTeamStadiumMutationOptions(options);
    return useMutation(mutationOptions);
};
/**
* @summary Get all TeamStadiums
*/
export const getAllTeamStadium = (signal) => {
    return clientInstance({ url: `/team-stadium`, method: 'GET', signal
    });
};
export const getGetAllTeamStadiumQueryKey = () => {
    return [`/team-stadium`];
};
export const getGetAllTeamStadiumQueryOptions = (options) => {
    var _a;
    const { query: queryOptions } = options !== null && options !== void 0 ? options : {};
    const queryKey = (_a = queryOptions === null || queryOptions === void 0 ? void 0 : queryOptions.queryKey) !== null && _a !== void 0 ? _a : getGetAllTeamStadiumQueryKey();
    const queryFn = ({ signal }) => getAllTeamStadium(signal);
    return Object.assign({ queryKey, queryFn }, queryOptions);
};
/**
 * @summary Get all TeamStadiums
 */
export const useGetAllTeamStadium = (options) => {
    const queryOptions = getGetAllTeamStadiumQueryOptions(options);
    const query = useQuery(queryOptions);
    query.queryKey = queryOptions.queryKey;
    return query;
};
/**
 * @summary Get all TeamStadiums
 */
export const getQueryTeamStadium = (params, signal) => {
    return clientInstance({ url: `/team-stadium/query`, method: 'GET',
        params, signal
    });
};
export const getGetQueryTeamStadiumQueryKey = (params) => {
    return [`/team-stadium/query`, ...(params ? [params] : [])];
};
export const getGetQueryTeamStadiumQueryOptions = (params, options) => {
    var _a;
    const { query: queryOptions } = options !== null && options !== void 0 ? options : {};
    const queryKey = (_a = queryOptions === null || queryOptions === void 0 ? void 0 : queryOptions.queryKey) !== null && _a !== void 0 ? _a : getGetQueryTeamStadiumQueryKey(params);
    const queryFn = ({ signal }) => getQueryTeamStadium(params, signal);
    return Object.assign({ queryKey, queryFn }, queryOptions);
};
/**
 * @summary Get all TeamStadiums
 */
export const useGetQueryTeamStadium = (params, options) => {
    const queryOptions = getGetQueryTeamStadiumQueryOptions(params, options);
    const query = useQuery(queryOptions);
    query.queryKey = queryOptions.queryKey;
    return query;
};
/**
 * @summary Get count of TeamStadiums
 */
export const getCountTeamStadium = (params, signal) => {
    return clientInstance({ url: `/team-stadium/count`, method: 'GET',
        params, signal
    });
};
export const getGetCountTeamStadiumQueryKey = (params) => {
    return [`/team-stadium/count`, ...(params ? [params] : [])];
};
export const getGetCountTeamStadiumQueryOptions = (params, options) => {
    var _a;
    const { query: queryOptions } = options !== null && options !== void 0 ? options : {};
    const queryKey = (_a = queryOptions === null || queryOptions === void 0 ? void 0 : queryOptions.queryKey) !== null && _a !== void 0 ? _a : getGetCountTeamStadiumQueryKey(params);
    const queryFn = ({ signal }) => getCountTeamStadium(params, signal);
    return Object.assign({ queryKey, queryFn }, queryOptions);
};
/**
 * @summary Get count of TeamStadiums
 */
export const useGetCountTeamStadium = (params, options) => {
    const queryOptions = getGetCountTeamStadiumQueryOptions(params, options);
    const query = useQuery(queryOptions);
    query.queryKey = queryOptions.queryKey;
    return query;
};
/**
 * @summary Get one TeamStadium
 */
export const getOneTeamStadium = (id, signal) => {
    return clientInstance({ url: `/team-stadium/${id}`, method: 'GET', signal
    });
};
export const getGetOneTeamStadiumQueryKey = (id) => {
    return [`/team-stadium/${id}`];
};
export const getGetOneTeamStadiumQueryOptions = (id, options) => {
    var _a;
    const { query: queryOptions } = options !== null && options !== void 0 ? options : {};
    const queryKey = (_a = queryOptions === null || queryOptions === void 0 ? void 0 : queryOptions.queryKey) !== null && _a !== void 0 ? _a : getGetOneTeamStadiumQueryKey(id);
    const queryFn = ({ signal }) => getOneTeamStadium(id, signal);
    return Object.assign({ queryKey, queryFn, enabled: !!(id) }, queryOptions);
};
/**
 * @summary Get one TeamStadium
 */
export const useGetOneTeamStadium = (id, options) => {
    const queryOptions = getGetOneTeamStadiumQueryOptions(id, options);
    const query = useQuery(queryOptions);
    query.queryKey = queryOptions.queryKey;
    return query;
};
/**
 * @summary Update one TeamStadium
 */
export const updateOneTeamStadium = (id, teamStadium) => {
    return clientInstance({ url: `/team-stadium/${id}`, method: 'PATCH',
        headers: { 'Content-Type': 'application/json', },
        data: teamStadium
    });
};
export const getUpdateOneTeamStadiumMutationOptions = (options) => {
    const { mutation: mutationOptions } = options !== null && options !== void 0 ? options : {};
    const mutationFn = (props) => {
        const { id, data } = props !== null && props !== void 0 ? props : {};
        return updateOneTeamStadium(id, data);
    };
    return Object.assign({ mutationFn }, mutationOptions);
};
/**
* @summary Update one TeamStadium
*/
export const useUpdateOneTeamStadium = (options) => {
    const mutationOptions = getUpdateOneTeamStadiumMutationOptions(options);
    return useMutation(mutationOptions);
};
/**
* @summary Delete one TeamStadium
*/
export const deleteOneTeamStadium = (id) => {
    return clientInstance({ url: `/team-stadium/${id}`, method: 'DELETE'
    });
};
export const getDeleteOneTeamStadiumMutationOptions = (options) => {
    const { mutation: mutationOptions } = options !== null && options !== void 0 ? options : {};
    const mutationFn = (props) => {
        const { id } = props !== null && props !== void 0 ? props : {};
        return deleteOneTeamStadium(id);
    };
    return Object.assign({ mutationFn }, mutationOptions);
};
/**
* @summary Delete one TeamStadium
*/
export const useDeleteOneTeamStadium = (options) => {
    const mutationOptions = getDeleteOneTeamStadiumMutationOptions(options);
    return useMutation(mutationOptions);
};
/**
* @summary Upload a file for TeamStadium
*/
export const uploadTeamStadium = () => {
    return clientInstance({ url: `/team-stadium/upload`, method: 'POST'
    });
};
export const getUploadTeamStadiumMutationOptions = (options) => {
    const { mutation: mutationOptions } = options !== null && options !== void 0 ? options : {};
    const mutationFn = () => {
        return uploadTeamStadium();
    };
    return Object.assign({ mutationFn }, mutationOptions);
};
/**
* @summary Upload a file for TeamStadium
*/
export const useUploadTeamStadium = (options) => {
    const mutationOptions = getUploadTeamStadiumMutationOptions(options);
    return useMutation(mutationOptions);
};
/**
* @summary Download file related to TeamStadium
*/
export const downloadTeamStadium = (filename, signal) => {
    return clientInstance({ url: `/team-stadium/download/${filename}`, method: 'GET', signal
    });
};
export const getDownloadTeamStadiumQueryKey = (filename) => {
    return [`/team-stadium/download/${filename}`];
};
export const getDownloadTeamStadiumQueryOptions = (filename, options) => {
    var _a;
    const { query: queryOptions } = options !== null && options !== void 0 ? options : {};
    const queryKey = (_a = queryOptions === null || queryOptions === void 0 ? void 0 : queryOptions.queryKey) !== null && _a !== void 0 ? _a : getDownloadTeamStadiumQueryKey(filename);
    const queryFn = ({ signal }) => downloadTeamStadium(filename, signal);
    return Object.assign({ queryKey, queryFn, enabled: !!(filename) }, queryOptions);
};
/**
 * @summary Download file related to TeamStadium
 */
export const useDownloadTeamStadium = (filename, options) => {
    const queryOptions = getDownloadTeamStadiumQueryOptions(filename, options);
    const query = useQuery(queryOptions);
    query.queryKey = queryOptions.queryKey;
    return query;
};
//# sourceMappingURL=team-stadium.js.map