/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * I Watch Football API
 * The API Docs for I Watch Football
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query'
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query'
import type {
  CreateTicketDTO,
  GetCountTicketParams,
  GetQueryTicketParams,
  Ticket
} from './iWatchFootballAPI.schemas'
import { clientInstance } from '../client-instance';




/**
 * @summary Create Ticket
 */
export const createTicket = (
    createTicketDTO: CreateTicketDTO,
 ) => {
      
      
      return clientInstance<Ticket>(
      {url: `/ticket`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createTicketDTO
    },
      );
    }
  


export const getCreateTicketMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createTicket>>, TError,{data: CreateTicketDTO}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof createTicket>>, TError,{data: CreateTicketDTO}, TContext> => {
const {mutation: mutationOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createTicket>>, {data: CreateTicketDTO}> = (props) => {
          const {data} = props ?? {};

          return  createTicket(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateTicketMutationResult = NonNullable<Awaited<ReturnType<typeof createTicket>>>
    export type CreateTicketMutationBody = CreateTicketDTO
    export type CreateTicketMutationError = void

    /**
 * @summary Create Ticket
 */
export const useCreateTicket = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createTicket>>, TError,{data: CreateTicketDTO}, TContext>, }
): UseMutationResult<
        Awaited<ReturnType<typeof createTicket>>,
        TError,
        {data: CreateTicketDTO},
        TContext
      > => {

      const mutationOptions = getCreateTicketMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * @summary Get all Tickets
 */
export const getAllTicket = (
    
 signal?: AbortSignal
) => {
      
      
      return clientInstance<Ticket[]>(
      {url: `/ticket`, method: 'GET', signal
    },
      );
    }
  

export const getGetAllTicketQueryKey = () => {
    return [`/ticket`] as const;
    }

    
export const getGetAllTicketQueryOptions = <TData = Awaited<ReturnType<typeof getAllTicket>>, TError = void>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getAllTicket>>, TError, TData>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAllTicketQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAllTicket>>> = ({ signal }) => getAllTicket(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAllTicket>>, TError, TData> & { queryKey: QueryKey }
}

export type GetAllTicketQueryResult = NonNullable<Awaited<ReturnType<typeof getAllTicket>>>
export type GetAllTicketQueryError = void

/**
 * @summary Get all Tickets
 */
export const useGetAllTicket = <TData = Awaited<ReturnType<typeof getAllTicket>>, TError = void>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getAllTicket>>, TError, TData>, }

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getGetAllTicketQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Get all Tickets
 */
export const getQueryTicket = (
    params?: GetQueryTicketParams,
 signal?: AbortSignal
) => {
      
      
      return clientInstance<Ticket[]>(
      {url: `/ticket/query`, method: 'GET',
        params, signal
    },
      );
    }
  

export const getGetQueryTicketQueryKey = (params?: GetQueryTicketParams,) => {
    return [`/ticket/query`, ...(params ? [params]: [])] as const;
    }

    
export const getGetQueryTicketQueryOptions = <TData = Awaited<ReturnType<typeof getQueryTicket>>, TError = void>(params?: GetQueryTicketParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getQueryTicket>>, TError, TData>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetQueryTicketQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getQueryTicket>>> = ({ signal }) => getQueryTicket(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getQueryTicket>>, TError, TData> & { queryKey: QueryKey }
}

export type GetQueryTicketQueryResult = NonNullable<Awaited<ReturnType<typeof getQueryTicket>>>
export type GetQueryTicketQueryError = void

/**
 * @summary Get all Tickets
 */
export const useGetQueryTicket = <TData = Awaited<ReturnType<typeof getQueryTicket>>, TError = void>(
 params?: GetQueryTicketParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getQueryTicket>>, TError, TData>, }

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getGetQueryTicketQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Get count of Tickets
 */
export const getCountTicket = (
    params?: GetCountTicketParams,
 signal?: AbortSignal
) => {
      
      
      return clientInstance<number>(
      {url: `/ticket/count`, method: 'GET',
        params, signal
    },
      );
    }
  

export const getGetCountTicketQueryKey = (params?: GetCountTicketParams,) => {
    return [`/ticket/count`, ...(params ? [params]: [])] as const;
    }

    
export const getGetCountTicketQueryOptions = <TData = Awaited<ReturnType<typeof getCountTicket>>, TError = void>(params?: GetCountTicketParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getCountTicket>>, TError, TData>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetCountTicketQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getCountTicket>>> = ({ signal }) => getCountTicket(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getCountTicket>>, TError, TData> & { queryKey: QueryKey }
}

export type GetCountTicketQueryResult = NonNullable<Awaited<ReturnType<typeof getCountTicket>>>
export type GetCountTicketQueryError = void

/**
 * @summary Get count of Tickets
 */
export const useGetCountTicket = <TData = Awaited<ReturnType<typeof getCountTicket>>, TError = void>(
 params?: GetCountTicketParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getCountTicket>>, TError, TData>, }

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getGetCountTicketQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Get one Ticket
 */
export const getOneTicket = (
    id: number,
 signal?: AbortSignal
) => {
      
      
      return clientInstance<Ticket>(
      {url: `/ticket/${id}`, method: 'GET', signal
    },
      );
    }
  

export const getGetOneTicketQueryKey = (id: number,) => {
    return [`/ticket/${id}`] as const;
    }

    
export const getGetOneTicketQueryOptions = <TData = Awaited<ReturnType<typeof getOneTicket>>, TError = void>(id: number, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getOneTicket>>, TError, TData>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetOneTicketQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getOneTicket>>> = ({ signal }) => getOneTicket(id, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getOneTicket>>, TError, TData> & { queryKey: QueryKey }
}

export type GetOneTicketQueryResult = NonNullable<Awaited<ReturnType<typeof getOneTicket>>>
export type GetOneTicketQueryError = void

/**
 * @summary Get one Ticket
 */
export const useGetOneTicket = <TData = Awaited<ReturnType<typeof getOneTicket>>, TError = void>(
 id: number, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getOneTicket>>, TError, TData>, }

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getGetOneTicketQueryOptions(id,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Update one Ticket
 */
export const updateOneTicket = (
    id: number,
    ticket: Ticket,
 ) => {
      
      
      return clientInstance<void>(
      {url: `/ticket/${id}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: ticket
    },
      );
    }
  


export const getUpdateOneTicketMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateOneTicket>>, TError,{id: number;data: Ticket}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof updateOneTicket>>, TError,{id: number;data: Ticket}, TContext> => {
const {mutation: mutationOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateOneTicket>>, {id: number;data: Ticket}> = (props) => {
          const {id,data} = props ?? {};

          return  updateOneTicket(id,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateOneTicketMutationResult = NonNullable<Awaited<ReturnType<typeof updateOneTicket>>>
    export type UpdateOneTicketMutationBody = Ticket
    export type UpdateOneTicketMutationError = void

    /**
 * @summary Update one Ticket
 */
export const useUpdateOneTicket = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateOneTicket>>, TError,{id: number;data: Ticket}, TContext>, }
): UseMutationResult<
        Awaited<ReturnType<typeof updateOneTicket>>,
        TError,
        {id: number;data: Ticket},
        TContext
      > => {

      const mutationOptions = getUpdateOneTicketMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * @summary Delete one Ticket
 */
export const deleteOneTicket = (
    id: number,
 ) => {
      
      
      return clientInstance<void>(
      {url: `/ticket/${id}`, method: 'DELETE'
    },
      );
    }
  


export const getDeleteOneTicketMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteOneTicket>>, TError,{id: number}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof deleteOneTicket>>, TError,{id: number}, TContext> => {
const {mutation: mutationOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteOneTicket>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  deleteOneTicket(id,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteOneTicketMutationResult = NonNullable<Awaited<ReturnType<typeof deleteOneTicket>>>
    
    export type DeleteOneTicketMutationError = void

    /**
 * @summary Delete one Ticket
 */
export const useDeleteOneTicket = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteOneTicket>>, TError,{id: number}, TContext>, }
): UseMutationResult<
        Awaited<ReturnType<typeof deleteOneTicket>>,
        TError,
        {id: number},
        TContext
      > => {

      const mutationOptions = getDeleteOneTicketMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * @summary Upload a file for Ticket
 */
export const uploadTicket = (
    
 ) => {
      
      
      return clientInstance<void>(
      {url: `/ticket/upload`, method: 'POST'
    },
      );
    }
  


export const getUploadTicketMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof uploadTicket>>, TError,void, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof uploadTicket>>, TError,void, TContext> => {
const {mutation: mutationOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof uploadTicket>>, void> = () => {
          

          return  uploadTicket()
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UploadTicketMutationResult = NonNullable<Awaited<ReturnType<typeof uploadTicket>>>
    
    export type UploadTicketMutationError = void

    /**
 * @summary Upload a file for Ticket
 */
export const useUploadTicket = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof uploadTicket>>, TError,void, TContext>, }
): UseMutationResult<
        Awaited<ReturnType<typeof uploadTicket>>,
        TError,
        void,
        TContext
      > => {

      const mutationOptions = getUploadTicketMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * @summary Download file related to Ticket
 */
export const downloadTicket = (
    filename: string,
 signal?: AbortSignal
) => {
      
      
      return clientInstance<void>(
      {url: `/ticket/download/${filename}`, method: 'GET', signal
    },
      );
    }
  

export const getDownloadTicketQueryKey = (filename: string,) => {
    return [`/ticket/download/${filename}`] as const;
    }

    
export const getDownloadTicketQueryOptions = <TData = Awaited<ReturnType<typeof downloadTicket>>, TError = void>(filename: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof downloadTicket>>, TError, TData>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getDownloadTicketQueryKey(filename);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof downloadTicket>>> = ({ signal }) => downloadTicket(filename, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(filename), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof downloadTicket>>, TError, TData> & { queryKey: QueryKey }
}

export type DownloadTicketQueryResult = NonNullable<Awaited<ReturnType<typeof downloadTicket>>>
export type DownloadTicketQueryError = void

/**
 * @summary Download file related to Ticket
 */
export const useDownloadTicket = <TData = Awaited<ReturnType<typeof downloadTicket>>, TError = void>(
 filename: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof downloadTicket>>, TError, TData>, }

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getDownloadTicketQueryOptions(filename,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



