/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * I Watch Football API
 * The API Docs for I Watch Football
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query'
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query'
import type {
  UpdateTrackerPrivacyDto
} from './iWatchFootballAPI.schemas'
import { clientInstance } from '../client-instance';




/**
 * @summary Get tracker privacy settings for the current user
 */
export const trackerControllerGetPrivacy = (
    
 signal?: AbortSignal
) => {
      
      
      return clientInstance<void>(
      {url: `/tracker/privacy`, method: 'GET', signal
    },
      );
    }
  

export const getTrackerControllerGetPrivacyQueryKey = () => {
    return [`/tracker/privacy`] as const;
    }

    
export const getTrackerControllerGetPrivacyQueryOptions = <TData = Awaited<ReturnType<typeof trackerControllerGetPrivacy>>, TError = void>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof trackerControllerGetPrivacy>>, TError, TData>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getTrackerControllerGetPrivacyQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof trackerControllerGetPrivacy>>> = ({ signal }) => trackerControllerGetPrivacy(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof trackerControllerGetPrivacy>>, TError, TData> & { queryKey: QueryKey }
}

export type TrackerControllerGetPrivacyQueryResult = NonNullable<Awaited<ReturnType<typeof trackerControllerGetPrivacy>>>
export type TrackerControllerGetPrivacyQueryError = void

/**
 * @summary Get tracker privacy settings for the current user
 */
export const useTrackerControllerGetPrivacy = <TData = Awaited<ReturnType<typeof trackerControllerGetPrivacy>>, TError = void>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof trackerControllerGetPrivacy>>, TError, TData>, }

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getTrackerControllerGetPrivacyQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Update tracker privacy settings
 */
export const trackerControllerUpdatePrivacy = (
    updateTrackerPrivacyDto: UpdateTrackerPrivacyDto,
 ) => {
      
      
      return clientInstance<void>(
      {url: `/tracker/privacy`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: updateTrackerPrivacyDto
    },
      );
    }
  


export const getTrackerControllerUpdatePrivacyMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof trackerControllerUpdatePrivacy>>, TError,{data: UpdateTrackerPrivacyDto}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof trackerControllerUpdatePrivacy>>, TError,{data: UpdateTrackerPrivacyDto}, TContext> => {
const {mutation: mutationOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof trackerControllerUpdatePrivacy>>, {data: UpdateTrackerPrivacyDto}> = (props) => {
          const {data} = props ?? {};

          return  trackerControllerUpdatePrivacy(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type TrackerControllerUpdatePrivacyMutationResult = NonNullable<Awaited<ReturnType<typeof trackerControllerUpdatePrivacy>>>
    export type TrackerControllerUpdatePrivacyMutationBody = UpdateTrackerPrivacyDto
    export type TrackerControllerUpdatePrivacyMutationError = void

    /**
 * @summary Update tracker privacy settings
 */
export const useTrackerControllerUpdatePrivacy = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof trackerControllerUpdatePrivacy>>, TError,{data: UpdateTrackerPrivacyDto}, TContext>, }
): UseMutationResult<
        Awaited<ReturnType<typeof trackerControllerUpdatePrivacy>>,
        TError,
        {data: UpdateTrackerPrivacyDto},
        TContext
      > => {

      const mutationOptions = getTrackerControllerUpdatePrivacyMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * @summary Get aggregate tracker stats for a user (privacy-gated)
 */
export const trackerControllerGetStats = (
    userId: number,
 signal?: AbortSignal
) => {
      
      
      return clientInstance<void>(
      {url: `/tracker/stats/${userId}`, method: 'GET', signal
    },
      );
    }
  

export const getTrackerControllerGetStatsQueryKey = (userId: number,) => {
    return [`/tracker/stats/${userId}`] as const;
    }

    
export const getTrackerControllerGetStatsQueryOptions = <TData = Awaited<ReturnType<typeof trackerControllerGetStats>>, TError = void>(userId: number, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof trackerControllerGetStats>>, TError, TData>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getTrackerControllerGetStatsQueryKey(userId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof trackerControllerGetStats>>> = ({ signal }) => trackerControllerGetStats(userId, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(userId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof trackerControllerGetStats>>, TError, TData> & { queryKey: QueryKey }
}

export type TrackerControllerGetStatsQueryResult = NonNullable<Awaited<ReturnType<typeof trackerControllerGetStats>>>
export type TrackerControllerGetStatsQueryError = void

/**
 * @summary Get aggregate tracker stats for a user (privacy-gated)
 */
export const useTrackerControllerGetStats = <TData = Awaited<ReturnType<typeof trackerControllerGetStats>>, TError = void>(
 userId: number, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof trackerControllerGetStats>>, TError, TData>, }

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getTrackerControllerGetStatsQueryOptions(userId,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Compare tracker stats with a friend (premium)
 */
export const trackerControllerCompare = (
    friendUserId: number,
 signal?: AbortSignal
) => {
      
      
      return clientInstance<void>(
      {url: `/tracker/compare/${friendUserId}`, method: 'GET', signal
    },
      );
    }
  

export const getTrackerControllerCompareQueryKey = (friendUserId: number,) => {
    return [`/tracker/compare/${friendUserId}`] as const;
    }

    
export const getTrackerControllerCompareQueryOptions = <TData = Awaited<ReturnType<typeof trackerControllerCompare>>, TError = void>(friendUserId: number, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof trackerControllerCompare>>, TError, TData>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getTrackerControllerCompareQueryKey(friendUserId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof trackerControllerCompare>>> = ({ signal }) => trackerControllerCompare(friendUserId, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(friendUserId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof trackerControllerCompare>>, TError, TData> & { queryKey: QueryKey }
}

export type TrackerControllerCompareQueryResult = NonNullable<Awaited<ReturnType<typeof trackerControllerCompare>>>
export type TrackerControllerCompareQueryError = void

/**
 * @summary Compare tracker stats with a friend (premium)
 */
export const useTrackerControllerCompare = <TData = Awaited<ReturnType<typeof trackerControllerCompare>>, TError = void>(
 friendUserId: number, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof trackerControllerCompare>>, TError, TData>, }

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getTrackerControllerCompareQueryOptions(friendUserId,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



