/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * I Watch Football API
 * The API Docs for I Watch Football
 * OpenAPI spec version: 1.0
 */
import { useMutation } from '@tanstack/react-query';
import { clientInstance } from '../client-instance';
/**
 * @summary Stripe webhook (ticket payments + subscriptions)
 */
export const stripeWebhookControllerHandleStripeWebhook = () => {
    return clientInstance({ url: `/webhooks/stripe`, method: 'POST'
    });
};
export const getStripeWebhookControllerHandleStripeWebhookMutationOptions = (options) => {
    const { mutation: mutationOptions } = options !== null && options !== void 0 ? options : {};
    const mutationFn = () => {
        return stripeWebhookControllerHandleStripeWebhook();
    };
    return Object.assign({ mutationFn }, mutationOptions);
};
/**
* @summary Stripe webhook (ticket payments + subscriptions)
*/
export const useStripeWebhookControllerHandleStripeWebhook = (options) => {
    const mutationOptions = getStripeWebhookControllerHandleStripeWebhookMutationOptions(options);
    return useMutation(mutationOptions);
};
/**
* @summary Complete checkout after external PSP success (shared-secret trusted relay)
*/
export const paymentWebhookControllerHandlePaymentConfirmed = (webhookConfirmCheckoutDto) => {
    return clientInstance({ url: `/webhooks/payment`, method: 'POST',
        headers: { 'Content-Type': 'application/json', },
        data: webhookConfirmCheckoutDto
    });
};
export const getPaymentWebhookControllerHandlePaymentConfirmedMutationOptions = (options) => {
    const { mutation: mutationOptions } = options !== null && options !== void 0 ? options : {};
    const mutationFn = (props) => {
        const { data } = props !== null && props !== void 0 ? props : {};
        return paymentWebhookControllerHandlePaymentConfirmed(data);
    };
    return Object.assign({ mutationFn }, mutationOptions);
};
/**
* @summary Complete checkout after external PSP success (shared-secret trusted relay)
*/
export const usePaymentWebhookControllerHandlePaymentConfirmed = (options) => {
    const mutationOptions = getPaymentWebhookControllerHandlePaymentConfirmedMutationOptions(options);
    return useMutation(mutationOptions);
};
//# sourceMappingURL=webhooks.js.map