export enum LoyaltyEventType {
    SPENDING_MILESTONE = 'SPENDING_MILESTONE',
    BIRTHDAY = 'BIRTHDAY',
    FIRST_PURCHASE = 'FIRST_PURCHASE',
    REFERRAL = 'REFERRAL',
    ANNIVERSARY = 'ANNIVERSARY',
    CUSTOM = 'CUSTOM',
}

