export enum NotificationType {
    FRIEND_REQUEST_RECEIVED = 'FRIEND_REQUEST_RECEIVED',
    FRIEND_REQUEST_ACCEPTED = 'FRIEND_REQUEST_ACCEPTED',
    // Phase 3 — ticket demand
    TICKET_RESALE_AVAILABLE = 'TICKET_RESALE_AVAILABLE',
    // Phase 4 — marketplace
    LISTING_APPROVED = 'LISTING_APPROVED',
    LISTING_REJECTED = 'LISTING_REJECTED',
    PURCHASE_REQUESTED = 'PURCHASE_REQUESTED',
    TRANSFER_INITIATED = 'TRANSFER_INITIATED',
    TRANSFER_CONFIRMED = 'TRANSFER_CONFIRMED',
    DISPUTE_RAISED = 'DISPUTE_RAISED',
    // Phase 2 — attendance
    MATCH_REMINDER = 'MATCH_REMINDER',
    MATCH_CANCELLED = 'MATCH_CANCELLED',
    MATCH_POSTPONED = 'MATCH_POSTPONED',
    MATCH_SUSPENDED = 'MATCH_SUSPENDED',
}
