export enum PartnerType {
    TICKETING = 'TICKETING',
    HOSPITALITY = 'HOSPITALITY',
    TRAVEL = 'TRAVEL',
    PARKING = 'PARKING',
    HOTEL = 'HOTEL',
    MERCHANDISE = 'MERCHANDISE',
    GAMBLING = 'GAMBLING',
    OTHER = 'OTHER',
}

export enum PlacementType {
    MATCH_PREVIEW = 'MATCH_PREVIEW',
    ODDS_TAB = 'ODDS_TAB',
    STATS_SIDEBAR = 'STATS_SIDEBAR',
    PREDICTIONS_PAGE = 'PREDICTIONS_PAGE',
    NEWSLETTER = 'NEWSLETTER',
}
