/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
export { ApiError } from './core/ApiError';
export { CancelablePromise, CancelError } from './core/CancelablePromise';
export { OpenAPI } from './core/OpenAPI';
export type { OpenAPIConfig } from './core/OpenAPI';

export type { Address as AddressClient } from './models/Address';
export type { AuthResponse as AuthResponseClient } from './models/AuthResponse';
export type { Card as CardClient } from './models/Card';
export type { Competition as CompetitionClient } from './models/Competition';
export type { CreateAddressDTO as CreateAddressDTOClient } from './models/CreateAddressDTO';
export type { CreateCardDTO as CreateCardDTOClient } from './models/CreateCardDTO';
export type { CreateCompetitionDTO as CreateCompetitionDTOClient } from './models/CreateCompetitionDTO';
export type { CreateFixtureDTO as CreateFixtureDTOClient } from './models/CreateFixtureDTO';
export type { CreateFixtureRefereeDTO as CreateFixtureRefereeDTOClient } from './models/CreateFixtureRefereeDTO';
export type { CreateGenericTokenDTO as CreateGenericTokenDTOClient } from './models/CreateGenericTokenDTO';
export type { CreateGoalDTO as CreateGoalDTOClient } from './models/CreateGoalDTO';
export type { CreateInjuryDTO as CreateInjuryDTOClient } from './models/CreateInjuryDTO';
export type { CreateLineUpDTO as CreateLineUpDTOClient } from './models/CreateLineUpDTO';
export type { CreateLogDTO as CreateLogDTOClient } from './models/CreateLogDTO';
export type { CreateManagerDTO as CreateManagerDTOClient } from './models/CreateManagerDTO';
export type { CreateManagerEmploymentDTO as CreateManagerEmploymentDTOClient } from './models/CreateManagerEmploymentDTO';
export type { CreatePlayerDTO as CreatePlayerDTOClient } from './models/CreatePlayerDTO';
export type { CreatePlayerLineUpDTO as CreatePlayerLineUpDTOClient } from './models/CreatePlayerLineUpDTO';
export type { CreatePositionDTO as CreatePositionDTOClient } from './models/CreatePositionDTO';
export type { CreatePredictionDTO as CreatePredictionDTOClient } from './models/CreatePredictionDTO';
export type { CreateRefereeDTO as CreateRefereeDTOClient } from './models/CreateRefereeDTO';
export type { CreateSeasonDTO as CreateSeasonDTOClient } from './models/CreateSeasonDTO';
export type { CreateStadiumDTO as CreateStadiumDTOClient } from './models/CreateStadiumDTO';
export type { CreateSubstitutionDTO as CreateSubstitutionDTOClient } from './models/CreateSubstitutionDTO';
export type { CreateTeamCompetitionSeasonDTO as CreateTeamCompetitionSeasonDTOClient } from './models/CreateTeamCompetitionSeasonDTO';
export type { CreateTeamDTO as CreateTeamDTOClient } from './models/CreateTeamDTO';
export type { CreateTransferDTO as CreateTransferDTOClient } from './models/CreateTransferDTO';
export type { CreateTrophyDTO as CreateTrophyDTOClient } from './models/CreateTrophyDTO';
export type { CreateUserDTO as CreateUserDTOClient } from './models/CreateUserDTO';
export type { Fixture as FixtureClient } from './models/Fixture';
export type { FixtureReferee as FixtureRefereeClient } from './models/FixtureReferee';
export type { GenericToken as GenericTokenClient } from './models/GenericToken';
export type { Goal as GoalClient } from './models/Goal';
export type { Injury as InjuryClient } from './models/Injury';
export type { LineUp as LineUpClient } from './models/LineUp';
export type { Log as LogClient } from './models/Log';
export type { LoginBody as LoginBodyClient } from './models/LoginBody';
export type { Manager as ManagerClient } from './models/Manager';
export type { ManagerEmployment as ManagerEmploymentClient } from './models/ManagerEmployment';
export type { Player as PlayerClient } from './models/Player';
export type { PlayerLineUp as PlayerLineUpClient } from './models/PlayerLineUp';
export type { Position as PositionClient } from './models/Position';
export type { Prediction as PredictionClient } from './models/Prediction';
export type { Promise as PromiseClient } from './models/Promise';
export type { Referee as RefereeClient } from './models/Referee';
export type { RegisterBody as RegisterBodyClient } from './models/RegisterBody';
export type { Season as SeasonClient } from './models/Season';
export type { Stadium as StadiumClient } from './models/Stadium';
export type { Substitution as SubstitutionClient } from './models/Substitution';
export type { Team as TeamClient } from './models/Team';
export type { TeamCompetitionSeason as TeamCompetitionSeasonClient } from './models/TeamCompetitionSeason';
export type { Transfer as TransferClient } from './models/Transfer';
export type { Trophy as TrophyClient } from './models/Trophy';
export type { User as UserClient } from './models/User';

export { Address } from './services/Address';
export { Auth } from './services/Auth';
export { Card } from './services/Card';
export { Competition } from './services/Competition';
export { Fixture } from './services/Fixture';
export { FixtureReferee } from './services/FixtureReferee';
export { GenericToken } from './services/GenericToken';
export { Goal } from './services/Goal';
export { Injury } from './services/Injury';
export { LineUp } from './services/LineUp';
export { Log } from './services/Log';
export { Manager } from './services/Manager';
export { ManagerEmployment } from './services/ManagerEmployment';
export { Player } from './services/Player';
export { PlayerLineUp } from './services/PlayerLineUp';
export { Position } from './services/Position';
export { Prediction } from './services/Prediction';
export { Referee } from './services/Referee';
export { Season } from './services/Season';
export { Stadium } from './services/Stadium';
export { Substitution } from './services/Substitution';
export { Team } from './services/Team';
export { TeamCompetitionSeason } from './services/TeamCompetitionSeason';
export { Transfer } from './services/Transfer';
export { Trophy } from './services/Trophy';
export { User } from './services/User';
