/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * I Watch Football API
 * The API Docs for I Watch Football
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query'
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query'
import type {
  CreateUserDTO,
  GetCountParams,
  GetQueryParams,
  User
} from './iWatchFootballAPI.schemas'
import { clientInstance } from './client-instance';




/**
 * @summary Create User
 */
export const create = (
    createUserDTO: CreateUserDTO,
 ) => {
      
      
      return clientInstance<User>(
      {url: `/user`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createUserDTO
    },
      );
    }
  


export const getCreateMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof create>>, TError,{data: CreateUserDTO}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof create>>, TError,{data: CreateUserDTO}, TContext> => {
const {mutation: mutationOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof create>>, {data: CreateUserDTO}> = (props) => {
          const {data} = props ?? {};

          return  create(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateMutationResult = NonNullable<Awaited<ReturnType<typeof create>>>
    export type CreateMutationBody = CreateUserDTO
    export type CreateMutationError = void

    /**
 * @summary Create User
 */
export const useCreate = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof create>>, TError,{data: CreateUserDTO}, TContext>, }
): UseMutationResult<
        Awaited<ReturnType<typeof create>>,
        TError,
        {data: CreateUserDTO},
        TContext
      > => {

      const mutationOptions = getCreateMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * @summary Get all Users
 */
export const getAll = (
    
 signal?: AbortSignal
) => {
      
      
      return clientInstance<User[]>(
      {url: `/user`, method: 'GET', signal
    },
      );
    }
  

export const getGetAllQueryKey = () => {
    return [`/user`] as const;
    }

    
export const getGetAllQueryOptions = <TData = Awaited<ReturnType<typeof getAll>>, TError = void>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getAll>>, TError, TData>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAllQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAll>>> = ({ signal }) => getAll(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAll>>, TError, TData> & { queryKey: QueryKey }
}

export type GetAllQueryResult = NonNullable<Awaited<ReturnType<typeof getAll>>>
export type GetAllQueryError = void

/**
 * @summary Get all Users
 */
export const useGetAll = <TData = Awaited<ReturnType<typeof getAll>>, TError = void>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getAll>>, TError, TData>, }

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getGetAllQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Get all Users
 */
export const getQuery = (
    params?: GetQueryParams,
 signal?: AbortSignal
) => {
      
      
      return clientInstance<User[]>(
      {url: `/user/query`, method: 'GET',
        params, signal
    },
      );
    }
  

export const getGetQueryQueryKey = (params?: GetQueryParams,) => {
    return [`/user/query`, ...(params ? [params]: [])] as const;
    }

    
export const getGetQueryQueryOptions = <TData = Awaited<ReturnType<typeof getQuery>>, TError = void>(params?: GetQueryParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getQuery>>, TError, TData>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetQueryQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getQuery>>> = ({ signal }) => getQuery(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getQuery>>, TError, TData> & { queryKey: QueryKey }
}

export type GetQueryQueryResult = NonNullable<Awaited<ReturnType<typeof getQuery>>>
export type GetQueryQueryError = void

/**
 * @summary Get all Users
 */
export const useGetQuery = <TData = Awaited<ReturnType<typeof getQuery>>, TError = void>(
 params?: GetQueryParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getQuery>>, TError, TData>, }

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getGetQueryQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Get count of Users
 */
export const getCount = (
    params?: GetCountParams,
 signal?: AbortSignal
) => {
      
      
      return clientInstance<number>(
      {url: `/user/count`, method: 'GET',
        params, signal
    },
      );
    }
  

export const getGetCountQueryKey = (params?: GetCountParams,) => {
    return [`/user/count`, ...(params ? [params]: [])] as const;
    }

    
export const getGetCountQueryOptions = <TData = Awaited<ReturnType<typeof getCount>>, TError = void>(params?: GetCountParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getCount>>, TError, TData>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetCountQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getCount>>> = ({ signal }) => getCount(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getCount>>, TError, TData> & { queryKey: QueryKey }
}

export type GetCountQueryResult = NonNullable<Awaited<ReturnType<typeof getCount>>>
export type GetCountQueryError = void

/**
 * @summary Get count of Users
 */
export const useGetCount = <TData = Awaited<ReturnType<typeof getCount>>, TError = void>(
 params?: GetCountParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getCount>>, TError, TData>, }

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getGetCountQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Get one User
 */
export const getOne = (
    id: number,
 signal?: AbortSignal
) => {
      
      
      return clientInstance<User>(
      {url: `/user/${id}`, method: 'GET', signal
    },
      );
    }
  

export const getGetOneQueryKey = (id: number,) => {
    return [`/user/${id}`] as const;
    }

    
export const getGetOneQueryOptions = <TData = Awaited<ReturnType<typeof getOne>>, TError = void>(id: number, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getOne>>, TError, TData>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetOneQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getOne>>> = ({ signal }) => getOne(id, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getOne>>, TError, TData> & { queryKey: QueryKey }
}

export type GetOneQueryResult = NonNullable<Awaited<ReturnType<typeof getOne>>>
export type GetOneQueryError = void

/**
 * @summary Get one User
 */
export const useGetOne = <TData = Awaited<ReturnType<typeof getOne>>, TError = void>(
 id: number, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getOne>>, TError, TData>, }

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getGetOneQueryOptions(id,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Update one User
 */
export const updateOne = (
    id: number,
    user: User,
 ) => {
      
      
      return clientInstance<void>(
      {url: `/user/${id}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: user
    },
      );
    }
  


export const getUpdateOneMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateOne>>, TError,{id: number;data: User}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof updateOne>>, TError,{id: number;data: User}, TContext> => {
const {mutation: mutationOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateOne>>, {id: number;data: User}> = (props) => {
          const {id,data} = props ?? {};

          return  updateOne(id,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateOneMutationResult = NonNullable<Awaited<ReturnType<typeof updateOne>>>
    export type UpdateOneMutationBody = User
    export type UpdateOneMutationError = void

    /**
 * @summary Update one User
 */
export const useUpdateOne = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateOne>>, TError,{id: number;data: User}, TContext>, }
): UseMutationResult<
        Awaited<ReturnType<typeof updateOne>>,
        TError,
        {id: number;data: User},
        TContext
      > => {

      const mutationOptions = getUpdateOneMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * @summary Delete one User
 */
export const deleteOne = (
    id: number,
 ) => {
      
      
      return clientInstance<void>(
      {url: `/user/${id}`, method: 'DELETE'
    },
      );
    }
  


export const getDeleteOneMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteOne>>, TError,{id: number}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof deleteOne>>, TError,{id: number}, TContext> => {
const {mutation: mutationOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteOne>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  deleteOne(id,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteOneMutationResult = NonNullable<Awaited<ReturnType<typeof deleteOne>>>
    
    export type DeleteOneMutationError = void

    /**
 * @summary Delete one User
 */
export const useDeleteOne = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteOne>>, TError,{id: number}, TContext>, }
): UseMutationResult<
        Awaited<ReturnType<typeof deleteOne>>,
        TError,
        {id: number},
        TContext
      > => {

      const mutationOptions = getDeleteOneMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * @summary Upload a file for User
 */
export const upload = (
    
 ) => {
      
      
      return clientInstance<void>(
      {url: `/user/upload`, method: 'POST'
    },
      );
    }
  


export const getUploadMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof upload>>, TError,void, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof upload>>, TError,void, TContext> => {
const {mutation: mutationOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof upload>>, void> = () => {
          

          return  upload()
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UploadMutationResult = NonNullable<Awaited<ReturnType<typeof upload>>>
    
    export type UploadMutationError = void

    /**
 * @summary Upload a file for User
 */
export const useUpload = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof upload>>, TError,void, TContext>, }
): UseMutationResult<
        Awaited<ReturnType<typeof upload>>,
        TError,
        void,
        TContext
      > => {

      const mutationOptions = getUploadMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * @summary Download file related to User
 */
export const download = (
    filename: string,
 signal?: AbortSignal
) => {
      
      
      return clientInstance<void>(
      {url: `/user/download/${filename}`, method: 'GET', signal
    },
      );
    }
  

export const getDownloadQueryKey = (filename: string,) => {
    return [`/user/download/${filename}`] as const;
    }

    
export const getDownloadQueryOptions = <TData = Awaited<ReturnType<typeof download>>, TError = void>(filename: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof download>>, TError, TData>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getDownloadQueryKey(filename);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof download>>> = ({ signal }) => download(filename, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(filename), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof download>>, TError, TData> & { queryKey: QueryKey }
}

export type DownloadQueryResult = NonNullable<Awaited<ReturnType<typeof download>>>
export type DownloadQueryError = void

/**
 * @summary Download file related to User
 */
export const useDownload = <TData = Awaited<ReturnType<typeof download>>, TError = void>(
 filename: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof download>>, TError, TData>, }

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getDownloadQueryOptions(filename,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



