/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * I Watch Football API
 * The API Docs for I Watch Football
 * OpenAPI spec version: 1.0
 */
import {
  useQuery
} from '@tanstack/react-query'
import type {
  QueryFunction,
  QueryKey,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query'
import { clientInstance } from '../../client-instance';



/**
 * @summary Health check endpoint
 */
export const healthControllerCheck = (
    
 signal?: AbortSignal
) => {
      
      
      return clientInstance<void>(
      {url: `/health`, method: 'GET', signal
    },
      );
    }
  

export const getHealthControllerCheckQueryKey = () => {
    return [`/health`] as const;
    }

    
export const getHealthControllerCheckQueryOptions = <TData = Awaited<ReturnType<typeof healthControllerCheck>>, TError = unknown>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof healthControllerCheck>>, TError, TData>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getHealthControllerCheckQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof healthControllerCheck>>> = ({ signal }) => healthControllerCheck(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof healthControllerCheck>>, TError, TData> & { queryKey: QueryKey }
}

export type HealthControllerCheckQueryResult = NonNullable<Awaited<ReturnType<typeof healthControllerCheck>>>
export type HealthControllerCheckQueryError = unknown

/**
 * @summary Health check endpoint
 */
export const useHealthControllerCheck = <TData = Awaited<ReturnType<typeof healthControllerCheck>>, TError = unknown>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof healthControllerCheck>>, TError, TData>, }

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getHealthControllerCheckQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Readiness check endpoint
 */
export const healthControllerReady = (
    
 signal?: AbortSignal
) => {
      
      
      return clientInstance<void>(
      {url: `/health/ready`, method: 'GET', signal
    },
      );
    }
  

export const getHealthControllerReadyQueryKey = () => {
    return [`/health/ready`] as const;
    }

    
export const getHealthControllerReadyQueryOptions = <TData = Awaited<ReturnType<typeof healthControllerReady>>, TError = unknown>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof healthControllerReady>>, TError, TData>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getHealthControllerReadyQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof healthControllerReady>>> = ({ signal }) => healthControllerReady(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof healthControllerReady>>, TError, TData> & { queryKey: QueryKey }
}

export type HealthControllerReadyQueryResult = NonNullable<Awaited<ReturnType<typeof healthControllerReady>>>
export type HealthControllerReadyQueryError = unknown

/**
 * @summary Readiness check endpoint
 */
export const useHealthControllerReady = <TData = Awaited<ReturnType<typeof healthControllerReady>>, TError = unknown>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof healthControllerReady>>, TError, TData>, }

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getHealthControllerReadyQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Liveness check endpoint
 */
export const healthControllerLive = (
    
 signal?: AbortSignal
) => {
      
      
      return clientInstance<void>(
      {url: `/health/live`, method: 'GET', signal
    },
      );
    }
  

export const getHealthControllerLiveQueryKey = () => {
    return [`/health/live`] as const;
    }

    
export const getHealthControllerLiveQueryOptions = <TData = Awaited<ReturnType<typeof healthControllerLive>>, TError = unknown>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof healthControllerLive>>, TError, TData>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getHealthControllerLiveQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof healthControllerLive>>> = ({ signal }) => healthControllerLive(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof healthControllerLive>>, TError, TData> & { queryKey: QueryKey }
}

export type HealthControllerLiveQueryResult = NonNullable<Awaited<ReturnType<typeof healthControllerLive>>>
export type HealthControllerLiveQueryError = unknown

/**
 * @summary Liveness check endpoint
 */
export const useHealthControllerLive = <TData = Awaited<ReturnType<typeof healthControllerLive>>, TError = unknown>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof healthControllerLive>>, TError, TData>, }

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getHealthControllerLiveQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



