/** Metric keys shared by player page and attendance leaderboards. */
export const ADVANCED_STAT_METRICS = {
    XG: 'xg',
    XA: 'xa',
    SHOTS: 'shots',
    SHOTS_ON_TARGET: 'shotsOnTarget',
    HEADED_SHOTS: 'headedShots',
    KEY_PASSES: 'keyPasses',
    SUCCESSFUL_DRIBBLES: 'successfulDribbles',
    TOUCHES_IN_OPPOSITION_BOX: 'touchesInOppositionBox',
    INTERCEPTIONS: 'interceptions',
    FOULS_COMMITTED: 'foulsCommitted',
    RATING: 'rating',
} as const;

export type AdvancedStatMetricKey = (typeof ADVANCED_STAT_METRICS)[keyof typeof ADVANCED_STAT_METRICS];

export const ADVANCED_STAT_SOURCE = {
    PLAYER_FIXTURE_STAT: 'playerFixtureStat',
    GOAL: 'goal',
    CARD: 'card',
} as const;

export const ADVANCED_STAT_METRIC_SOURCE: Record<AdvancedStatMetricKey, string> = {
    [ADVANCED_STAT_METRICS.XG]: ADVANCED_STAT_SOURCE.PLAYER_FIXTURE_STAT,
    [ADVANCED_STAT_METRICS.XA]: ADVANCED_STAT_SOURCE.PLAYER_FIXTURE_STAT,
    [ADVANCED_STAT_METRICS.SHOTS]: ADVANCED_STAT_SOURCE.PLAYER_FIXTURE_STAT,
    [ADVANCED_STAT_METRICS.SHOTS_ON_TARGET]: ADVANCED_STAT_SOURCE.PLAYER_FIXTURE_STAT,
    [ADVANCED_STAT_METRICS.HEADED_SHOTS]: ADVANCED_STAT_SOURCE.PLAYER_FIXTURE_STAT,
    [ADVANCED_STAT_METRICS.KEY_PASSES]: ADVANCED_STAT_SOURCE.PLAYER_FIXTURE_STAT,
    [ADVANCED_STAT_METRICS.SUCCESSFUL_DRIBBLES]: ADVANCED_STAT_SOURCE.PLAYER_FIXTURE_STAT,
    [ADVANCED_STAT_METRICS.TOUCHES_IN_OPPOSITION_BOX]: ADVANCED_STAT_SOURCE.PLAYER_FIXTURE_STAT,
    [ADVANCED_STAT_METRICS.INTERCEPTIONS]: ADVANCED_STAT_SOURCE.PLAYER_FIXTURE_STAT,
    [ADVANCED_STAT_METRICS.FOULS_COMMITTED]: ADVANCED_STAT_SOURCE.PLAYER_FIXTURE_STAT,
    [ADVANCED_STAT_METRICS.RATING]: ADVANCED_STAT_SOURCE.PLAYER_FIXTURE_STAT,
};

export const ADVANCED_LEADERBOARD_LABELS: Record<AdvancedStatMetricKey, string> = {
    [ADVANCED_STAT_METRICS.XG]: 'Expected goals (xG)',
    [ADVANCED_STAT_METRICS.XA]: 'Expected assists (xA)',
    [ADVANCED_STAT_METRICS.SHOTS]: 'Shots',
    [ADVANCED_STAT_METRICS.SHOTS_ON_TARGET]: 'Shots on target',
    [ADVANCED_STAT_METRICS.HEADED_SHOTS]: 'Headed shots',
    [ADVANCED_STAT_METRICS.KEY_PASSES]: 'Key passes',
    [ADVANCED_STAT_METRICS.SUCCESSFUL_DRIBBLES]: 'Successful dribbles',
    [ADVANCED_STAT_METRICS.TOUCHES_IN_OPPOSITION_BOX]: 'Touches in opposition box',
    [ADVANCED_STAT_METRICS.INTERCEPTIONS]: 'Interceptions',
    [ADVANCED_STAT_METRICS.FOULS_COMMITTED]: 'Fouls committed',
    [ADVANCED_STAT_METRICS.RATING]: 'Rating',
};
