/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * I Watch Football API
 * The API Docs for I Watch Football
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query'
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query'
import { clientInstance } from '../../client-instance';



/**
 * @summary Manually trigger news aggregation
 */
export const newsAggregatorControllerTriggerAggregation = (
    
 ) => {
      
      
      return clientInstance<void>(
      {url: `/news-aggregation/trigger`, method: 'POST'
    },
      );
    }
  


export const getNewsAggregatorControllerTriggerAggregationMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof newsAggregatorControllerTriggerAggregation>>, TError,void, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof newsAggregatorControllerTriggerAggregation>>, TError,void, TContext> => {
const {mutation: mutationOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof newsAggregatorControllerTriggerAggregation>>, void> = () => {
          

          return  newsAggregatorControllerTriggerAggregation()
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type NewsAggregatorControllerTriggerAggregationMutationResult = NonNullable<Awaited<ReturnType<typeof newsAggregatorControllerTriggerAggregation>>>
    
    export type NewsAggregatorControllerTriggerAggregationMutationError = unknown

    /**
 * @summary Manually trigger news aggregation
 */
export const useNewsAggregatorControllerTriggerAggregation = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof newsAggregatorControllerTriggerAggregation>>, TError,void, TContext>, }
): UseMutationResult<
        Awaited<ReturnType<typeof newsAggregatorControllerTriggerAggregation>>,
        TError,
        void,
        TContext
      > => {

      const mutationOptions = getNewsAggregatorControllerTriggerAggregationMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * @summary Manually trigger news aggregation for a specific feed
 */
export const newsAggregatorControllerTriggerFeedAggregation = (
    feedName: string,
 ) => {
      
      
      return clientInstance<void>(
      {url: `/news-aggregation/trigger/${feedName}`, method: 'POST'
    },
      );
    }
  


export const getNewsAggregatorControllerTriggerFeedAggregationMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof newsAggregatorControllerTriggerFeedAggregation>>, TError,{feedName: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof newsAggregatorControllerTriggerFeedAggregation>>, TError,{feedName: string}, TContext> => {
const {mutation: mutationOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof newsAggregatorControllerTriggerFeedAggregation>>, {feedName: string}> = (props) => {
          const {feedName} = props ?? {};

          return  newsAggregatorControllerTriggerFeedAggregation(feedName,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type NewsAggregatorControllerTriggerFeedAggregationMutationResult = NonNullable<Awaited<ReturnType<typeof newsAggregatorControllerTriggerFeedAggregation>>>
    
    export type NewsAggregatorControllerTriggerFeedAggregationMutationError = unknown

    /**
 * @summary Manually trigger news aggregation for a specific feed
 */
export const useNewsAggregatorControllerTriggerFeedAggregation = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof newsAggregatorControllerTriggerFeedAggregation>>, TError,{feedName: string}, TContext>, }
): UseMutationResult<
        Awaited<ReturnType<typeof newsAggregatorControllerTriggerFeedAggregation>>,
        TError,
        {feedName: string},
        TContext
      > => {

      const mutationOptions = getNewsAggregatorControllerTriggerFeedAggregationMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * @summary Get news aggregation status
 */
export const newsAggregatorControllerGetStatus = (
    
 signal?: AbortSignal
) => {
      
      
      return clientInstance<void>(
      {url: `/news-aggregation/status`, method: 'GET', signal
    },
      );
    }
  

export const getNewsAggregatorControllerGetStatusQueryKey = () => {
    return [`/news-aggregation/status`] as const;
    }

    
export const getNewsAggregatorControllerGetStatusQueryOptions = <TData = Awaited<ReturnType<typeof newsAggregatorControllerGetStatus>>, TError = unknown>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof newsAggregatorControllerGetStatus>>, TError, TData>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getNewsAggregatorControllerGetStatusQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof newsAggregatorControllerGetStatus>>> = ({ signal }) => newsAggregatorControllerGetStatus(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof newsAggregatorControllerGetStatus>>, TError, TData> & { queryKey: QueryKey }
}

export type NewsAggregatorControllerGetStatusQueryResult = NonNullable<Awaited<ReturnType<typeof newsAggregatorControllerGetStatus>>>
export type NewsAggregatorControllerGetStatusQueryError = unknown

/**
 * @summary Get news aggregation status
 */
export const useNewsAggregatorControllerGetStatus = <TData = Awaited<ReturnType<typeof newsAggregatorControllerGetStatus>>, TError = unknown>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof newsAggregatorControllerGetStatus>>, TError, TData>, }

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getNewsAggregatorControllerGetStatusQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



